### ISSUE TITLE
How can dubbo-admin monitor all service groups

### ISSUE THREAD

**Issue by wanghany** [alibaba/dubbo#1004]
当前看很多文章配置都只讲解配置一个group信息，请问有方法可以同时监控多个group的信息或者所有group的信息么？

如果不行，请问有其他的方法去实现这个功能么

**Comment by chickenlj** [comment]
The reference implementation of monitor statistics do not categorize different groups.

**Comment by chickenlj** [comment]
dubbo/dubbo-ops#10
