### ISSUE TITLE
Will upgrade spring to the higher version?

### ISSUE THREAD

**Issue by wtta1812** [alibaba/dubbo#1023]
Spring 版本会升级吗？什么时间升级 ？

**Comment by chickenlj** [comment]
Dubbo already support spring-4.3.10 since 2.5.5, you can upgrade spring to higher version at your own project.
Official support for spring-5.x is still not in the plan.

**Comment by wtta1812** [comment]
tks

**Comment by lovepoem** [comment]
https://github.com/alibaba/dubbo/issues/1023
