### ISSUE TITLE
Timeline of REST support.

### ISSUE THREAD

**Issue by linyongfu2013** [alibaba/dubbo#1025]
大概什么时候实现支持 REST ？

**Comment by chickenlj** [comment]
#1001

**Comment by fanlei1988** [comment]
@chickenlj  希望dubbo 和 dubbox合并的同时也可以支持SpringMVC 的Rest实现， 因为我感觉dubbox 和swagger 兼容并不是很好，并且并不支持其他容器吧，比如说Undertow 
补充一点，swagger我一般用的是springfox-swagger2

**Comment by bamboolsu** [comment]
Restful 我想象用这个功能， 何时合并dubbox里的相应功能。

**Comment by chickenlj** [comment]
REST has been released in [2.6.0](https://github.com/alibaba/dubbo/releases).
