### ISSUE TITLE
Duplicated Component scan when Bean Class annotated @Service and Dubbo's @Service

### ISSUE THREAD

**Issue by mercyblitz** [alibaba/dubbo#1029]
If Bean Class annotated `@Service` and Dubbo's `@com.alibaba.dubbo.config.annotation.Service`,
and `@DubboComponentScan` and `@ComponentScan` were present on `@Configuration` Class, the Spring Context will scan this component twice.

Test cases:

## Test Configuration Class

```java
@EnableDubbo(scanBasePackages = "com.alibaba.dubbo.config.spring.context.annotation")
@ComponentScan(basePackages = "com.alibaba.dubbo.config.spring.context.annotation")
@PropertySource("META-INF/dubbb-provider.properties")
@EnableTransactionManagement
public static class TestProviderConfiguration {
}
```

## Service Class

```java
@com.alibaba.dubbo.config.annotation.Service(
        version = "2.5.7",
        application = "${demo.service.application}",
        protocol = "${demo.service.protocol}",
        registry = "${demo.service.registry}"
)
@Service
@Transactional
public class DemoServiceImpl implements DemoService {

    @Override
    public String sayName(String name) {
        return "Hello," + name;
    }

    @Override
    public Box getBox() {
        return new Box() {
            @Override
            public String getName() {
                return "MyBox";
            }
        };
    }
}
```

**Comment by mercyblitz** [comment]
This is a tolerated issue

**Comment by kirbylynx** [comment]
I think spring annotation @Service is no longer needed if dubbo's @Service annotated.
If dubbo service annotated, it means this service would be exposed for invocation by dubbo consumers. Why annotated spring service again for local invocation?

**Comment by chickenlj** [comment]
@kirbylynx What if one want a Service being exported as both` internal` and `dubbo`, and most importantly, this is not under our control. 
Maybe we can support assign `internal` spring  bean name on dubbo @Service, and forbid use spring @Service at the same time. Is this possible? @mercyblitz

**Comment by mercyblitz** [comment]
@chickenlj It could add a rule to restrict Spring's `@Service` and Dubbo's `@Service` , or it will throw a `IllegalAnnotationException`(new)

@kirbylynx  For now on , the aim of current issue is a compatible or tradeoff for realistic status.
