### ISSUE TITLE
Official support for spring-boot-starter

### ISSUE THREAD

**Issue by ganlanshugod** [alibaba/dubbo#1033]
有很多集成springboot的dubbo方案，但都是个人发布的，官方是否考虑做一个springboot的集成插件，需要的同学们支持我。

**Comment by oldratlee** [comment]
@ganlanshugod  

here https://github.com/dubbo/dubbo-spring-boot-project

**Comment by Comven** [comment]
Will this starter be updated recently, because there are many places that are not good for use  with this starter。

**Comment by lovepoem** [comment]
>

**Comment by Comven** [comment]
@lovepoem  3Q

**Comment by leyou240** [comment]
Looking forward to updated springboot-starter-dubbo!

**Comment by mercyblitz** [comment]
@leyou240 It will be released soon

**Comment by meiping05** [comment]
@EnableDubboConfigBindings(
        {
                @EnableDubboConfigBinding(prefix = "dubbo.application", type = ApplicationConfig.class),
                @EnableDubboConfigBinding(prefix = "dubbo.protocol", type = ProtocolConfig.class),
                @EnableDubboConfigBinding(prefix = "dubbo.provider", type = ProviderConfig.class),
                @EnableDubboConfigBinding(prefix = "dubbo.registry", type = RegistryConfig.class)
        }
)
@DubboComponentScan(basePackages = "...")

**Comment by zhangruhong** [comment]
Looking forward to updated springboot-starter-dubbo!
