### ISSUE TITLE
Is this a unuseful file？

### ISSUE THREAD

**Issue by lovepoem** [alibaba/dubbo#1034]
https://github.com/alibaba/dubbo/blob/d5284338d636bfec88e60292c750eecf521a2173/tree.txt#L6

@mercyblitz

**Comment by chickenlj** [comment]
Yes, it's useless.  Mercyblitz must have made a PR based on a previous branch which contains this useless file. We should always create a PR based on the latest `master` branch.

**Comment by chickenlj** [comment]
It's been removed

**Comment by lovepoem** [comment]
ok
