### ISSUE TITLE
the way to get dubbo interface proxy object from spring context？

### ISSUE THREAD

**Issue by Comven** [alibaba/dubbo#1035]
When the @Reference annotation is used, is there a way to get it from the spring context, such as ApplicationContext.getBean ("Dubbo interface name")?  I printed the details of ApplicationContext, and I couldn't find the bean injected by @Reference. Is there a way to achieve it

**Comment by Comven** [comment]
by the way, when I configiured it by <dubbo:reference> with xml，it works fine.

**Comment by mercyblitz** [comment]
`@Reference`  works for setter injection , like  `@Autowired`.

If application invoked `<dubbo:reference>` under XMl-based configuration , the `ReferenceBean` bean will be present in `ApplicationContext`.

**Comment by Comven** [comment]
@mercyblitz But I don't want to use XML to configure it because we use springboot， Is there any other way to do it？perhaps the newest dubbo-spring-boot-starter will support it?

**Comment by mercyblitz** [comment]
@Comven It will be add into endpoint on spring boot starter , please refer here : https://github.com/dubbo/dubbo-spring-boot-project/milestone/1
