### ISSUE TITLE
远程调用方法(空方法)响应时间要几十ms

### ISSUE THREAD

**Issue by YoKv** [alibaba/dubbo#1036]
![_20171213171833](https://user-images.githubusercontent.com/15179941/33931035-d2cb4998-e029-11e7-8ccb-c952a59e5a3c.png)
用demo测试了下要74ms,项目进行压力测试的时候时间非常长，版本是2.5.7
是什么问题

**Comment by oldratlee** [comment]
对问题尤其是性能 要给出可以别人重复的代码工程 @YoKv 比如把可以运行工程放一个github仓库中。

如果我不能复现再细节分析，涉及的环境可能的点太多（也可以是自己的环境问题）就只能给泛泛的提示，不能高效解决问题。

**Comment by YoKv** [comment]
项目中的问题解决了是一个filter比较耗时的原因，上面图片的demo是 [官方demo](https://github.com/alibaba/dubbo/tree/master/dubbo-demo) ，demo这么慢让我觉得可能是环境问题或者是dubbo的bug，没注意filter。所以demo为什么要几十毫秒！ @oldratlee

**Comment by chickenlj** [comment]
官网示例demo，第一次请求会涉及到初始化网络链接等，所以会比较耗时
