### ISSUE TITLE
ERROR com.alibaba.dubbo.qos.server.Server -  [DUBBO] qos-server can not bind localhost:22222, dubbo version: 2.5.8,

### ISSUE THREAD

**Issue by lovederh** [alibaba/dubbo#1037]
ERROR com.alibaba.dubbo.qos.server.Server -  [DUBBO] qos-server can not bind localhost:22222, dubbo version: 2.5.8,
我启动了一个服务，一个消费的服务，然后二个绑定的都是22222,怎么修改这个端口号呢？用的springmvc集成的

**Comment by chickenlj** [comment]
[This doc shows how to config](https://github.com/dubbo/dubbo-user-book/blob/master/references/qos.md)

**Comment by sunbufu** [comment]
try this
```
<dubbo:registry client="curator" protocol="${dubbo.registry.protocol}" address="${dubbo.registry.address}" username="${dubbo.registry.username}" password="${dubbo.registry.password}" register="true">
<dubbo:parameter key="qos.enable" value="false"/>
</dubbo:registry>
```
or
```
<dubbo:registry client="curator" protocol="${dubbo.registry.protocol}" address="${dubbo.registry.address}" username="${dubbo.registry.username}" password="${dubbo.registry.password}" register="true">
<dubbo:parameter key="qos.port" value="22224"/>
</dubbo:registry>
```

**Comment by liaomengge** [comment]
i use dubbo2.6.2, and xml user below:

<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
       xmlns:dubbo="http://dubbo.apache.org/schema/dubbo"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       http://www.springframework.org/schema/beans/spring-beans.xsd
       http://dubbo.apache.org/schema/dubbo
       http://dubbo.apache.org/schema/dubbo/dubbo.xsd">

<dubbo:application name="" organization="" owner="liaomengge" version="1.0">
       <dubbo:parameter key="qos.enable" value="false"/>
</dubbo:application>
