### ISSUE TITLE
 Duplicate application configs: <dubbo:application name="custsrv" id="custsrv" />

### ISSUE THREAD

**Issue by li362692680** [alibaba/dubbo#1038]
com.alibaba.dubbo.container.Main 方法启动jar包报 
Duplicate application configs: <dubbo:application name="custsrv" id="custsrv" /> and <dubbo:application name="custsrv" id="custsrv2" />
配置方式是在xml文件中 <dubbo:application name="custsrv" />
不加这行又报  No such application config! Please add <dubbo:application name="..." />
这个应该怎么配置啊？？？？

**Comment by chickenlj** [comment]
The error promotion is clear enough:
```xml
<dubbo:application name="custsrv" id="custsrv" /> and <dubbo:application name="custsrv" id="custsrv2" />
```
