### ISSUE TITLE
The problem of dubbo provider starts warmup

### ISSUE THREAD

**Issue by EndProcess** [alibaba/dubbo#1049]
dubbo内置的LoadBalance继承自AbstractLoadBalance，该类根据服务启动时间进行一次预热，以防止服务首次启动被大量请求压垮，然而实现的invoker获取的url是consumer端启动时间，因此无法对provider端进行预热保护
int weight = invoker.getUrl().getMethodParameter(invocation.getMethodName(), Constants.WEIGHT_KEY, Constants.DEFAULT_WEIGHT);
        if (weight > 0) {
            long timestamp = invoker.getUrl().getParameter(Constants.REMOTE_TIMESTAMP_KEY, 0L);
            if (timestamp > 0L) {
                int uptime = (int) (System.currentTimeMillis() - timestamp);
                int warmup = invoker.getUrl().getParameter(Constants.WARMUP_KEY, Constants.DEFAULT_WARMUP);
                if (uptime > 0 && uptime < warmup) {
                    weight = calculateWarmupWeight(uptime, warmup, weight);
                }
            }
        }

**Comment by chickenlj** [comment]
```java
long timestamp = invoker.getUrl().getParameter(Constants.REMOTE_TIMESTAMP_KEY, 0L);
```

I think this is the timestamp of the provider.

**Comment by EndProcess** [comment]
thanks
