### ISSUE TITLE
I got an exception when using token in dubbo 2.5.x: <dubbo:protocol name="dubbo" token="123456" />, support token or not？

### ISSUE THREAD

**Issue by luohuijun619** [alibaba/dubbo#1052]
![image](https://user-images.githubusercontent.com/10302568/34068693-c9d118d8-e27a-11e7-87eb-52682d2c60d7.png)

![image](https://user-images.githubusercontent.com/10302568/34068687-ada1b370-e27a-11e7-85b8-92eb80203f22.png)

**Comment by chickenlj** [comment]
Currently, `token` is only supported on `<dubbo:provider />` and `<dubbo:service/>`.

I will check whether it should be added to `<dubbo:protocol/>`.
