### ISSUE TITLE
Is there a way that i can open/close QOS in dubbo-2.5.8?

### ISSUE THREAD

**Issue by luohuijun619** [alibaba/dubbo#1053]
![image](https://user-images.githubusercontent.com/10302568/34068779-70c99fb0-e27c-11e7-8d89-543f52e13556.png)

**Comment by chickenlj** [comment]
It can not be closed at this version, but you can use `dubbo.qos.accept.foreign=false` to reject any connection. 
At first, we design this part as pluggable, when dubbo can be packaged separately, this part will automatically become optional.

**Comment by chickenlj** [comment]
In 2.5.9, you can use `dubbo.qos.enable=true/false` to open or close qos.
