### ISSUE TITLE
Can i use c++ client to invoke the dubbo service?

### ISSUE THREAD

**Issue by njusnail** [alibaba/dubbo#1057]

**Comment by chickenlj** [comment]
We don't have official support for C++ client. Currently, you can export a service with hessian/http protocol on server side, and then invoke this service using C++ client, but you cannot use the Service Discovery and LoadBalance feature provided by Dubbo.

**Comment by njusnail** [comment]
Can i export a service with thrift protocol on server side and then invoke this service using c++ client by Apache Thrift? Or in other words, is dubbo thrift protocal compatible with the Apache Thrift?

**Comment by chickenlj** [comment]
It is compatible with Apache Thrift. But i recommend use hessian instead of thrift. First, this part is in urgent need to upgrade; Secondly, this part don't have enough test experiences in production.

**Comment by chickenlj** [comment]
#1095
