### ISSUE TITLE
How to config multiple route rules to one service? 

### ISSUE THREAD

**Issue by pengyonglei** [alibaba/dubbo#1059]
如题. 同一个服务如何配置多个路由规则 ? 

如果我对一个服务设置两个路由规则, priority的级别不一样, 那么dubbo会不会先执行优先级高的, 再继续执行优先级低的规则呢 ? 用这种方式能不能达到我一个服务设置多个路由规则的功能 ?

**Comment by chickenlj** [comment]
We recommend use english. In theory, you can set as many route rules as you can, and i don't think the execute order of route rules will make any difference?

**Comment by pengyonglei** [comment]
I set two routing rules for the same service, but dubbo-admin just displays one routing rule. please see pictures
![image](https://user-images.githubusercontent.com/11027128/34369745-8bc47de6-eaf9-11e7-95f0-bdbccabfdb5d.png)
![image](https://user-images.githubusercontent.com/11027128/34369756-a74fc14c-eaf9-11e7-95ef-b9666a17ace5.png)

**Comment by chickenlj** [comment]
It seems to be a bug of dubbo-admin

**Comment by chickenlj** [comment]
dubbo/dubbo-ops#9

**Comment by kimmking** [comment]
sincerely, I guess:
If we build a bridge with dubbo and camel/spring-integration, then many patterns in EIP and connections to many framework can be reuse in dubbo applications.
