### ISSUE TITLE
dubbo telnet command status -l

### ISSUE THREAD

**Issue by goal578** [alibaba/dubbo#1060]
生产系统有个dubbo服务过几天就会僵死一次，看dump日志也没看出来什么。然后用 telnet 命令 看状态，有些参数不太清楚，比如附件的task是表示？请问是否有 status -l 各参数解释的文档？
![dubbo](https://user-images.githubusercontent.com/16495004/34149207-4c0a1b54-e4df-11e7-97d7-3035a5629749.png)

**Comment by chickenlj** [comment]
Sorry, there is no explanation for this command at this moment, you can check [source code](https://github.com/alibaba/dubbo/blob/master/dubbo-rpc/dubbo-rpc-default/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/status/ThreadPoolStatusChecker.java) for details

**Comment by suhlmsn** [comment]
这是处理的总任务数

我的问题是:status -l 没有返回结果
