### ISSUE TITLE
To meet the following requirement, should i customize loadbalance policy?

### ISSUE THREAD

**Issue by veio007** [alibaba/dubbo#1063]
希望可以将消息发送给指定的服务提供者，比如同一模块启了两个实例，应用名称分别为a1,a2，另外一个模块的服务希望可以有选择的给a1或者a2，我的想法是自定义负载均衡，然后从doSelect的invokers参数里面遍历拿providerUrl里面的application参数，但是好像providerUrl放在一个私有类RegistryDirectory.InvokerDelegete里面，所以拿不到，请问下有什么办法可以实现类似的功能吗 感谢
使用dubbo 2.5.8

**Comment by veio007** [comment]
我现在暂时的做法是把group设置为对应的应用名称，相当于每个实例对应一个分组，消费端指定对应的group进行调用，效果是可以达到，但是感觉姿势不对可能会有其他未发现问题

**Comment by chickenlj** [comment]
This can be achieved by add customized router rule, current route can support this.
And we plan to enhance the router functionality.
