### ISSUE TITLE
The application name and ip are not covered in consumer's URL of monitorService

### ISSUE THREAD

**Issue by yongxing510** [alibaba/dubbo#1064]
One registered URL of consumer may looks like 

> consumer:///com.alibaba.dubbo.monitor.MonitorService?category=consumers&check=false&dubbo=2.5.7&interface=com.alibaba.dubbo.monitor.MonitorService&pid=1&timestamp=1513609493290

, which missed the name and ip fields.

**Comment by chickenlj** [comment]
How do you configure MonitorService? Check if you missed the address in your configuration please.
