### ISSUE TITLE
dubbo peer-to-peer serialization error

### ISSUE THREAD

**Issue by 15993061515** [alibaba/dubbo#1068]
in dev enviroment,bypassing the registry,i use the peer-tp-peer to connect dubbo service by "-Ddubbo.resolve.file" arguments,but occured serialization error. i upload some pictures of this problem in website(https://segmentfault.com/q/1010000012478443). please give me guidence,thanks。

**Comment by chickenlj** [comment]
You may have got a deserialization error of request arguments on provider side. Have you checked the logs on provider?

**Comment by chickenlj** [comment]
I find that you use dubbox 2.8.4, do you use both dubbo and dubbox? dubbox has changed the core rpc protocol and it has compatibility problem with dubbo.
