### ISSUE TITLE
com.alibaba.dubbo.rpc.RpcException: Forbid consumer 169.254.226.207 access service com.base.service.AppService from registry localhost:2181 use dubbo version 2.5.3, Please check registry access list (whitelist/blacklist).

### ISSUE THREAD

**Issue by jkxqj** [alibaba/dubbo#1070]
本地运行生产者和消费者2个项目在同一个tomcat中，生产者无法正常启动，请问这是什么情况？

**Comment by QiJiYinQiao** [comment]
请看#317

**Comment by lxf-NewBanker** [comment]
@jkxqj 
https://github.com/apache/dubbo/issues/684    中，[david1228用户](https://github.com/david1228) 评论说：

> 我的本地环境中也遇到类似的问题，
报错信息：
Forbid consumer 10.58.95.10 access service com.xxx.mms.api.service.IAlbumService from registry 36.110.219.106:2181 use dubbo version 2.5.3, Please check registry access list (whitelist/blacklist).
当provider启动后，在zk中的providers节点下面能够看到注册信息，当消费端consumer启动后，zk中providers下注册信息丢失了，而consumers节点中有2份注册信息。
这个问题是因为IDEA中使用同一个Tomcat启动provider和consumer服务就会出现上述异常，使用两个tomcat分别启动provider和consumer就没问题，或者都用jetty插件方式启动也没问题。
