### ISSUE TITLE
dubbo Unauthorized access! a web app security scanner report!

### ISSUE THREAD

**Issue by lsh1611** [alibaba/dubbo#1073]
Hi, 
I met a situation here, we have a web system and dubbo installed. One of Security services company made a scan last week. there is a report:  
It's a vulnerability : dubbo Unauthorized access!
the test process proved that anyone can login the dubbo server via telnet dubboIP portNUM.
I did the same test, it's true...
I wonder it's really a vulnerablility?  How can I disable the telnet function in dubbo?

expect your reply!
regards,
Lloyd.

**Comment by chickenlj** [comment]
What's your dubbo version?
At 2.5.8, you can decide whether accept traffic coming from telnet port or not, click [here](http://dubbo.io/books/dubbo-user-book/references/qos.html) for more how to config.

We will remove the old telnet implementation in the future.

**Comment by chickenlj** [comment]
Add a switch like `telnet.open=true/false` to decide open telnet or not?
`dubbo.qos.accept.foreign.ip=true/false` can be changed at runtime?

**Comment by lsh1611** [comment]
got it. we'll have a try on it. Thanks!

**Comment by lsh1611** [comment]
Dear sir,
One of my colleague did some tests according your suggestion, but it seems not work:
 environment:
JDK update to 1.7, and dubbo update to 2.5.8
![1](https://user-images.githubusercontent.com/17892859/34554510-2feb88f0-f168-11e7-95bf-4ecf1412eeb5.png)

Following the manual of telnet part: http://dubbo.io/books/dubbo-user-book/references/qos.html ,
we modified the file dubbo.properties in dubbo-admin, set the dubbo.qos.port=**33333**  .
but in the log file, we found the port still is 22222(default).  set the dubbo.qos.accept.foreign.ip=**true**,
I also can telnet to dubbo port 2088X.

My current properties:
![2](https://user-images.githubusercontent.com/17892859/34554813-c14bc3f4-f169-11e7-83de-628b85a7595f.png)

We just want disable the access of telnet 2088x, and we do'nt know where is the key point.  would you please give us some particular advice for this issue?

regards,
Lloyd.

**Comment by lsh1611** [comment]
and further step:
add a switch in dubbo.properties:
![3](https://user-images.githubusercontent.com/17892859/34556118-0b9bcdea-f170-11e7-9749-214f811dc408.png)
and restart the dubbo, it's also telnet 2088x success...

**Comment by chickenlj** [comment]
It seems that `dubbo.properties` cannot be loaded in a web container environment for the previous implementation, it's a bug.
We have fixed this problem, it will be released with 2.5.9.
