### ISSUE TITLE
What's the relationship of Dubbo and Spring Cloud?

### ISSUE THREAD

**Issue by hanwangkun** [alibaba/dubbo#1078]
现在Dubbo相对于Spring Cloud作为微服务框架来说，缺少很多的组件，比如配置管理、链路跟踪、断路器，Dubbo现在有很大的用户集体，作为Dubbo的用户群体之一，我很希望Dubbo能够更完善，所以很关心Dubbo未来的走向，我想这也是很大一部分用户的想法

**Comment by lzf8888** [comment]
要不是因为公司原因，谁会想用dubbo构建呢，资源和支持少了很多

**Comment by chickenlj** [comment]
Simply put, dubbo will focus on RPC, Spring Cloud want to provide a complete solution for microservices architecture, we will try to adapt to Spring Cloud as a RPC solution. 

I recommend you watch [this video](http://www.itdks.com/eventlist/detail/1809), here i give a detailed description of this question.

**Comment by vihunk** [comment]
官方可以规划路线，一部分由官方团队实现，另一部分 看看是否可以建立dubbo社区，由社区爱好者进行扩充，朝多元化发展完善，变成社区版，官方版再根据实际情况看是否需要集成。
我相信很多人愿意加入到社区版里面。
