### ISSUE TITLE
2.5.7新版本ZkClientWrapper 超时设置能否改为可配置方式

### ISSUE THREAD

**Issue by Fcworld** [alibaba/dubbo#1082]
ZkclientZookeeperClient 类，client = new ZkClientWrapper(url.getBackupAddress(), 30000);
因为在网络环境较差的情况下，外加zk集群。连接时间有时会大于30s.

**Comment by chickenlj** [comment]
Firstly, in production, i think 30s is a pretty long time, if you can not build a connection to ZK server, there may have a potential problem.

Secondly, we do this to prevent unlimited waiting when ZK server can not be reached in a really long time. If you use `<dubbo:registry check="false"/>`, this mechanism will make sure your application use the cached data of registry and continue working, and when you finally build a connection to ZK server,  ZkclientWrapper will use this connection and keep sync to ZK server automatically.

**Comment by chickenlj** [comment]
And if you don't use `<dubbo:registry check="false"/>` and you can not connect to ZK server in 30s, your application will fail to start.
