### ISSUE TITLE
retries property in @Service don't take effect when i set `retries=0`

### ISSUE THREAD

**Issue by brainhunt** [alibaba/dubbo#1085]
2.5.8中，使用@Service注解，配置retries为0时，根据文档描述将不重试。实际测试中，设置为0后相当于retries=2的结果。设置-1时不重试。

**Comment by chickenlj** [comment]
I have tried and it works fine. Maybe there's something else wrong in your project, you can post your detailed configuration here.

**Comment by TwoWaterLee** [comment]
I've located this bug, I'll pull a request.

**Comment by chickenlj** [comment]
@brainhunt If you don't want retry, i recommend use `failfast` policy instead.
Besides, i think `retries=-1` means don't retry is also acceptable, since failover means retry, we can not figure out `retries=0` is a default value or user explicitly set 0.

**Comment by TwoWaterLee** [comment]
@chickenlj Yes, you are right. When use the `failover` policy, retries must be more than one.
Thanks a lot.
