### ISSUE TITLE
How can i extend the cache policy? I want to add a new cache policy using redis.

### ISSUE THREAD

**Issue by onlyyjc** [alibaba/dubbo#1088]
希望通过redis来实现缓存，自己定义了一个工厂类来实现AbstractCacheFactory，并在META-INF/dubbo/internal/com.alibaba.dubbo.cache.CacheFactory中增加了一条数据，redis=com.alibaba.dubbo.cache.support.redis.RedisCacheFactory。客户端配置cache="redis"，实际调试的时候，依旧调用的是默认的lru而非redis。请问，如何扩展dubbo缓存实现？我是还缺少什么配置吗？

**Comment by chickenlj** [comment]
I think you are extending in a right way. 
Please check your configuration again. And also, if you set `cache=redis` on consumer side, the provider will still use the default cache policy `lru`.
