### ISSUE TITLE
dubbo-admin显示接口警告，有人修复了吗

### ISSUE THREAD

**Issue by linpn** [alibaba/dubbo#109]
dubbo-admin显示接口警告，有人修复了吗

**Comment by liangfei0201** [comment]
dubbo-admin显示接口警告，一般是指有两个不同的dubbo.application.name注册了同一服务，主要是用于防止多应用间因依赖jar包，误暴露服务，并不会影响运行。

**Comment by Jimbean0615** [comment]
我看providers/index.vm里边，比较不同服务的application，只要不相同就会告警，是这样的吗

**Comment by lpn520** [comment]
这个是admin的显示bug

**Comment by wgzh159** [comment]
这个bug能解决么？

**Comment by 394938226** [comment]
参见我的博客，已修改
http://blog.csdn.net/u012063409/article/details/59110559

**Comment by yikee** [comment]
mark

**Comment by lovepoem** [comment]
https://github.com/alibaba/dubbo/issues/714

**Comment by lovepoem** [comment]
fixed  in https://github.com/alibaba/dubbo/pull/780
