### ISSUE TITLE
can dubbo provider a plan that supports the api gateway?

### ISSUE THREAD

**Issue by LINGLUOJUN** [alibaba/dubbo#1092]
In the case，when service instances becoming more  complex,the api gateway is in need nessarily

**Comment by chickenlj** [comment]
In the following several releases,  we will continue focus on improving the core dubbo features, so we may not have too much resources supporting `API Gateway` or some requirements like this.

But i do think this can be a part of our long-term plan.We will try to build a sound eco-system around dubbo core RPC, or at least we can try adapt to other eco-systems that provide this features.

**Comment by LINGLUOJUN** [comment]
expecting that the eco-system around dubbo can support  more features ,thx!!!!
