### ISSUE TITLE
Consumer report NPE, can not get the remote reference instance.

### ISSUE THREAD

**Issue by hczc** [alibaba/dubbo#1099]
我用Springboot整合dubbo，使用application.properties注解模式配置，如果提供者在消费者后面启动的话，消费端调用就会空指针

**Comment by big-mouth-cn** [comment]
我也正好遇到这个问题，而且不会重新注入，会一直空指针。

**Comment by hczc** [comment]
spring.dubbo.consumer.check=false 这个参数添加了但是没效果ReferenceConfig拿到的是空，
最终使用JVM参数解决的-Ddubbo.consumer.check=false，望dubbo团队回复下是什么原因导致的，谢谢！

**Comment by mercyblitz** [comment]
Please use `@EnableDubbo` and add `@PropertySource("your-config.properties"), and

`your-config.properties` content:

```properties
dubbo.consumer.check=false
```

or wait for`[dubbo-spring-boot-starter](https://github.com/dubbo/dubbo-spring-boot-project)` that will be release soon.

**Comment by coderzl** [comment]
应该是注解没有生效，在你的boot启动类上打上@DubboComponentScan(basePackages = "cn.xxxx")的注解

**Comment by chickenlj** [comment]
@hczc Please use dubbo 2.5.8, and follow @mercyblitz 's advice or refer this [example](https://github.com/alibaba/dubbo/tree/master/dubbo-test/dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/annotation)

**Comment by chickenlj** [comment]
If you still get this problem, please attach a demo project so we can reproduce it.
