### ISSUE TITLE
Compile error.

### ISSUE THREAD

**Issue by shang7053** [alibaba/dubbo#1101]
针对服务提供者，如果存在以get开头，但是无参的业务方法，dubbo在启动的时候会报编译错误。

**Comment by shang7053** [comment]
Caused by: java.lang.RuntimeException: [source error] getPropertyValue (Ljava/lang/Object;Ljava/lang/Stringemoticon_winkLjava/lang/Object; in com.alibaba.dubbo.common.bytecode.Wrapper198: inconsistent stack height -1

**Comment by beiwei30** [comment]
@shang7053 pls. attach a sample to reproduce the issue.

**Comment by shang7053** [comment]
@beiwei30 sorry,there no sample,because it's over,we hope other coder find answer ,so we report it

**Comment by chickenlj** [comment]
#627 This issue may be helpful.
Can you post your Interface definition?

**Comment by shang7053** [comment]
@chickenlj yes ,it's right! In jdk7,all green,in jdk8 red.But is there any other way to solve the problem besides switching javassist?

**Comment by revolyw** [comment]
这个问题是因为 dubbo 在使用 javassist 动态编译 provider 类的 getter 方法时，选择类属性识别以及返回值转换处理逻辑不够健壮导致的。
关键源码在 org.apache.dubbo.common.bytecode.Wrapper#makeWrapper 这里，识别 provider 目标方法使用的正则是 org.apache.dubbo.common.utils.ReflectUtils#GETTER_METHOD_DESC_PATTERN ，即 get 开头，入参为空的方法的后缀将识别为属性。 
针对这种属性动态编译 getter 方法时，待编译源码声明返回值为 Object （public Object getPropertyValue(Object o, String n)），javassist 编译器在翻译字节码阶段发现待编译源码和方法返回值不相符，字节码操作数栈对不齐，所以就报错了

因此理论上没有入参/返回值为空的 get 前缀开头的方法都有这个问题
