### ISSUE TITLE
Annotation don't work, why?

### ISSUE THREAD

**Issue by shang7053** [alibaba/dubbo#1102]
当使用的spring的注解，如apo或者Transactional的时候，注解的service不能被注册，需要手动在xml注册，或者在service里指定名字才能被注册

**Comment by shang7053** [comment]
调度中心预计什么时候上？

**Comment by mercyblitz** [comment]
Did you try  to use `@DubboComponentScan`?

**Comment by shang7053** [comment]
@mercyblitz no，I used xml ,like '<dubbo:annotation package="*" />'.

**Comment by chickenlj** [comment]
@shang7053  We recommend you upgrade dubbo version to 2.5.8 and use @EnableDubbo annotation.
[annotation example](https://github.com/alibaba/dubbo/tree/master/dubbo-test/dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/annotation)

**Comment by chickenlj** [comment]
@mercyblitz When our documentation for annotation is ready, we can  add a link here.

**Comment by shang7053** [comment]
@mercyblitz Thank you very much!In our new project,we uesd dubbo2.5.8 and @DubboComponentScan  ,So far, no problems have been found!
