### ISSUE TITLE
dubbo 抛不出自定义的异常

### ISSUE THREAD

**Issue by qiuxuhong** [alibaba/dubbo#111]
后端抛出 自己定义的异常（继承runtimeException），在前端通过spring 接受到的异常时 runtimeException，请问怎么解决

**Comment by taoeaten** [comment]
可以在api接口声明中显示的throws 你的自定义异常，可以看下dubbo的ExceptionFilter的逻辑

**Comment by liangfei0201** [comment]
这个是为了防止服务提供方抛出了消费方没有的异常，比如数据库异常类，导致消费方反序列化失败，使异常信息更奇怪，建议在业务接口上RuntimeException也声明在throws中。

**Comment by wangjingfei** [comment]
可以通过设置禁用掉默认的ExceptionFilter
`
<dubbo:provider filter="-exception"/>
`
这样的话所有的异常都会原样返回，当然前提是不会出现 @liangfei0201 提到的

> 服务提供方抛出了消费方没有的异常，比如数据库异常类，导致消费方反序列化失败
