### ISSUE TITLE
Is there a convenient way for configuring a large number of dubbo services?

### ISSUE THREAD

**Issue by everhopingandwaiting** [alibaba/dubbo#1115]
现在各种查文档， 看到的例子都是大家 就写一个  
` <dubbo:service interface="com.alibaba.dubbo.demo.DemoService" ref="demoService" />`

然后在消费端引用， 但是如果有很多的Service需要被引入，那是不是就得配置多个  `<dubbo:service xxx/>`
这样的写法？    看了下有个 `<dubbo:annotation ` 这是用来扫描所有的service包的吗？ 

反正我想的是有没有可以通过一句扫描就可以配置很多` <dubbo:service`的方法？

**Comment by everhopingandwaiting** [comment]
网上大片 大片的  csdn 的 复制粘贴的文章，看的实在是无语

**Comment by mercyblitz** [comment]
You could use `@DubboComponentScan` to register them

**Comment by everhopingandwaiting** [comment]
@mercyblitz 这个方法是不是只有 spring boot 项目可用啊？

**Comment by chickenlj** [comment]
@everhopingandwaiting Not just in spring-boot, it can be used in any spring projects.
Here's an [example](https://github.com/alibaba/dubbo/tree/master/dubbo-test/dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/annotation)

**Comment by everhopingandwaiting** [comment]
@chickenlj  thank u , 

dubbo provider 

```
@Component
@DubboComponentScan(basePackages = arrayOf("com.xxx.serviceImpl.impl")) 
class DubboConfig
```
that works ,  but  in my springMVC project， how to config the  dubbo customer? 
```
@Configuration
@EnableDubbo(scanBasePackages = arrayOf("com.**.service"), multipleConfig = true)
@ComponentScan(value = "com.siyue.zxxdzg.service")
 public open class DubboConsumerConfiguration {
}
```
```
aused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.xxx' available: expected at least 1 bean which qualif
```

**Comment by chickenlj** [comment]
It works the same on consumer side. Still doesn't work? maybe you should provide more code for someone to help.

**Comment by DocEcho** [comment]
可以自己实现一个 类， 专门 去扫 某个 package 下面的classes
然后 
ServiceBean serviceBean = new ServiceBean()
serviceBean.set...
serviceBean.set...
serviceBean.export()
