### ISSUE TITLE
Can't compile under JDK 1.9, caused by an invalid import.

### ISSUE THREAD

**Issue by markyao** [alibaba/dubbo#1116]
com.alibaba.dubbo.config.spring.context.annotation.provider里面
import com.sun.org.apache.regexp.internal.RE无效导入JDK9下部能编译通过
同时下面两个也是无效导入
import com.alibaba.dubbo.rpc.Protocol;
import org.springframework.context.annotation.ImportResource;

**Comment by mercyblitz** [comment]
It will be resolved in next release , please add fake class to compile

**Comment by mercyblitz** [comment]
You also could remove some test cases , sorry for careless :(

**Comment by chickenlj** [comment]
It's been fixed
