### ISSUE TITLE
help wanted: pull request for the changes from your folk branch which may benefit to all

### ISSUE THREAD

**Issue by xeostream** [alibaba/dubbo#1117]
我司在几年前就开始使用dubbo，并根据我司内部的需求修改了dubbo的代码，比如修复优雅停服、增加调用监控或其他我司定制非通用需求等等。

我们很欣喜阿里又开始维护dubbo并且投入大量人力，现在有一个问题：我司想合并官方dubbo的代码以使用更新后的新特性和性能提升（合并代码的方式不一定是最优解），但是有一些bug可能双方都修复了，这样就会导致代码合并的复杂度很大。

所以我有两个疑问想和大家讨论：

- 官方关于上述的场景是否有建议或最佳实践？

- dubbo代码分支是否可以参考spring-framework，每个release的大版本都有一个对应的稳定分支，不然无法确定master分支是否有非稳定代码提交？

**Comment by stoneapple** [comment]
同关心

**Comment by beiwei30** [comment]
@xeostream pls. submit pull request if you think the enhancement can benefit to all, you can talk to me on gitter. 

Thanks,
-Ian.

**Comment by xeostream** [comment]
@beiwei30 ok,i see.I will submit pull request after my boss approve this operation,thank you.
