### ISSUE TITLE
啥时候 restful 支持能进入master 分支啊， 急需这个功能

### ISSUE THREAD

**Issue by bamboolsu** [alibaba/dubbo#1119]
dubbox也不怎么更新了，  但其中的restful相关的支持， 确实好用， 

既然咱们dubbo重新启动了， 尽快引入 dubbox里面的一些主要功能吧， 尤其是RESTFUL 功能。

谢谢

**Comment by boylong12** [comment]
[PR#1001](https://github.com/alibaba/dubbo/pull/1001)

**Comment by beiwei30** [comment]
don't worry, will release soon

**Comment by chickenlj** [comment]
It has been released in [2.6.0](https://github.com/alibaba/dubbo/releases/tag/untagged-032f6654cf6ddf811881). 
Don't hesitate to contact us whenever you have a problem using dubbo, thanks.
