### ISSUE TITLE
ConsistentHashLoadBalance is unavaliable when using generic, because it always hit the same hash cycle

### ISSUE THREAD

**Issue by kirayunfei** [alibaba/dubbo#1123]
protected <T> Invoker<T> doSelect(List<Invoker<T>> invokers, URL url, Invocation invocation) {
        String key = invokers.get(0).getUrl().getServiceKey() + "." + invocation.getMethodName();
        ......
    }

由于泛化调用时invocation.getMethodName()值始终为"$invoke"，不会根据泛化调用真实信息构建hash环。修复代码可以尝试提交吗？

**Comment by mercyblitz** [comment]
Please pull request

**Comment by kirayunfei** [comment]
给出更详细的问题如下，帮助代码revice者快速定位问题。
1. 构建hash环的缓存使用interface+method作为key，泛化调用通过getMethodName()获得方法名始终为"$invoke"，相当于混用了hash环。
2. identityHashCode通过invoker的hashcode方法直接得到。但是invoker对象计算时会将url内容计算进去，url包含调用时间戳，每次都变，hash环每次都会失效重建
3.虚拟节点hash环持有invoker对象引用，个人认为loadbalance作为一个策略tool，尽量不需持有对整个工作流具有重要意义的invoker
已经提交了pull request，#1144

**Comment by chickenlj** [comment]
I leaved some message in the PR #1144, please check.
