### ISSUE TITLE
How can i add Filters, and Filters can apply to invoke chain without any extra configuration.

### ISSUE THREAD

**Issue by rangwea** [alibaba/dubbo#1127]
比如我将通用的Filter抽取成了common-dubbo-filter.jar的jar包，只要dubbo项目引用这个jar就自动注册jar中的Filter.（现在只能在项目的META-INF中添加filter配置文件）

要实现上面的功能我需要怎样的配置呢？

**Comment by chickenlj** [comment]
You can use @Activate annotation on your Filter, it will guarantee your Filters be invoked automatically  when condition matches.
See [@Activate for details](http://dubbo.io/books/dubbo-dev-book/SPI.html)

**Comment by rangwea** [comment]
@chickenlj Think, It can solve my problem.
