### ISSUE TITLE
What if an application export a service and refer this service at the same time?

### ISSUE THREAD

**Issue by wing-only** [alibaba/dubbo#1129]
写了一个接口，服务提供方进行实现，同时也引用该接口，然后把这个服务部署多套，测试发现不会进行分布式调用，只会当做本地方法调用。

**Comment by jiangll007** [comment]
这样处理没问题吧？集群部署就是为了避免单机崩溃的。一个接口它既是提供者又是消费者。那么机器挂了之后不仅仅提供者挂了，消费者也挂了。消费者也没有可能去找别的机器调用了。 而且不会进行分布式调用，还减小了网络传输的带宽消耗

**Comment by chickenlj** [comment]
@wing-only  If a service is exported and referenced in the same application, dubbo will always refer the inner service instance by default (`InjvmProtocol`), avoiding network costs. If you want to change this default behavior, set `scope=remote`, click [here](http://dubbo.io/books/dubbo-user-book/demos/local-call.html) for more details.

**Comment by wing-only** [comment]
ok,thanks
