### ISSUE TITLE
Dubbo取代F5做负载均衡的可行性

### ISSUE THREAD

**Issue by junny9985** [alibaba/dubbo#113]
目前公司，前端2台服务器，F5做均衡，后端2台服务器，前端和后端之间也有F5做均衡，目前公司要引入dubbo，dubbo自带负载均衡，取代F5的可行性是多大？
如果可行性不大，dubbo如果集成到后端F5的架构中去，
请教，谢谢！

**Comment by junny9985** [comment]
![1](https://cloud.githubusercontent.com/assets/11238955/6933590/f622929e-d85b-11e4-8236-1d9a522e6aed.jpg)

**Comment by dolt131943** [comment]
前端和后端之间的这台F5可以取消了，用来应对外部访问的F5还是得留着。用F5的真是土豪。

**Comment by teaey** [comment]
dubbo主要用于企业内部的服务化。就是说，内部系统（前端-后端）可以采用dubbo来服务化，同时去除F5依赖。

**Comment by liangfei0201** [comment]
如果dolt131943，Dubbo是可以取代前端和后端之间的F5，将内部硬负载改为软负载，阿里内部就是这么做的。

**Comment by junny9985** [comment]
@liangfei0201 ,@teaey,@dolt131943  了解了，多谢！！！
