### ISSUE TITLE
Direct invoke to a specific provider: peer-to-peer invocation.

### ISSUE THREAD

**Issue by qqcbqqkcel** [alibaba/dubbo#1135]
用了直连提供者通过文件映射这种方式，发现一个问题。
因为我的接口提供端的超时时间是通过<dubbo:provider  timeout="${dubbo.timeout}" />这种方式统一设置的。
直连的时候是不会生效的，目前解决方法是在服务端单独设置超时，这样的化统一的方式就不起作用了。
希望可以在直连的文件映射中单独配置
如：
com.alibaba.xxx.XxxService=dubbo://localhost:20890?timeout=10000

**Comment by chickenlj** [comment]
Firstly, we recommend using english.

As for your question, we still don't support using peer-to-peer invocation that way. And also, it's a feature designed for test only, we do not recommend using this feature in production.
