### ISSUE TITLE
Can `dubbo.application.name` use `${spring.application.name}`  placeholder as a default value?

### ISSUE THREAD

**Issue by cwt9562** [alibaba/dubbo#1137]
我使用spring-boot, 我希望可以只在一个地方配置我的应用名称, 故我使用了${}来配置, 结果报错了
部分配置文件如下
application.yml
```
spring:
  application:
    name: dubbo-demo

dubbo:
  application:
    name: ${spring.application.name}
#    name: dubbo-demo-provider
```

部分报错信息如下
```
2017-12-28 16:33:09.470 ERROR 17156 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: ApplicationConfig.application == null
    at com.alibaba.dubbo.config.AbstractConfig.appendParameters(AbstractConfig.java:245) ~[dubbo-2.5.8.jar:2.5.8]
```

---
我想说, 可否允许支持使用变量的模式? 
或者干脆没配置dubbo.application.name时, 使用spring.application.name作为默认值

**Comment by mercyblitz** [comment]
You can use `@EnableDubboConfigBinding(prefix = "${spring.application.name}", type = ApplicationConfig.class)` if your dubbo's version >= `2.5.8`

**Comment by mercyblitz** [comment]
Or use `@EnableDubbo`

**Comment by chickenlj** [comment]
Are you using dubbo-spring-boot-starter? Which version? 
The official boot-starter is still developing by @mercyblitz, it will be released soon.

**Comment by chickenlj** [comment]
>You can use @EnableDubboConfigBinding(prefix = "${spring.application.name}", type = ApplicationConfig.class) if your dubbo's version >= 2.5.8

@mercyblitz  If we use `@EnableDubboConfigBinding(prefix = "${spring.application.name}", type = ApplicationConfig.class)`, we still have to config explicitly in .properties file with the following format: `${spring.application.name}.name`? 
 For example, if `${spring.application.name}` is `dubbo-demo`,  we still have to config `dubbo-demo.name=dubbo-demo-provider`.

**Comment by cwt9562** [comment]
no, i don't use dubbo-spring-boot-starter
