### ISSUE TITLE
The xsd schema of Spring XML can not be visited.

### ISSUE THREAD

**Issue by bossty** [alibaba/dubbo#1143]
如下
http://code.alibabatech.com/schema/dubbo/dubbo.xsd
xml的schema定义文件无法访问，故而也无法引用，导致项目validate不通过

不知只是我遇到了这个问题还是各位都有这个问题

**Comment by chickenlj** [comment]
First, we recommend using english in community.

As for your question, `http://code.alibabatech.com/schema/dubbo/dubbo.xsd` is a local mapping to [dubbo.xsd](https://github.com/alibaba/dubbo/blob/master/dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd)
