### ISSUE TITLE
求助：移除dubbo的RpcException

### ISSUE THREAD

**Issue by Dreamroute** [alibaba/dubbo#1146]
由于我们应用消费端会自行处理各种异常，不需要返回dubbo内置的RpcException，而是将异常原样返回给客户端，请问怎么操作？

**Comment by Dreamroute** [comment]
看了下源码，Filter的invoke方法抛出运行时异常RpcException，所以感觉我这种想法基本上没戏了

**Comment by Dreamroute** [comment]
已解决，找了个折中的办法来解决

**Comment by chickenlj** [comment]
Dubbo will re-throw the original business exception thrown on provider side. But if consumer encountered some problem when calling remote peer, such as timeout or no provider, it will throw RpcException.
