### ISSUE TITLE
RpcInvocationHelper NP

### ISSUE THREAD

**Issue by lulu200861626** [alibaba/dubbo#1147]
![image](https://user-images.githubusercontent.com/5058705/34465115-2620abce-eeda-11e7-8bbd-6fdca3063bbb.png)

2.5.3版本，这个NP异常出现得还挺频繁的，这是一个什么问题

**Comment by chickenlj** [comment]
How come there is a RpcInvocationHelper? It is definitely not a class provided by dubbo, i think you are using a extended dubbo version.
