### ISSUE TITLE
getLogHost returning 127.0.0.1 not the correct ip address

### ISSUE THREAD

**Issue by stoneapple** [alibaba/dubbo#1150]
When Dubbo system is running ,the logs is like : 
30 15:45:47,446 INFO [com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry] -  [DUBBO] Subscribe: provider://10.20.5.106:20880/com.xxx.dubbotest.provider.DemoService?anyhost=true&application=xixi_provider&category=configurators&check=false&dubbo=2.5.2&interface=com.unj.dubbotest.provider.DemoService&methods=sayHello,getUsers&pid=12192&side=provider×tamp=1419925546891, dubbo version: 2.5.2, current host: 127.0.0.1

getLogHost returning 127.0.0.1 not the correct ip address，I think it should be a bug, and can be fixed easily by change the way getting localhost IP

**Comment by chickenlj** [comment]
It's been fixed.

**Comment by EdwardLee03** [comment]
Suggest to merge 'getLocalHost()' and 'getLogHost()', unnecessary to maintain two the same implementation methods.
