### ISSUE TITLE
Dubbo registered the wrong interface because of spring AOP and dubbo annotation conflict: dubbo://192.168.55.41:21882/org.springframework.aop.SpringProxy?

### ISSUE THREAD

**Issue by LesterDong** [alibaba/dubbo#1153]
我用spring aop写了个统一异常处理类，然后启动的时候发现dubbo注解方式的服务注册名变成了 org.springframework.aop.SpringProxy  ，请看日志：com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry] [DUBBO] Register: dubbo://192.168.55.41:21882/org.springframework.aop.SpringProxy?anyhost=true&application=gpay-bcp&cluster=failover&delay=-1&dubbo=2.5.8&generic=false&interface=org.springframework.aop.SpringProxy&loadbalance=random&logger=slf4j&methods=*&pid=6176&revision=4.3.0.RELEASE&side=provider&threads=100&timeout=60000&timestamp=1514901935548&version=2.0.0, dubbo version: 2.5.8, current host: 127.0.0.1， 我用的最新的2.5.8版本，我看之前有相关问题的回答说这个问题在最新版本已经修复，这个怎么说呢？我用的是spring 4.x版本

**Comment by chickenlj** [comment]
Do not use the `deprecated AnnotationBean` in your project.
Use the new annotation implementation instead, currently, you can refer [here](https://github.com/mercyblitz/blogs/blob/master/java/dubbo/Dubbo-New-Programming-Model.md
) and [the docs](http://dubbo.io/books/dubbo-user-book/configuration/annotation.html).
