### ISSUE TITLE
Black list exception is replaced with no provider exception

### ISSUE THREAD

**Issue by zhudongdong** [alibaba/dubbo#1154]
I know dubbo has replace the exception message 'black list...' with 'no provider ...' since some version，but when i set route for consumer to add it into some blacklist , the exception message throwed by the consumer client is not 'black list...' but 'no provider...'. Although it is not a big deal , but i still wonder is there any possiablity to  make the message more reasonable？

**Comment by zhudongdong** [comment]
excuse me，there is another little problem. When there is only one provider ,i can not offline it from admin,
and i traced the code ,i got this (RegistryDirectory.java line 253 from the latest version)
`
            
            // state change
            // If the calculation is wrong, it is not processed.
            if (newUrlInvokerMap == null || newUrlInvokerMap.size() == 0) {
                logger.error(new IllegalStateException("urls to invokers error .invokerUrls.size :" + invokerUrls.size() + ", invoker.size :0. urls :" + invokerUrls.toString()));
                return;
            }
`
if i change the code as below (get rid of 'return'):
`
if (newUrlInvokerMap == null || newUrlInvokerMap.size() == 0) {
                logger.error(new IllegalStateException("urls to invokers error .invokerUrls.size :" + invokerUrls.size() + ", invoker.size :0. urls :" + invokerUrls.toString()));
            }
`
it will work.
Could I do this?

**Comment by chickenlj** [comment]
>excuse me，there is another little problem. When there is only one provider ,i can not offline it from admin,
and i traced the code ,i got this (RegistryDirectory.java line 253 from the latest version)

That is an protection mechanism of dubbo to prevent unexpected `No Providers` from happening. Why do you have to offline the only provider, won't it cause `No Providers` exception on consumer side?

**Comment by chickenlj** [comment]
>I know dubbo has replace the exception message 'black list...' with 'no provider ...' since some version

Maybe we can reorganize the exception information so that it reflects both`blacklist` and `no provider`.
