### ISSUE TITLE
should not have two netty dependencies

### ISSUE THREAD

**Issue by beiwei30** [alibaba/dubbo#1156]
```xml
            <dependency>
                <groupId>org.jboss.netty</groupId>
                <artifactId>netty</artifactId>
                <version>${netty_version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-all</artifactId>
                <version>${netty4_version}</version>
            </dependency>
```

**Comment by chickenlj** [comment]
Currently, we support both netty3 (`dubbo-remoting-netty`) and netty4 (`dubbo-remoting-netty4`), so we have to depend on both.
By default, only netty3 works as a transitive dependency of `dubbo.jar`, netty4 is an optional dependency chosen by user.

**Comment by zhaojigang** [comment]
hi, when will you make a performance test report on netty3 and netty4? @beiwei30 @chickenlj
