### ISSUE TITLE
Memory leak risk in ConsistentHashLoadBalance?

### ISSUE THREAD

**Issue by LNAmp** [alibaba/dubbo#1157]
ConsistentHashLoadBalance holds a map of ConsistentHashSelector, the key is the  identityHashCode of all valid invokers. So when invoker list changed or invoker's filed(url, attachment) changed, a new ConsistentHashSelector will be construct.

**Comment by kirayunfei** [comment]
Hello， this problem I have figure out in #1123 ， and try to pull request to fix it #1144 。
Please stay focused~ 
And if there are any suggestions, please send them to me. Thank you~

**Comment by LNAmp** [comment]
我看过这个issue，情况貌似还不一样，我先看看你的issue及pr

**Comment by kirayunfei** [comment]
嗯，pr里包含了一个fix，是关于由于每次调用根据invoker构建hash环使用的identityHashCode都不同，导致每次调用hash环都会被重建的问题

**Comment by chickenlj** [comment]
I think we can discuss the problems of ConsistentHashLoadbalance in #1144, this PR also mentioned the memory leak problem.
