### ISSUE TITLE
typo: in word 'SUFFIXS'. in class com.alibaba.dubbo.config.AbstractConfig

### ISSUE THREAD

**Issue by akun2014** [alibaba/dubbo#1159]
in class com.alibaba.dubbo.config.AbstractConfig。The plural of 'SUFFIXS' should be 'SUFFIXES'。

**Comment by M-AJ** [comment]
Submitted PR [here](https://github.com/alibaba/dubbo/pull/1170).

**Comment by chickenlj** [comment]
Fixed with PR  #1170
