### ISSUE TITLE
dubbo2.5.3 注解配置无效

### ISSUE THREAD

**Issue by xuzunyuan** [alibaba/dubbo#116]
参照了dubbo用户指南，按照上面说的做了注解配置。
本想采用自动扫描，减少开发的工作量，但是无效。

有配置注解成功的吗？讲解一下吧

**Comment by caige2015** [comment]
我们也不成功，只能采用xml的形式了

**Comment by xiegengcai** [comment]
没成功，先xml配置吧，没时间研究

**Comment by xiegengcai** [comment]
没成功，先xml配置吧，没时间研究

**Comment by xiegengcai** [comment]
没成功，先xml配置吧，没时间研究

**Comment by zhouyuzhy** [comment]
成功是能成功，可以看下扫描的代码 有个BUG的，只能在spring的当前类中使用，spring bean父类中那个地方存在BUG。

如果你是没声明为spring的service或者引用reference不在spring的service中也是无效的。

**Comment by vistier** [comment]
我使用的4的版本没什么问题

**Comment by carlosli** [comment]
如果你是没声明为spring的service或者引用reference不在spring的service中也是无效的。
---------------------------------------------------------
果然是这个原因，感谢

**Comment by Benjamin2086** [comment]
@carlosli 请问如何把Reference接口声明为spring bean
