### ISSUE TITLE
DubboConfigConfigurationSelector should not set a hard-coded order value: HIGHEST_PRECEDENCE

### ISSUE THREAD

**Issue by guo168** [alibaba/dubbo#1160]
DubboConfigConfigurationSelector的order不应该写死HIGHEST_PRECEDENCE，
应该通过注解属性方式传值。

**Comment by chickenlj** [comment]
@mercyblitz need your help here.

**Comment by chickenlj** [comment]
@guo168  Why do we have to customize the order of DubboConfigConfigurationSelector?

**Comment by guo168** [comment]
因为这个扫描级别最高，且不可更改，失去了程序集成或者拓展的灵活性，比如我们这边用了百度的disconf 统一配置，也是居于spring集成的，它的扫描级别也要最高，因为配置文件下载且注入到容器里相关位置肯定是要最早，这种情形就出现问题了。比如我dubbo相关properties配置也是通过disconf管理，这是就出现了dubbo先执行，但是找不到配置文件。

**Comment by guo168** [comment]
而且就算没出现问题，单单从框架设计考虑，默认最高且可配置，不是更好吗，why not？框架设计默认了一些常规性需要，也需要提供灵活性以支持更多复杂的集成环境，和未知的需要，毕竟这个改动成本极低。本身就是通过@EnableDubbo @EnableDubboConfig注解为入口 只要在这个入口提供属性就可以

**Comment by mercyblitz** [comment]
It's a design purpose for `DubboConfigConfigurationSelector` ,  consider this scenario , it's required  to initialize all of Dubbo Configuration Beans needs  as soon as possible , those Dubbo configuration beans would be dependencies of `@Reference` and `@Servnce`. As generally , configuration or external configuration is ready first , If you know Spring Boot or Spring Framework , many cases follow this rule , e.g:

In Spring Boot  :

```java
```

**Comment by mercyblitz** [comment]
@guo168 what's more, it's unnecessary to extend DubboConfigConfigurationSelector , there are two reasons :

1. DubboConfigConfigurationSelector is imported by Application's `@EnableDubboConfiguration` or `@EnableDubbo` , there  is no chance to change **order**  , limited by Spring Framework . If application requires , it can use `@EnableDubboConfigBinding`.

2. DubboConfigConfigurationSelector is an internal class , the application should not extend it.

**Comment by guo168** [comment]
@mercyblitz 感谢您的回答，我知道您说的这些，您说的是对的，不过我想说的是，因为DubboConfigBindingRegistrar在处理的各个dubbo基础bean（比如ApplicationConfig.class） 的BeanDefinition注册的阶段,就已经需要通过environment加载properties，且这时候还在如果我是用properteis文件配置方式，那么这个时候必须保证我本地有这些properties配置文件，问题是假设系统集成的统一配置管理平台，比如我这边集成了百度的disconf(也是基于spring 处理)，那么他需要去配置文件中心下载properties文件再加载到environment，但该下载动作处理的时刻比前面讲的那个dubbo 基础bean BeanDefinition 注册阶段还晚，显然是有问题。当然我这边是有办法解决，但该问题应该会有很多人碰到。

**Comment by mercyblitz** [comment]
@guo168 Thank you for response, focus on your worry, even though `DubboConfigConfigurationSelector`'s order can be changed , the problem that you mentioned still exists. It may be implementation of disconf does not obey the rule , thus `DubboConfigConfigurationSelector` can't be aware of disconf's ready.

**Comment by guo168** [comment]
@mercyblitz 嗯，是的
