### ISSUE TITLE
Unify the behavior of setAttachments method in RpcInvocation and RpcResult

### ISSUE THREAD

**Issue by haodut** [alibaba/dubbo#1166]
RpcInvocation 中的 setAttachments 是设置新的 Attachments，是替换，RpcInvocation 中的 setAttachments 是添加新的 Attachments 到原 Attachments中，是追加，这两处应该保持一致。

**Comment by beiwei30** [comment]
pls. check 9c2e2fa6d3c4e5893deb930bffa469993c2161a6
