### ISSUE TITLE
changeLevel is not defined

### ISSUE THREAD

**Issue by linfeng2gh** [alibaba/dubbo#1169]
in: dubbo-admin/src/main/webapp/WEB-INF/templates/sysinfo/screen/logs/index.vm
line 3: <select id="logLevel" name="logLevel" onchange="changeLevel(this.value);">
changeLevel is not defined

**Comment by chickenlj** [comment]
You catch that error on your browser when using `system.management/logs` function of dubbo-admin?

**Comment by chickenlj** [comment]
That is a functional defect, but i am afraid that won't get fixed in the following releases.
