### ISSUE TITLE
AnnotationBean has been marked as Deprecated since 2.5.7?

### ISSUE THREAD

**Issue by BingjieLi** [alibaba/dubbo#1171]
最近更新了最新版的Dubbo2.5.8，然后发现从2.5.7版本开始com.alibaba.dubbo.config.spring.AnnotationBean被标记为Deprecated了，代码和文档中都没有找到任何原因说明，也没有说明是否是被其他类替代了。求解释~

**Comment by chickenlj** [comment]
We have refactored the annotation part and marked the `AnnotationBean` as deprecated in 2.5.7.
You can refer [the documentation](https://github.com/alibaba/dubbo/issues/1171) or [sample](https://github.com/alibaba/dubbo/tree/master/dubbo-test/dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/annotation) for more details.

**Comment by chickenlj** [comment]
More detailed introduction to Annotation and Spring-Boot-Starter is still in progress by @mercyblitz .

**Comment by mercyblitz** [comment]
`AnnotationBean` is an internal-use class , more details please refer here :
https://github.com/mercyblitz/blogs/blob/master/java/dubbo/Dubbo-Annotation-Driven.md
