### ISSUE TITLE
The demo consumer can not be started when the registry is N/A or multicast.

### ISSUE THREAD

**Issue by finddog** [alibaba/dubbo#1173]
demo的consumer无法启动， 需要在consumer中手动加入url才可以运行，我使用的dubbo版本为2.5.8.
http://dubbo.io/books/dubbo-user-book/quick-start.html#
应该改为如下方式：
    <dubbo:reference id="order" interface="com.mydubbo.order.IOrderService"
    url="dubbo://169.254.222.170:20880/com.mydubbo.order.IOrderService"/>

**Comment by chickenlj** [comment]
When using N/A, you have to specify the provider address.
