### ISSUE TITLE
I failed to use `org.apache.curator`. dubbo only support using of `com.netflix.curator` currently?

### ISSUE THREAD

**Issue by finddog** [alibaba/dubbo#1174]
<dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
            <version>4.0.0</version>
        </dependency>
在 consumber中，采用 org前缀的curator ，如下：
<dubbo:registry protocol="zookeeper" address="192.168.20.21:2181,192.168.20.22:2181,192.168.20.23:2181" client="curator"/>
会报错，“java.lang.ClassNotFoundException: com.netflix.curator.framework.api.CuratorWatcher”
curator最新更新的维护都在 org.apache.curator 下面。

**Comment by chickenlj** [comment]
Is your dubbo version 2.5.3 or lower?
On the contrary, dubbo only support `org.apache.curator` after 2.5.4+.

**Comment by Tanky-Zhang** [comment]
> Is your dubbo version 2.5.3 or lower?
> On the contrary, dubbo only support `org.apache.curator` after 2.5.4+.

Why dubbo only support `org.apache.curator` after 2.5.4+？I see the document said：
![image](https://user-images.githubusercontent.com/48041180/128819092-d88e02d4-1910-4330-938e-743bd4c4ae7d.png)
it said that  support `org.apache.curator` after 2.3.0+，could you tell me，thank you very much。
