### ISSUE TITLE
Restart zookeeper, some service can't be registered.

### ISSUE THREAD

**Issue by qxk1989** [alibaba/dubbo#1175]
zookeeper所在机器硬件故障，集群重启，但是发现有部分服务没有重新注册，请问有遇到过吗

**Comment by liyang8** [comment]
我好像遇到过，不过因为dubbo提供者报错（并不是业务代码报错）了~ 我不确定是不是我重启zookeeper导致的。同一个注册中心的其他提供者倒是正常。 Dubbo版本：2.5.3

**Comment by zhaolizhi** [comment]
请问怎么解决的呢？
