### ISSUE TITLE
The online/offline provided in 2.5.8 doesn't work properly with redis registry.

### ISSUE THREAD

**Issue by jactorew** [alibaba/dubbo#1181]
搭建的是基于redis的dubbo2.5.8
服务启动设置默认不注册服务，待应用启动后执行脚本telnet localhost 22222进入dubbo控制台，然后online注册服务；到这里都很正常，但需要更新应用时先offline下线服务时出了问题，不管怎么执行命令，隔一会儿（1秒左右）服务又重新注册了，试过了各种办法都无效。

理想效果：默认启动不注册服务，执行online后注册服务，执行offline后下线服务，kill掉应用后重新启动应用（记住kill前的状态，如果是online则直接注册服务，如果是offline则不注册服务），执行online，恢复服务。
  
![image](https://user-images.githubusercontent.com/3916627/34672976-9325b21e-f4bb-11e7-8b64-82153ff0d2ea.png)

debug到这里发现registered注册和注销的实例化对象不是同一个，online添加的对象（内存中）offline却无法移除，却单单把redis上的数据删掉了；而com.alibaba.dubbo.registry.redis.RedisRegistry#deferExpired这个定时任务却把内存中没被移除的对象有重新写入了redis，导致offline下线无效。

![image](https://user-images.githubusercontent.com/3916627/34673335-da3a3c50-f4bc-11e7-957d-3714b9a94ecb.png)
private final Set<URL> registered = new ConcurrentHashSet<URL>();应该设置为静态变量，保证该类的所有实例对象共享一个registered

**Comment by qinliujie** [comment]
#1190

**Comment by qinliujie** [comment]
it is not recommand to use redis registry in production

**Comment by jactorew** [comment]
@qinliujie 这也是没办法，公司只有现成的redis，不想再多维护一个zookeeper集群了。

**Comment by qinliujie** [comment]
I have fixed it, you can look at #1190
