### ISSUE TITLE
Discussion: release plan and version management.

### ISSUE THREAD

**Issue by chickenlj** [alibaba/dubbo#1193]

**Comment by zhaojigang** [comment]
How will dubbo3.x implement reactive? RxJava2 or Reactor or Do one by yourself?

**Comment by chickenlj** [comment]
We plan to integrate with existing RX frameworks now. 
Actually, instead of reactive stream, i find most of the requirements in RPC are only asynchronous. Just like the difference of CompletableFuture and Reactive Stream: CompletableFuture fits most of the scenarios in RPC, it has only one emit, also can combine requests asynchronously, may lack of some convenient operators, like flatMap,  filter or others, but for a one emit scenario c
