### ISSUE TITLE
The DTO generated by thrift don't support telnet invoke.

### ISSUE THREAD

**Issue by fmyblack** [alibaba/dubbo#1194]
thrift生成java类时，除了原有的属性外，还会生成setXXisSet, getXXisSet方法，这在`com.alibaba.dubbo.common.bytecode.Wrapper`类包装时，会在propertyNames中加入XXisSet

    if( ( matcher = ReflectUtils.GETTER_METHOD_DESC_PATTERN.matcher(md) ).matches() ){
	    String pn = propertyName(matcher.group(1));
	    c2.append(" if( $2.equals(\"").append(pn).append("\") ){ return ($w)w.").append(method.getName()).append("(); }");
	    pts.put(pn, method.getReturnType());
	}
  
然而在getPropertyValue方法生成中没有把这个加入。
这导致了两部分不对称而报出`Not found property XXisSet field`错误

**Comment by chickenlj** [comment]
@lovepoem is working on supporting thrift, can you give some suggestion?
