### ISSUE TITLE
Why NettyClient does not use the configured connection timeout in netty4.

### ISSUE THREAD

**Issue by CaiHongLa** [alibaba/dubbo#1197]
boolean ret = future.awaitUninterruptibly(3000, TimeUnit.MILLISECONDS);

为什么不使用boolean ret = future.awaitUninterruptibly(getConnectTimeout(), TimeUnit.MILLISECONDS);

**Comment by chickenlj** [comment]
Try to use `<dubbo:parameter key="connect.timeout" value="xxx" />`.
