### ISSUE TITLE
How long will it take you guys to support the spring 3.x or even 4.x？

### ISSUE THREAD

**Issue by yincu** [alibaba/dubbo#1198]
How long will it take you guys to support the spring 3.x or even 4.x？
However, thank you for continuing to support the project.

The newest version support the REST ?  Maybe you can reference the dubbo eXtension project  from Dangdang  team?

**Comment by lovepoem** [comment]
Dubbox's core features #1001 was merged since https://github.com/alibaba/dubbo/releases/tag/dubbo-2.6.0

**Comment by caijunjun** [comment]
现在dubbo支持了，我用的就是4.x的，楼主没有仔细试过？
最新的2.6.0 https://github.com/alibaba/dubbo/releases/tag/dubbo-2.6.0
你可以看下

**Comment by mercyblitz** [comment]
Spring 3.2.18.RELEASE reaches end-of-life , thus I suggest you use Spring 4.x

**Comment by yincu** [comment]
Thank you all guys .I   referenced  http://dubbo.io/books/dubbo-user-book/dependencies.html   before. And  It says the dependencies  aren't   the updated  spring version  so that I came here to ask.
