### ISSUE TITLE
Can dubbo-admin monitor more than one registries?

### ISSUE THREAD

**Issue by a13707331174** [alibaba/dubbo#1200]
想只部署一个dubbo-admin,监控不同的注册中心,dubbo-admin现在支持这种实现吗? 或者韩都的dubbo-monitor,支持吗? 是不是只能在定义多个registryService消费者才行

**Comment by stoneapple** [comment]
这个实现应该是没问题的，稍微修改下内部存储结果，map再扩展一层，但是可能会存在内存问题的，如果你们服务节点数量多的话。

**Comment by a13707331174** [comment]
@stoneapple,你好,能在详细说说吗,现在的问题是A,B是两个独立的zk集群,虽然同时把dubbo.registry.address配置两个地址,但是registryService.subscribe只能接受一个zk的回调消息,

**Comment by chickenlj** [comment]
You can achieve that by customizing `RegistryServerSync`.

**Comment by a13707331174** [comment]
@chickenlj,是定义多个registryService吗,这样的话,如果增加或减少对某注册中心的监控,要改代码啊

**Comment by chickenlj** [comment]
Yes, you need to define extra RegistryService using another Registry address and customize RegistryServerSync.
