### ISSUE TITLE
When i use the parameters configured in the dubbo provider in the routing rules, the rules can not be matched

### ISSUE THREAD

**Issue by haodut** [alibaba/dubbo#1201]
如果将参数添加到dubbo provider中，例如：
`<dubbo:provider  serialization="fastjson" />`
这样生成的url中会带有 default.serialization=fastjson 这样的参数。
如果路由规则设置为 "=> serialization=fastjson"，是无法过滤出带有 default.serialization=fastjson 的提供者的。

**Comment by chickenlj** [comment]
The router can not match both `serialization` and `default.serialization` automatically. So try use `default.serialization`?

**Comment by haodut** [comment]
@chickenlj Condition router should try use default.serialization. I have fixed this in #1204
