### ISSUE TITLE
Changes of dubbo project structure.

### ISSUE THREAD

**Issue by chickenlj** [alibaba/dubbo#1209]
We have made some adjustments to the current project structure：

* Optimization for maven package and dependency modules
* Remove OPS modules like dubbo-admin, dubbo-monitor from the core project.

We made this change mainly for the following purposes:

* Extract OPS from the core library, so projects can evolve at their own pace.
* A good start for coding modular and packaging modular

1. Core project structure
 dubbo-parent ...........................................  parent pom introducing basic dependencies and plugins
 dubbo-common ......................................... Not Changed
 dubbo-container ........................................ Not Changed
 dubbo-remoting ......................................... Not Changed
 dubbo-rpc .................................................. Not Changed
 dubbo-cluster ............................................. Not Changed
 dubbo-registry ............................................ Not Changed
 dubbo-monitor ............................................ Not Changed
 dubbo-filter ................................................. Not Changed
 dubbo-config ............................................... Not Changed
 dubbo-demo ................................................ Not Changed
 dubbo-plugin ............................................... Not Changed
 dubbo-test ................................................... Not Changed
 Hessian Lite(Alibaba embed version) ........... Not Changed
 dubbo-dependencies ................................... management for thirdpart dependencies
 bom .............................................................. bom of all `sub-modules` users can depend on
 all .................................................................  packaging`dubbo-all.jar`

2. [dubbo-ops](https://github.com/dubbo/dubbo-ops/tree/for_dubbo-2.6.1)
 dubbo-admin ............................................. Service Management OPS
 dubbo-monitor-simple .............................. Reference implementation of monitor
 dubbo-registry-simple .............................. Reference implementation of registry

**Comment by chickenlj** [comment]
I will push the above changes to a new branch lately.

**Comment by randy-zs** [comment]
dubbo-admin 项目以后还会更新吗？现在页面上完全没有入口啊。只能去 https://github.com/alibaba/dubbo/releases 里面找。

**Comment by diecui1202** [comment]
@randy-zs dubbo admin is here: https://github.com/apache/incubator-dubbo-ops

We're working on the new Dubbo OPS, welcome to join.

**Comment by johnsonzhengCN** [comment]
hey，why can i receive this mail?haha







在 2018-09-25 09:49:06，"Jerrick Zhu" <notifications@github.com> 写道：


@randy-zs dubbo admin is here: https://github.com/apache/incubator-dubbo-ops

We're working on the new Dubbo OPS, welcome to join.
