### ISSUE TITLE
Does dubbo-monitor  consider data collection asynchronously?

### ISSUE THREAD

**Issue by zhaojigang** [alibaba/dubbo#1212]
![image](https://user-images.githubusercontent.com/14085645/34872098-a1049082-f7ca-11e7-80b3-88dcf511a223.png)
代码看上去只处理了同步情况，异步调用并没有处理

**Comment by chickenlj** [comment]
Yes, it does not handles async invoke, we can track the issue in dubbo/dubbo-ops#8
