### ISSUE TITLE
Inconsistent charset: telnet uses `GBK` while `dubbo:protocol` uses `utf-8` by default.

### ISSUE THREAD

**Issue by comdeng** [alibaba/dubbo#1213]
dubbo的telnet协议缺省的编码是GBK，而dubbo:protocol的缺省编码是UTF-8 。这就导致如果不在dubbo的服务的配置里边不显示指定编码时，通过telnet协议返回的内容的编码是GBK，而有些中文从GBK再转回UTF-8的时候容易出现乱码（如人民币符号$）。这种不一致给调试带来比较大的麻烦，需要经过大量的反复校验才能发现问题所在。
因此，建议telnet的缺省编码改得和dubbo:protocol的缺省编码一致，都为UTF-8。

dubbo:protocol 的缺省编码 参见：http://dubbo.io/books/dubbo-user-book/references/xml/dubbo-protocol.html

telnet协议的默认编码参见：
https://github.com/alibaba/dubbo/blob/master/dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/telnet/codec/TelnetCodec.java 第80行
```
    try {
            return Charset.forName("GBK");
        } catch (Throwable t) {
            logger.warn(t.getMessage(), t);
        }
```

**Comment by lovepoem** [comment]
Is fixed in  https://github.com/alibaba/dubbo/commit/235342e7f2180d74cd1af08308c981d40665ef82

**Comment by comdeng** [comment]
ok

**Comment by ThomasLau** [comment]
THX. this is helpful.
