### ISSUE TITLE
providers.size >= 0 always true

### ISSUE THREAD

**Issue by hqq2023623** [alibaba/dubbo#1216]
com.alibaba.dubbo.governance.web.governance.module.screen.Providers#getServiceAppMap 
at line 133 ， should be providers.size > 0 or just delete this comparison cause the next for will skip if proviers.size == 0

**Comment by chickenlj** [comment]
Would you please create a Pull Request?

**Comment by lovepoem** [comment]
Is there anything wrong with this?   providers.size >= 0  @hqq2023623

**Comment by hqq2023623** [comment]
if providers != null ,  this line will look like : (providers != null && true) , I think it's no need to do this @lovepoem
