### ISSUE TITLE
MonitorFilter initial concurrent count error

### ISSUE THREAD

**Issue by zhaojigang** [alibaba/dubbo#1217]
private AtomicInteger getConcurrent(Invoker<?> invoker, Invocation invocation) {
        String key = invoker.getInterface().getName() + "." + invocation.getMethodName();// 接口名.方法名
        AtomicInteger concurrent = concurrents.get(key);
        if (concurrent == null) {
            **concurrents.putIfAbsent(key, new AtomicInteger());**
            concurrent = concurrents.get(key);
        }
        return concurrent;
    }

这里应该改为new AtomicInteger(1)

**Comment by chickenlj** [comment]
`getConcurrent()` is not responsible for counter increment.

```java
getConcurrent(invoker, invocation).incrementAndGet(); // count up
```

**Comment by zhaojigang** [comment]
奥，sorry
