### ISSUE TITLE
How to configure a customized serialization.

### ISSUE THREAD

**Issue by sswater** [alibaba/dubbo#1223]
我已经实现好了自己的序列化方式，如何添加？

我知道，dubbo 自己的序列化方式，配置在：
META-INF/dubbo/internal/com.alibaba.dubbo.common.serialize.Serialization

我自己也在自己的 jar 包中，同样的位置，配置了序列化方式，也能正常工作。

我的问题是：
我总感觉， META-INF/dubbo/internal/com.alibaba.dubbo.common.serialize.Serialization 是 dubbo 自带的序列化方式配置的地方。当新添加自定义序列化方式时，是不是应该有其他地方，或者另一个配置文件？

**Comment by chickenlj** [comment]
You can put your extensions under `META-INF/dubbo` or `META-INF/services/`.
