### ISSUE TITLE
The access control rules configured in dubbo-admin do not take effect for rest

### ISSUE THREAD

**Issue by zhuoyuehc** [alibaba/dubbo#1224]
dubbo-admin里面配置的访问控制规则只对dubbo接口生效，对rest接口不生效，请问原因是什么？有解决办法吗？

**Comment by chickenlj** [comment]
What control rules do you use, Could you describe your question in more detail?

**Comment by zhuoyuehc** [comment]
我的应用提供了rest接口，postman测试调用成功，想对rest做访问控制，在dubbo-admin里分别针对ip做了白名单、黑名单限制，经过测试都没有效果，不知道是否在dubbo-cluster里路由匹配的时候没有做rest的处理？

**Comment by chickenlj** [comment]
@zhuoyuehc The route policy treats `rest`, `dubbo` and any other protocols as the same, so it should works for rest.

I suggest you check the data write to your registry first, for example, if you use ZK, check the data under /dubbo/your service/routers/
