### ISSUE TITLE
Can not use dubbo annotation @Reference in Controller?

### ISSUE THREAD

**Issue by huangxincheng** [alibaba/dubbo#1225]
请问除了
将全部配置都放到springMVC-servlet.xml，这样只生成一个上下文,和 在springMVC-servlet.xml也加入duboo的配置 还有其他解决方案吗

**Comment by chickenlj** [comment]
@Reference can be used in Controller, please check your `@DubboComponentScan` configuration.
[examples](https://github.com/alibaba/dubbo/tree/master/dubbo-test/dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/annotation)
