### ISSUE TITLE
`qos-server can not bind localhost:22222` when using 2.6.0.

### ISSUE THREAD

**Issue by coolrainman** [alibaba/dubbo#1230]
ERROR 8940 --- [           main] com.alibaba.dubbo.qos.server.Server      :  [DUBBO] qos-server can not bind localhost:22222, dubbo version: 2.6.0, current host: 127.0.0.1

![image](https://user-images.githubusercontent.com/3948331/35022953-784a7cf4-fb73-11e7-954e-3a643dd7a72e.png)

如何解决？

**Comment by chickenlj** [comment]
You must have more than one dubbo applications in your machine. You can avoid this by [specify another port explicitly](http://dubbo.io/books/dubbo-user-book/references/qos.html).
