### ISSUE TITLE
refundant nullcheck of value known to non-null

### ISSUE THREAD

**Issue by hqq2023623** [alibaba/dubbo#1231]
There are some "refundant nullcheck of value known to non-null" suggests can be found by findBugs plugin, maybe we should handle these to make the code cleaner
example : CacheFilter#invoke ,  check the (cache != null) twice

**Comment by ralf0131** [comment]
Hi, could you provide more details (file name, line number for example)?

**Comment by hqq2023623** [comment]
## type1 : check null more than one time
### FutureFilter#fireInvokeCallback
line 110 ，  onInvokeMethod is checked by line 107
<img width="984" alt="1" src="https://user-images.githubusercontent.com/6971152/35096459-414c308e-fc87-11e7-986a-b1cc43ca2b0b.png">
### the same as   FutureFilter#fireReturnCallback
<img width="996" alt="2" src="https://user-images.githubusercontent.com/6971152/35096479-598bd4a6-fc87-11e7-8915-411a295c1751.png">
### and   FutureFilter#fireThrowCallback
<img width="998" alt="3" src="https://user-images.githubusercontent.com/6971152/35096502-68242766-fc87-11e7-8e45-e95f4fe8a7ec.png">

## type2 :  checked by context
### MergeableClusterInvoker#invoke ,at line 144
<img width="727" alt="4" src="https://user-images.githubusercontent.com/6971152/35096537-83122546-fc87-11e7-93b5-6a184a8d0361.png">
returnType.getMethod() will not return null
<img width="865" alt="5" src="https://user-images.githubusercontent.com/6971152/35096555-938d8a96-fc87-11e7-82e7-144faa2b68e4.png">

**Comment by hqq2023623** [comment]
## type3 :  call method that never return null
ExtensionLoader#hasExtension  ,  at line 333
<img width="682" alt="7" src="https://user-images.githubusercontent.com/6971152/35097258-5606f1dc-fc8a-11e7-9ef8-5ac64a94bb82.png">
ExtensionLoader#getExtensionClass() never return null 
<img width="879" alt="8" src="https://user-images.githubusercontent.com/6971152/35097265-5f44e966-fc8a-11e7-8b00-ae9319c56c0a.png">

**Comment by hqq2023623** [comment]
## type4 : check by both caller and self
### caller : RegistryDirectory#notify , at line 207
<img width="602" alt="1" src="https://user-images.githubusercontent.com/6971152/35097474-3be93ed0-fc8b-11e7-8a43-f7b3c530176f.png">
### self : RegistryDirectory#toRouters , at line 309
<img width="766" alt="2" src="https://user-images.githubusercontent.com/6971152/35097481-4731a520-fc8b-11e7-8695-f37c5293b2a7.png">

**Comment by hqq2023623** [comment]
@ralf0131

**Comment by ralf0131** [comment]
Hi @hqq2023623 Thanks for pointing out. It will be really appreciate if you can create a pull request~

**Comment by chickenlj** [comment]
Thanks, i will review the PR laterly.
