### ISSUE TITLE
typo in ZookeeperRegistry.java

### ISSUE THREAD

**Issue by hqq2023623** [alibaba/dubbo#1233]
branch : master , version : 2.6.x
1、 method name : doUnsubscribe  , fix:  doUnSubscribe
<img width="740" alt="sub" src="https://user-images.githubusercontent.com/6971152/35077199-dacb7c66-fc36-11e7-93ca-568728607086.png">

2、 method : toCategoriesPath , local variable categroies , fix : categories  
<img width="816" alt="cat" src="https://user-images.githubusercontent.com/6971152/35077201-e0129a2e-fc36-11e7-9da9-de9c06a813b9.png">

**Comment by ralf0131** [comment]
Hi, thanks for reporting.  Would you mind sending us a pull request?
