### ISSUE TITLE
@Reference can not be injected if consumer starts before provider.

### ISSUE THREAD

**Issue by VirensCn** [alibaba/dubbo#1235]
提供者 没有启动， 只启动 消费者的情况下@Reference  注解不能注入，就算之后启动提供者也不能重新注入，必须得先启动提供者再启动消费者才能成功注入。

  @DubboComponentScan 使用了的。

**Comment by foreveryang321** [comment]
我也是，想知道有没有解决方案，或者后续有没有这方面的优化计划

**Comment by chickenlj** [comment]
Can you provide a demo project? Some guys have reported this problem, but i can't reproduce in my environment.

**Comment by VirensCn** [comment]
@chickenlj 
@foreveryang321 

好了，可以不用找这个问题，我已经发现了。

在配置Consumer 的时候只要将check 设置为 false，就可以了。

`	@Bean
	public ConsumerConfig consumerConfig() {
		ConsumerConfig config = new ConsumerConfig();
		config.setLoadbalance("roundrobin");
		config.setMock("return null");
		config.setGroup("virens");
		config.setTimeout(10000);
		config.setDefault(true);
		config.setCheck(false);

		return config;
	}`

**Comment by foreveryang321** [comment]
Consume配置check=false，已经解决我的问题，谢谢了
