### ISSUE TITLE
Can i configure Service Mock to return a pojo(a Car instance for example)?

### ISSUE THREAD

**Issue by zhaojigang** [alibaba/dubbo#1238]
![image](https://user-images.githubusercontent.com/14085645/35105938-e04d9d24-fca7-11e7-9849-d4a4bddeb18b.png)
服务降级能否配置返回值为一个具体的可以自己给属性赋值的pojo对象，例如Car；上边这样配置只能返回一个String；如果改为mock=force:return+empty，则只能返回一个Car的空对象（属性没有赋值）；当然实现一个Mock类是可以的（mock=force:com.alibaba.dubbo.demo.DemoServiceMock），但是有没有可以直接mock=force:return+自己配置属性的pojo来简单的完成的这个功能？

**Comment by chickenlj** [comment]
Yes, you can achieve that by using `mock`. But currently we don't have a documentation introducing this feature, you can refer the [source code](https://github.com/alibaba/dubbo/blob/master/dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/router/MockInvoker.java) for details of how to configure.
