### ISSUE TITLE
Some fields deserialized result lost(turns out to be null) .

### ISSUE THREAD

**Issue by wanggeqiang** [alibaba/dubbo#1240]
dubbo版本2.4.7
如下图代码  客户端获取的时候 data  存在部分返回值为null  服务端日志输出是有值的 

public ResponseModel<String> getA(CartYzParam cartYzParam)
ResponseModel responseModel = new ResponseModel();
    CartYzResponse cartYzResponse = getAllCartData4PC(cartYzParam, responseModel);
    boolean hasData = false;
    if (cartYzResponse != null)
    {
      List demandCartData = cartYzResponse.getDemandCartData();
      String returnJson = null;
      if (!(CollectionUtils.isEmpty(demandCartData))) {
        hasData = true;
        returnJson = JSONArray.toJSONString(demandCartData);
        responseModel.setData(returnJson);
      }

      this.logger.error(new StringBuilder().append("需求清单返回json：").append(returnJson).toString());

      if (hasData)
        responseModel.setStatus(0);
      else
        responseModel.setStatus(2);
    }
    else {
      responseModel.setStatus(1);
    }
    return responseModel;

================================================================
public class ResponseModel<T>
  implements Serializable
{
  private static final long serialVersionUID = -906650523L;
  public static final int RESULT_ERROR = 1;
  public static final int RESULT_OK = 0;
  public static final int RESULT_NO = 2;
  private int status;
  private String msg;
  private T data;

  public int getStatus()
  {
    return this.status;
  }

  public void setStatus(int status) {
    this.status = status;
  }

  public T getData() {
    return this.data;
  }

  public void setData(T data) {
    this.data = data;
  }

  public String getMsg() {
    return this.msg;
  }

  public void setMsg(String msg) {
    this.msg = msg;
  }

  public String toString()
  {
    return "ResponseModel{data=" + this.data + ", status=" + this.status + ", msg='" + this.msg + '\'' + '}';
  }

  public ResponseModel(int status, String msg)
  {
    this.msg = msg;
    this.status = status; }

  public ResponseModel(int status, String msg, T data) {
    this.data = data;
    this.msg = msg;
    this.status = status;
  }
}

**Comment by chickenlj** [comment]
Which serialization framework do you use?
Highly recommend you check the DTO versions on both consumer and provider, there may be some compatibility problems when you use different versions of Class.
