### ISSUE TITLE
Unable to connect to zk.local.nucc.com:2181

### ISSUE THREAD

**Issue by zhangshuge** [alibaba/dubbo#1241]
当DNS服务不可用无法解析ZK的域名时，请求dubbo的服务会受到影响吗？理论上是会通过缓存信息直连访问的，但是实际情况是当DNS不可用时我有好多dubbo的操作都超时了，请问有人遇到过这种情况吗？应用会抛出org.I0Itec.zkclient.exception.ZkException: Unable to connect to zk.local.nucc.com:2181异常。

**Comment by chickenlj** [comment]
What dubbo version do you use? The previous version may block the remote call when registry can not be reached, we recommend you upgrade to the latest dubbo version.
