### ISSUE TITLE
How to achieve cross-language(java-C) communication using dubbo?

### ISSUE THREAD

**Issue by hellokejian** [alibaba/dubbo#1244]
想请问一下，若要实现跨语言通信，例如Java与c系统互相通信，dubbo目前支持吗？或者dubbo配合哪种产品技术能达到目的？谢谢！

**Comment by chickenlj** [comment]
Currently, we only support cross-language communication by using `hessian`, the good new is @lovepoem is now working on thrift supporting.  Both non-java sides don't support service management, such as service registry, service discovery, e.g.
