### ISSUE TITLE
When will "spring-boot-dubbo-starter" being released？

### ISSUE THREAD

**Issue by wangzhanxu** [alibaba/dubbo#1248]
如题，好像之前说过官方会考虑出dubbo整合spring-boot的项目，但是什么时候开始呢？

**Comment by CodingOX** [comment]
https://github.com/dubbo/dubbo-spring-boot-project
 can this help you?

**Comment by mercyblitz** [comment]
https://github.com/dubbo/dubbo-spring-boot-project

**Comment by ralf0131** [comment]
Hi please checkout this #1251

**Comment by shenzhuan** [comment]
关于dubbo+shiro导致dubbo无法注入的问题解决方案，这个怎么解决呢

**Comment by chickenlj** [comment]
@shenzhuan Can you create a issue and give more details of your problem?
