### ISSUE TITLE
Which network interface will be used for registry

### ISSUE THREAD

**Issue by Haitianisgood** [alibaba/dubbo#1250]
环境：
centos 6
dubbo 2.5.3
网卡：
eth0：内网IP
eth1: 公网IP

每次启动时候，注册的信息，总是去获取eth1的外网IP

请问：我如指定要它去获取eth0,内网IP？

**Comment by chickenlj** [comment]
You can specify the ip for registry:
1. set `hostname ip' mapping in `/etc/hosts`
2. [use JVM parameter or environment variables](https://github.com/dubbo/dubbo-docker-sample)

**Comment by Haitianisgood** [comment]
我已经在/etc/hosts中填写hostname 对应内网IP了，根本不管用
