### ISSUE TITLE
typo in ReferenceConfig

### ISSUE THREAD

**Issue by hqq2023623** [alibaba/dubbo#1260]
### ReferenceConfig#init , at line 307
change : prifix -> prefix
<img width="746" alt="1" src="https://user-images.githubusercontent.com/6971152/35309902-a22d3ed2-00e9-11e8-9928-e394b9e3d632.png">

### by the way,  ReferenceConfig#setInterface , at line 476
it's no need to cast null to String
<img width="903" alt="2" src="https://user-images.githubusercontent.com/6971152/35309908-b09e4a92-00e9-11e8-9725-8e6ff8071370.png">

**Comment by ralf0131** [comment]
Hi, would you kindly send us a pull request?
