### ISSUE TITLE
I have implemented a service that calls C programs with JNI, can it being registered as a dubbo service?

### ISSUE THREAD

**Issue by hellokejian** [alibaba/dubbo#1269]

**Comment by kimmking** [comment]
可以

**Comment by hellokejian** [comment]
那是不是就意味着可以变相地将C程序作为服务提供者以实现Java-C跨语言通信？

**Comment by chickenlj** [comment]
`JNI` is the tech your internal service uses, dubbo doesn't have a restriction on your implementation details. 
Anyway, you always need a `java shell` to communicate with other dubbo services and to use the service management features that dubbo highlights.
