### ISSUE TITLE
dubbo-admin of version 2.5.3 can't delete expired data.

### ISSUE THREAD

**Issue by lyg945** [alibaba/dubbo#1270]
我们公司在使用dubbo时发现了一个问题，在dubbo-admin上发现  ，每次重启dubbo-provides 服务端注册到zk后，dubbo-provides 关闭后一周，这个缓存也不会自动注销。（按官方文档上说的，dubbo-provides 服务端关闭后会从zk上自动注销，不知道为什么我们的项目不会自动注销？？？）

172.12.6.67 这个ip是开发环境本地电脑注册到test服务器zk的记录，过了好几个月也不会自动删除（没办法只能禁用掉，或者重启zk。。。等服务）

暂时解决方案是：
1.重启  zk，dubbo-admin，dubbo-provides 服务端
2.把不是test环境的dubbo-provides 服务端禁用掉，以免影响test环境

我们公司相关程序jar版本如下：
dubbo：2.5.3
dubbo-admin：2.5.3
zk ：3.3.3
zkclient： 0.1
![1](https://user-images.githubusercontent.com/3752131/35367485-7d35c4de-01b9-11e8-9af6-9a64623d1edb.png)
![2](https://user-images.githubusercontent.com/3752131/35367494-865f6ccc-01b9-11e8-825d-bcf19e2d3b13.png)
![3](https://user-images.githubusercontent.com/3752131/35367499-8d49bb32-01b9-11e8-8043-daafaa8d80f6.png)

**Comment by SuperDubbo** [comment]
这个肯定不存在的，还有为啥开发要和测试用一套呢，再说，开发不注册到上面也可以使用啊，只能说你使用姿势有问题啊

**Comment by SuperDubbo** [comment]
register | register | boolean | 可选 | true | 服务治理 | 是否向此注册中心注册服务，如果设为false，将只订阅，不注册

**Comment by chickenlj** [comment]
Please upgrade dubbo version to 2.5.9 or 2.6.0, and use the latest dubbo-adimin
