### ISSUE TITLE
@Reference should support annotating on custom annotation class.

### ISSUE THREAD

**Issue by charpty** [alibaba/dubbo#1279]
hi, 请问可以让```@Reference```能够注解在自定义的注解上吗? 这样我们可以用自定义的注解来注入dubbo的服务.
比如我们想叫```@DubboAutowired```, 里面已经设置了我们的默认想的一些值.
```@DubboAutowired```通过Spring的```@AliasFor```来把值传递给```@Reference```, 所以效果上自定义注解和```@Reference```一样.

**Comment by charpty** [comment]
如果考虑其他因素不方便放开的话, 那只能通过 ```BeanPostProcessor```来实现自定义扫描、注入. 这对我们来说比较麻烦且有风险,还是希望能使用dubbo官方的支持

**Comment by charpty** [comment]
上午好阿里的大牛们~, 因为改的比较简单,我就直接提个单,麻烦查看下

**Comment by charpty** [comment]
![image](https://user-images.githubusercontent.com/8869963/35492629-fc043e44-04e8-11e8-8da5-a02b44a8e06c.png)
这是对@Service注解的处理示例, 想在@Reference上做类似处理时发现了不能注解在自定义注解上

**Comment by chickenlj** [comment]
Thanks, we have received your PR, i think that's a reasonable enhancement. Do you think add a `ElementType.ANNOTATION` will solve this problem?

**Comment by charpty** [comment]
@chickenlj hi,
Nice suggestion. I have modified that. Please check it.

**Comment by charpty** [comment]
@chickenlj 改了~ 麻烦再review下~ D:)

**Comment by chickenlj** [comment]
done

**Comment by wcp1231** [comment]
@charpty @chickenlj 请教一下，在 `ServiceAnnotationBeanPostProcessor.java` 中是通过 `AnnotationUtils.findAnnotation(beanClass, Service.class);` 获取的 `@Service` 注解，那这里自定义的 `@DubboService` 注解里的属性是怎么传递给 `@Service` 的？

我在 Provider 上只用 `@DubboService` 最后得到的 bean 并没有我配置的信息。
