### ISSUE TITLE
How to specify "connect timeout"?

### ISSUE THREAD

**Issue by sunng87** [alibaba/dubbo#1281]
目前 config 类只暴露了一个 timeout 属性，即请求的 timeout。目前我们的网路环境有些苛刻，首次连接的时候默认的 3秒连接超时不够用，希望可以在 config 里开放 connect timeout 的自定义设置。

**Comment by chickenlj** [comment]
You can use <dubbo:parameter/>, like this:
```xml
<dubbo:service>
    <dubbo:parameter name="connect.timout" value="5000" />
</dubbo:service>
``'

**Comment by ldkjdk** [comment]
<dubbo:parameter name="connect.timout" value="5000" /> 这个是错的 parameter 不允许 name 属性，纠正如下
<dubbo:parameter key="connect.timout" value="5000" /> 属性name 换成 key 参考dubbo.xsd    <xsd:complexType name="parameterType"> 部分

**Comment by ldkjdk** [comment]
![image](https://user-images.githubusercontent.com/12707336/111068304-3bd2d100-8503-11eb-8b1b-dc2fa5d79454.png)

**Comment by sage417** [comment]
connect.timeout

**Comment by tradeshark** [comment]
可以设置如下参数：

``` yml
dubbo:
  provider:
    parameters:
      connect.timeout: 10000
```
