### ISSUE TITLE
How to specify qos port in XML with 2.5.9.

### ISSUE THREAD

**Issue by shiqingshun** [alibaba/dubbo#1282]
在使用rmi协议时，独立的qos端口需要如何配置

使用rmi协议的时候，共用端口，qos不生效

**Comment by chickenlj** [comment]
Currently, we don't support XML configuration.
You can use `dubbo.properties` instead:
`dubbo.application.qos.port=22222`

**Comment by shiqingshun** [comment]
I found the way, Add <dubbo:parameter key="qos.port" value="22224"/> under the <dubbo: registry node


for example:

<dubbo:registry client="curator" protocol="${dubbo.registry.protocol}" address="${dubbo.registry.address}" username="${dubbo.registry.username}" password="${dubbo.registry.password}" register="true">
        <dubbo:parameter key="qos.port" value="22224"/>
    </dubbo:registry>

**Comment by chickenlj** [comment]
@shiqingshun Yes, that will work, good job.
