### ISSUE TITLE
Why the dubbo protocol-implementation version changed to 2.0.1 since  2.5.9 release?

### ISSUE THREAD

**Issue by cnhans** [alibaba/dubbo#1286]
Why  dubbo protocol-implementation version changed to 2.0.1?

**Comment by cnhans** [comment]
Cannot resolve reference to bean 'esClient' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'esClient': Invocation of init method failed; nested exception is java.lang.IllegalStateException: availableProcessors is already set to [4], rejecting [4]

还跟es的netty有冲突。。。

**Comment by chickenlj** [comment]
> Why dubbo protocol-implementation version changed to 2.0.1?

Sorry this change has bothered you, actually we haven't changed the dubbo RPC protocol at all, so don't worry to use the new version. This change only benefits those who use RMI protocol.
Currently, dubbo framework uses the `version` key to pass version information between consumers and providers, but actually there's no code uses this feature before 2.5.9. Lately, we want to use this feature to identify peers use different versions, so we can do upgrade the RPC protocol smoothly.
