### ISSUE TITLE
How to configure RequestContextListener when i use dubbo framework?

### ISSUE THREAD

**Issue by ducat7** [alibaba/dubbo#1288]
原先RequestContextListener是配在web.xml文件里，让spring获取session、request、response等对象，方便在普通Bean中使用这些对象。
现在用Dubbo做微服务，Consumer如何将session等对象传给Provider使用？？？
比如：登录时，获取session里存储的User信息，进行验证。
在Provider中如何配置web.xml？？？

**Comment by chickenlj** [comment]
It's the same as what you do before, dubbo will not affect the configuration of web.xml.

**Comment by ducat7** [comment]
@chickenlj Dubbo Provider服务是用jar打包、以Dubbo Main的形式启动的，那么，如何加载web.xml文件？即：web.xml写在jar包的什么默认位置可以默认加载它？

项目架构结构（maven模块项目）：
Commons子模块（公共功能区）
Provider API子模块
Provider IMPL子模块（jar）
SpringMVC子模块（war）

**Comment by mercyblitz** [comment]
Bad design , Do you have to use `HttpServletRequest` on Provider?

**Comment by ducat7** [comment]
@mercyblitz 是的，我使用的是SpringSession来共享session，这将必须在web.xml中配置：
	
	<listener>
		<listener-class>org.springframework.web.context.request.RequestContextListener</listener-class>
	</listener>
	
	
	<filter>
		<filter-name>springSessionRepositoryFilter</filter-name>
		<filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
	</filter>
	<filter-mapping>
		<filter-name>springSessionRepositoryFilter</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>
如此，1、共享session。
2、在service或其他Bean中读取/存储session。

这几天发现Dubbo的HTTP协议使用Servlet，如下配置：
	
	<dubbo:protocol name="http" port="10080" server="tomcat" contextpath="api" />
但，还是没理解到web.xml应该存放到哪个位置？（即：Dubbo内嵌的Tomcat如何加载这个web.xml？）

请问：在微服务框架下，你是如何共享session的？
应用场景：登录者权限、单点登录、网络爬虫、商品信息、订单信息、财务信息、规则策略、神经网络
（这些是一次session信息，在session的生命周期里提供，session销毁就清理）

**Comment by ducat7** [comment]
这还能让用不？给个答案先！

**Comment by chickenlj** [comment]
@ducat7 The embedded tomcat doesn't support loading of web.xml. Please use servlet instead:
```xml
<dubbo:protocol name="http" port="10080" server="servlet" contextpath="api" />
```
Use a container to load your dubbo project and web.xml yourself
