### ISSUE TITLE
2.5.9, 2.6.0, whose code is the latest?

### ISSUE THREAD

**Issue by javahongxi** [alibaba/dubbo#1294]
谁的代码更新

**Comment by lovepoem** [comment]
2.6.0 （base on master） is a new feature version (merge dubbox's core feature)
 2.5.9（base on 2.5.x）  is a bug fix version （without dubbox's core feature）

the two releases are both not newest code，now the master branch have  newest code

**Comment by javahongxi** [comment]
OK
