### ISSUE TITLE
current master branch can‘t use netty4

### ISSUE THREAD

**Issue by zhaojigang** [alibaba/dubbo#1300]
使用当前的master分支，dubbo-demo-provider中配置：
<dubbo:provider server="netty4"/>
无法启动服务。
原因是：
![image](https://user-images.githubusercontent.com/14085645/35614304-95f6abec-06a9-11e8-8263-be595feca1e7.png)

跟到代码中发现是在META-INF/dubbo/internal/com.alibaba.dubbo.remoting.Transporter只有netty=xxx一条记录，而在dubbo2.5.8调试的时候是有四条记录的（包含netty4），这是为什么呢？
![image](https://user-images.githubusercontent.com/14085645/35614400-e8b4c18e-06a9-11e8-9e4e-4e73bdb3beb1.png)

**Comment by hqq2023623** [comment]
因为在当前master分支的dubbo-demo-provider模块没有依赖到dubbo-remoting-netty4这个模块，比较一下两个分支的dubbo-demo-provider模块的依赖就清楚了，intellij idea也有查看maven依赖图的功能

**Comment by zhaojigang** [comment]
确实是，没看仔细，sorry，原来的分支dubbo-demo-provider引用的是dubbo.jar，现在的master分支是单独引用的其中部分jar，remote这边只引入了dubbo-remoting-netty，谢谢！！！
