### ISSUE TITLE
dubbo-admin没了？

### ISSUE THREAD

**Issue by yangbo0317** [alibaba/dubbo#1307]
http://apache.etoak.com 访问不了

**Comment by web1992** [comment]
you can find it  [here](https://github.com/dubbo/dubbo-ops)

**Comment by 2222** [comment]
tks    @web1992

**Comment by ralf0131** [comment]
You can find the dubbo admin link in the readme file.

**Comment by kkillala** [comment]
@web1992 谢了兄弟。
