### ISSUE TITLE
How to active filter programmatically?

### ISSUE THREAD

**Issue by diwayou** [alibaba/dubbo#1312]
<dubbo:reference filter="xxx,yyy" />

<dubbo:consumer filter="xxx,yyy"/>

<dubbo:service filter="xxx,yyy" />

<dubbo:provider filter="xxx,yyy"/>

正常我们需要这样才能让一个filter生效，但是我现在做类似zipkin的监控系统，想要编程给consumer和provider加上我写的filter，如何做到

**Comment by chickenlj** [comment]
I think you can sse @Active to annotate your Filter implementation.
http://dubbo.io/books/dubbo-dev-book/SPI.html may help you.

**Comment by diwayou** [comment]
thanks!
