### ISSUE TITLE
shutdownhook can't unregister instances.

### ISSUE THREAD

**Issue by haiyang1985** [alibaba/dubbo#1313]
shutdownhook的时候不会执行FailbackRegistry的unregister方法。

首先，FailbackRegistry定义了一个全局的destroyed，默认值是false。
然后，shutdownhook在destroy之前会首先判断一下这个变量的状态，但是canDestroy就会把它置为true。
@Override
  public void destroy() {
    if (!canDestroy()){
      return;
    }
    super.destroy();
    try {
      retryFuture.cancel(true);
    } catch (Throwable t) {
      logger.warn(t.getMessage(), t);
    }
  }

最后，在真正执行unregister的时候，这个destroyed就会变成true被return掉了，导致FailbackRegistry的unregistry并不会被执行。
@Override
    public void unregister(URL url) {
        if (destroyed.get()){
            return;
        }
    super.unregister(url);
...
}

我看这个代码是8月30号修复issue#568的时候加的，这是个bug，还是有其他的考虑吗？还是我缺少配置？

**Comment by ralf0131** [comment]
Hi, if you think it can be improved, would you mind sending us a pull request?

**Comment by haiyang1985** [comment]
全部还原不会又引起issue#568的问题吗？我看当时改了好多个文件，这只是其中的一部分，看似是为了解决并发反注册的问题。

issue#568: 修复优雅停机问题 
- 修复注册中心 unexport 的并发问题 
- 修复关闭过程中，拿到的线程池为 null 的问题 
- 修复关闭过程中，拿到的 futures 为 null 的问题
