### ISSUE TITLE
How to invoke a method with "null" using telnet.

### ISSUE THREAD

**Issue by liuzhaozhao** [alibaba/dubbo#1314]
如：invoke XXX.XXXService.XXXMethod("abc", 0, null, null)
这种无法调用到服务，返回null

如果要传递null参数，该怎么写？

**Comment by scuwuyu** [comment]
When invoke a method with dubbo,the parameters can be "null",maybe something else is bad.

**Comment by changchangjie** [comment]
怎么被关掉了
