### ISSUE TITLE
About the strategy of processing result timeout in MergeableClusterInvoker.java (97-118).

### ISSUE THREAD

**Issue by Roysatm** [alibaba/dubbo#1320]
for (Map.Entry<String, Future<Result>> entry : results.entrySet()) {
            Future<Result> future = entry.getValue();
            try {
                **Result r = future.get(timeout, TimeUnit.MILLISECONDS);**
                if (r.hasException()) {
                    log.error(new StringBuilder(32).append("Invoke ")
                                    .append(getGroupDescFromServiceKey(entry.getKey()))
                                    .append(" failed: ")
                                    .append(r.getException().getMessage()).toString(),
                            r.getException());
                } else {
                    resultList.add(r);
                }
            } catch (Exception e) {
                throw new RpcException(new StringBuilder(32)
                        .append("Failed to invoke service ")
                        .append(entry.getKey())
                        .append(": ")
                        .append(e.getMessage()).toString(),
                        e);
            }
        }

假设有10个并行调用，需要获取这10个调用结果。假设获取结果超时失败是2s,通过97-118行代码可以看出极端情况获取这10个并行处理结果耗时可以是20s,不知作者设计这部分的思想是不是就是这种串行获取结果的思想？
for (Map.Entry<String, Future<Result>> entry : results.entrySet()) {
            Future<Result> future = entry.getValue();
            try {
                Result r = future.get(timeout, TimeUnit.MILLISECONDS);
                

在这段串行阻塞代码中 极端情况 第一个调用超时1.9s，第二个调用超时1.9s 以此类推，等到获取到第10个结果集时，可能这个线程耗时19s

**Comment by chickenlj** [comment]
future1.get(timeout) won't block future2, if future2 has finished, future2.get(timeout) will return immediately.

**Comment by Roysatm** [comment]
I don't understand, because 'future.get(timeout, TimeUnit.MILLISECONDS)' this the method is synchronized。

 /**
     * Waits if necessary for at most the given time for the computation
     * to complete, and then retrieves its result, if available.
     *
     * @param timeout the maximum time to wait
     * @param unit the time unit of the timeout argument
     * @return the computed result
     * @throws CancellationException if the computation was cancelled
     * @throws ExecutionException if the computation threw an
     * exception
     * @throws InterruptedException if the current thread was interrupted
     * while waiting
     * @throws TimeoutException if the wait timed out
     */
    V get(long timeout, TimeUnit unit)
        throws InterruptedException, ExecutionException, TimeoutException;
}


				Result r = future.get(timeout, TimeUnit.MILLISECONDS);
                if (r.hasException()) {
                    log.error(new StringBuilder(32).append("Invoke ")
                                    .append(getGroupDescFromServiceKey(entry.getKey()))
                                    .append(" failed: ")
                                    .append(r.getException().getMessage()).toString(),
                            r.getException());
                } else {
                    resultList.add(r);
                }

**Comment by kimmking** [comment]
I think @Roysatm  means the for statement is executed in the main thread, and processing task one by one.

**Comment by Roysatm** [comment]
yes,@kimmking

**Comment by Roysatm** [comment]
yes,@kimmking

**Comment by chickenlj** [comment]
@Roystam Am i get it wrong?  
```java
for (Map.Entry<String, Future<Result>> entry : results.entrySet()) {
        Future<Result> future = entry.getValue();
        try {
            ** Result r = future.get(timeout, TimeUnit.MILLISECONDS); **
            // future1.get(timeout) may block for 1.9s, but when you call future2.get() or future3.get(), they might return immediately because they have finished during the 1.9s.
            if (r.hasException()) {
                log.error(new StringBuilder(32).append("Invoke ")
                                .append(getGroupDescFromServiceKey(entry.getKey()))
                                .append(" failed: ")
                                .append(r.getException().getMessage()).toString(),
                        r.getException());
            } else {
                resultList.add(r);
            }
        } catch (Exception e) {
            throw new RpcException(new StringBuilder(32)
                    .append("Failed to invoke service ")
                    .append(entry.getKey())
                    .append(": ")
                    .append(e.getMessage()).toString(),
                    e);
        }
    }
```

**Comment by Roysatm** [comment]
Hi @chickenlj 你明白表述的意思，我们换个思路讨论这个问题，这个for循环的最大耗时是多少？

我的答案：最大耗时是 results.size() * timeout 


for (Map.Entry<String, Future<Result>> entry : results.entrySet()) {
        Future<Result> future = entry.getValue();
        try {
            ** Result r = future.get(timeout, TimeUnit.MILLISECONDS); **
            // future1.get(timeout) may block for 1.9s, but when you call future2.get() or future3.get(), they might return immediately because they have finished during the 1.9s.
            if (r.hasException()) {
                log.error(new StringBuilder(32).append("Invoke ")
                                .append(getGroupDescFromServiceKey(entry.getKey()))
                                .append(" failed: ")
                                .append(r.getException().getMessage()).toString(),
                        r.getException());
            } else {
                resultList.add(r);
            }
        } catch (Exception e) {
            throw new RpcException(new StringBuilder(32)
                    .append("Failed to invoke service ")
                    .append(entry.getKey())
                    .append(": ")
                    .append(e.getMessage()).toString(),
                    e);
        }
    }

**Comment by chickenlj** [comment]
If the timeout for every future is 1.9s, the most cost for all results will be 1.9s or a little higher.
Because when future1 timed out, future2 and future-n already also timed out, they will return immediately.

**Comment by Roysatm** [comment]
Hi @chickenlj  下面是我模拟97-118行for循环处理

for (Map.Entry<String, Future> entry : results.entrySet()) {
Future future = entry.getValue();
try {
Result r = future.get(timeout, TimeUnit.MILLISECONDS); 
if (r.hasException()) {
log.error(new StringBuilder(32).append("Invoke ")
.append(getGroupDescFromServiceKey(entry.getKey()))
.append(" failed: ")
.append(r.getException().getMessage()).toString(),
r.getException());
} else {
resultList.add(r);
}
} catch (Exception e) {
throw new RpcException(new StringBuilder(32)
.append("Failed to invoke service ")
.append(entry.getKey())
.append(": ")
.append(e.getMessage()).toString(),
e);
}
}


模拟三个任务处理，模拟出最后整个for循环处理时间
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.*;

public class Simulation {

    private static final ExecutorService EXECUTORS = Executors.newFixedThreadPool(3);

    public static long time = 0;


    public static void main(String[] args) {

        List<Future> list = new ArrayList<>();
        for (int i = 0; i < 3; i++) {
            Cal cal = new Cal();
            time = i * (1900 - i * 100)  + 1900;
            list.add(EXECUTORS.submit(cal));
        }
        long startTime = System.currentTimeMillis();
        for (int i = 0; i < 3; i++) {
            Future f = list.get(i);
            try {
                System.out.println(f.get(2, TimeUnit.SECONDS));
            } catch (Exception e) {
                throw new RuntimeException("访问超时");
            }
        }
        System.out.println("主线程处理时间 ： " + (System.currentTimeMillis() - startTime));
        EXECUTORS.shutdown();

    }

    static class Cal implements Callable {


        @Override
        public Object call() throws Exception {
            Thread.sleep(time);
            return new String("hello ");
        }
    }

}
运行结果：
![image](https://user-images.githubusercontent.com/13662524/36470293-50e697f6-1725-11e8-9956-bc267cb867d0.png)


正如上面我们讨论的“for循环的最大耗时是多少？”
我的理解运行的最大耗时应该是接近 results.size() * timeout，而不是接近timeout。
