### ISSUE TITLE
Will MonitorFilter cause performance problem?

### ISSUE THREAD

**Issue by taoyangxu** [alibaba/dubbo#1321]
高并发情况下，当启用了MonitorFilter的时候，请求会不定时的出现高延迟，关闭MonitorFilter后正常。
经过分析，可能出现问题的地方有：

1. 从MonitorFactory中获取Monitor有一个全局锁；
2. getIp(）问题
3. 可能是其他问题。

**Comment by chickenlj** [comment]
What version do you use?
