### ISSUE TITLE
<dubbo:method "oninvoke"  injection failure.

### ISSUE THREAD

**Issue by z529192557** [alibaba/dubbo#1324]
<dubbo:method name="sayHello" oninvoke="callback.oninvoke" onthrow="callback.onthrow"  onreturn="callback.onreturn"></dubbo:method>   spring 启动报错，如下图
![image](https://user-images.githubusercontent.com/9245774/35789484-7fe53c5c-0a77-11e8-888c-9711144561bb.png)
初步定位是DubboBeanDefinitionParser 类下parse方法中，oninvoke 没有像 onreturn（193行附近）那样，将callback.oninvoke 拆解成invoke 和invokeMethod，而是直接将callback.oninvoke当做Bean去处理，导致报错

**Comment by z529192557** [comment]
May I make a pull request to fix this issues?

**Comment by chickenlj** [comment]
Yes, create a PR whenever you find a problem or have a good idea.
