### ISSUE TITLE
In java8+ PermSize  MaxPermSize  vm args was unsupported

### ISSUE THREAD

**Issue by web1992** [alibaba/dubbo#1330]
> In java8+ `PermSize` and  `MaxPermSize`  vm args was unsupported

- See [#issues](https://github.com/alibaba/dubbo/issues/1284)
- You can see reason at [#link](http://openjdk.java.net/jeps/122)

> So we need change these vm args in shell(bat) scripts:

- [start.bat lines 11,15,19](https://github.com/alibaba/dubbo/blob/98c548aab1fef47b29cf7af451b7cd447205ec0a/dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.bat#L11,#L19)
- [start.sh lines 63,65](https://github.com/alibaba/dubbo/blob/98c548aab1fef47b29cf7af451b7cd447205ec0a/dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.sh#L63,#L65)

**Comment by web1992** [comment]
@ralf0131  I had open a new issues.

**Comment by ralf0131** [comment]
@web1992 Do you have a PR for this?

**Comment by web1992** [comment]
@ralf0131 If I could,I will send new PR later.

**Comment by ralf0131** [comment]
@web1992 That's great!

**Comment by web1992** [comment]
@ralf0131 I had send PR. #1347
