### ISSUE TITLE
长连接

### ISSUE THREAD

**Issue by suhuaguo** [alibaba/dubbo#1334]
怎么配置长连接呢，REST 的方式？

**Comment by zhaojigang** [comment]
http1.1默认是长连接，dubbo-rest会显式的关闭连接吗？（没用过dubbo-rest）

**Comment by suhuaguo** [comment]
不会的啦。我翻了源码，里面在 Netty 里面设置为长连接了。我用 jmeter 压测的时候，发现默认是 HTTP 协议，所以，在 dubbo-rest 应用前面挡住一个 Nginx ，性能总是提不上，后来改成 HTTP1.1 就可以了。
我一开始以为是 dubbo-rest 里面显示设置为短连接的啦。

**Comment by suhuaguo** [comment]
我用 Nginx 来处理短连接，后端Java 保持长连接。性能非常优越。因为Tomcat 不擅长于短连接
