### ISSUE TITLE
redis as a registry center ，url authentication username 

### ISSUE THREAD

**Issue by chenleijava** [alibaba/dubbo#1336]
Redis as a registry, if redis set a password, mandatory to fill in username, com.alibaba.dubbo.common.URL 150 lines
I think this logic is not rigorous, please pay attention to the next
···
     if ((username == null || username.length () == 0)
                 && password! = null && password.length ()> 0) {
             throw new IllegalArgumentException ("Invalid url, password without username!");
         }
···
dubbo version 2.6.0

**Comment by chickenlj** [comment]
#1195
We decide not to change this check currently. As for most cases, we should specify both user and password, and  also redis registry is really not a popular choice in dubbo.
