### ISSUE TITLE
Where is dubbo-admin?

### ISSUE THREAD

**Issue by mrlixiansheng** [alibaba/dubbo#1341]
where's dubbo admin?

**Comment by web1992** [comment]
You can see #1307

**Comment by mthhk** [comment]
提这个问题的人你是傻逼吗？？？？
别人辛辛苦苦日日夜夜给你搞开源，莫非是你爸爸？义务帮你？？？

**Comment by mthhk** [comment]
@mrlixiansheng 傻逼玩意

**Comment by beiwei30** [comment]
folks, don't do this, this is an engineering site, pls. focus :)
