### ISSUE TITLE
The "catch clause" in RpcCcontext.asyncCall() seem to be useless, and can be removed.

### ISSUE THREAD

**Issue by zhaojigang** [alibaba/dubbo#1346]
![image](https://user-images.githubusercontent.com/14085645/35962586-ee8cc5ae-0cec-11e8-883a-98b1c8baabe3.png)
RpcCcontext这里的第二个catch的作用是什么？捕捉removeAttachment(Constants.ASYNC_KEY);这里的异常吗？

**Comment by kimmking** [comment]
看样子可以去掉。

**Comment by kimmking** [comment]
you can submit a PR？

**Comment by zhaojigang** [comment]
ok, I submit a pr,  https://github.com/alibaba/dubbo/pull/1351 @kimmking

**Comment by chickenlj** [comment]
Thanks for your PR, i already had a review on it, please check.

**Comment by chickenlj** [comment]
We also recommend using english to start an issue.
