### ISSUE TITLE
how to install dubbo admin

### ISSUE THREAD

**Issue by MalcolmFF** [alibaba/dubbo#1349]
根据管理控制台安装安装手册，最要下载 dubbo-admin-2.4.1.war，地址已经连接不上了，并且现在的项目没有找到 dubbo admin，那请问 web 管理控制台如何安装呢？

**Comment by zwl1995** [comment]
下载一个dubbo-admin-2.4.1.war ,将这个war包放在tomcat中的webapps下面，启动即可，用户名/密码 root/root,访问地址：http://localhost:8080/dubbo-admin-2.4.1

**Comment by beiwei30** [comment]
you could find dubbo admin [here](https://github.com/dubbo/dubbo-ops). in order to keep core clean, we made the decision to move it out, sorry for the inconvenience, we will update the doc later.

**Comment by beiwei30** [comment]
doc has been updated, enjoy: http://dubbo.io/books/dubbo-admin-book/install/admin-console.html
