### ISSUE TITLE
Does the timeout include time costing for waiting request to be processed in a queue on provider?

### ISSUE THREAD

**Issue by Jaskey** [alibaba/dubbo#1356]
如果一个请求堆积在队列超过了timeout时间，会否被丢弃。

我这边看到一个服务正常耗时只有1毫秒的，却花了几十秒，超时1秒。想确认下timeout是否对队列等待的时间生效

**Comment by chickenlj** [comment]
By default, dubbo don't use a queue on provider side, if thread is exhausted, upcoming request will be rejected immediately.

**Comment by chickenlj** [comment]
Have you configured a queue explicitly?

**Comment by Jaskey** [comment]
what do you mean ?

What about queues? I set the thread num as 200 and use fixed thread pool. Does it have queue before we schedule it in thread?

**Comment by fightingaman** [comment]
我自己写过超时机制，我想dubbo应该也差不多，配不配线程池的队列，与客户端的超时与否是没有影响的，如果配了进入了队列，这个请求注定是要被执行的（除非发生特殊情况），如果没配，线程池没有空闲，则会拒绝提交抛出RejectedExecution，当然还有重试机制等等

**Comment by chickenlj** [comment]
> What about queues? I set the thread num as 200 and use fixed thread pool. Does it have queue before we schedule it in thread?

Dubbo has no queue for requests before schedule.
