### ISSUE TITLE
how to study dubbo source code?

### ISSUE THREAD

**Issue by 1061235166** [alibaba/dubbo#1358]
阅读dubbo源码从哪里入手好？这么大的一个框架，不知道从何看起。。

**Comment by rabel7** [comment]
http://dubbo.io/books/dubbo-dev-book/design.html 阅读一遍，然后断点跟踪你会有个头绪

**Comment by kimmking** [comment]
1、debug大法好。
2、看看这些材料，搞清楚设计思路和概念。
[阿里巴巴(B2B)的服务框架探索(钱霄).pdf](https://github.com/alibaba/dubbo/files/1713440/B2B.pdf)

[High_Performance_Remoting.pdf](https://github.com/alibaba/dubbo/files/1713445/High_Performance_Remoting.pdf)
[Service_Framework_Practices.pdf](https://github.com/alibaba/dubbo/files/1713448/Service_Framework_Practices.pdf)
[Dubbo_Framework_Extensions.pdf](https://github.com/alibaba/dubbo/files/1713442/Dubbo_Framework_Extensions.pdf)
[Dubbo_RPC_Features.pdf](https://github.com/alibaba/dubbo/files/1713443/Dubbo_RPC_Features.pdf)
[DubboInternals.zip](https://github.com/alibaba/dubbo/files/1713446/DubboInternals.zip)
[Framework_Design_Principles.pdf](https://github.com/alibaba/dubbo/files/1713444/Framework_Design_Principles.pdf)

3、自己动手写几个filter，rpc、remoting的扩展，就吃透了。

**Comment by 1061235166** [comment]
@rabel7 这个设计图一眼看过去太复杂了，容易懵逼。。
