### ISSUE TITLE
i found a mistake in  dubbo-user-book

### ISSUE THREAD

**Issue by DeadLion** [alibaba/dubbo#1359]
http://dubbo.io/books/dubbo-user-book/references/qos.html

//根据正则，上线部分服务
dubbo>offline com.*
OK

the comment is wrong,should be 下线部分服务

**Comment by kimmking** [comment]
https://github.com/dubbo/dubbo-docs/pull/1

you can submit a pr like this next time

**Comment by beiwei30** [comment]
fixed, thanks for your feedback.
