### ISSUE TITLE
Why most DubboServerHandler threads are all waiting , only few threads are in Runnable state?

### ISSUE THREAD

**Issue by Jaskey** [alibaba/dubbo#1360]
I have 200 threads in  a fixed pool in my provider, but when I analyze the jstack, I only have one thread is running but rest of them are all in WAITING state, which means though I have huge of requests but dubbo only assigns one thread to me!?

This is the error logs of my thread pool EXHAUSED : 
```
2018-02-10 13:46:54.194 [New I/O worker #40] WARN  com.alibaba.dubbo.common.threadpool.support.AbortPolicyWithReport -  [DUBBO] Thread pool is EXHAUSTED! Thread Name: DubboServerHandler-10.12.26.143:9000, Pool Size: 200 (active: 2
00, core: 200, max: 200, largest: 200), Task: 241799977 (completed: 241799777), Executor status:(isShutdown:false, isTerminated:false, isTerminating:false), in dubbo://10.12.26.143:9000!, dubbo version: 2.5.3, current host: 10.12.
26.143
```

Why is that and how to fix it.

My provider is configured like:

`<dubbo:protocol name="dubbo" transporter="netty"  port="9000" accesslog="false" threads="200" />`

**Comment by qcxyzff** [comment]
你的其它线程可能都在 I/O调用，你查看下是否都是阻塞在db,缓存，其它http访问之类

**Comment by chickenlj** [comment]
@Jaskey You should check the detailed stack of the Waiting thread, why is it waiting? who called the Object.wait() sort of code?
