### ISSUE TITLE
When using method level cache, no matter what i config, it's always LruCache.

### ISSUE THREAD

**Issue by zhaojigang** [alibaba/dubbo#1362]
consumer配置：
    <dubbo:reference id="demoService" check="false" interface="com.alibaba.dubbo.demo.DemoService">
        <dubbo:method name="sayHello" timeout="60000" **cache="threadlocal"**/>
    </dubbo:reference>

在执行的过程中，我们发现其实并不会创建ThreadlocalCache，而是用的LruCache，原因是在
![image](https://user-images.githubusercontent.com/14085645/36060257-e63276f2-0e80-11e8-9da7-36e41c7ef23a.png)
可以看到，当将cache配置在方法上而不是服务上的时候，传入的url只有"method.cache"参数而没有"cache"参数，但是CacheFactory$Adaptive这个类并没有作区分。

**Comment by kimmking** [comment]
it seems a bu

**Comment by hqq2023623** [comment]
有几个疑问：
1、dubbo分支或者版本是多少
2、CacheFactory$Adaptive这个类是你们自己写的吗，在dubbo源码里没看到
3、如果是自己写的，按照图里的代码创建的就应该是作为默认值的LruCache，原因如你所说没有cache这个key，你可以自己适配cache的key
4、看你的问题的话应该是期望在Reference和Method两层都配置cache的话应该统一的key是“cache"，那如果我希望Reference中不同的Method使用不同的cache该如何处理呢？
5、URL参数的设置可以在ReferenceConfig#init()方法查看
@zhaojigang

**Comment by zhaojigang** [comment]
1、当前master分支
2、CacheFactory$Adaptive是自适应生成的类
3、不是自己写的
4、不是这个期望，你理解错误了
@hqq2023623

**Comment by zhaojigang** [comment]
嗯，麻烦官方看一下，应该是个bug @kimmking

**Comment by chickenlj** [comment]
@zhaojigang Would you like to create a PR?

**Comment by Adam74211** [comment]
问题出在ExtensionLoader上， 在生成的代理类中，应该使用url.getMethodParameter而不是url.getParameter

**Comment by ma-xiao-guang-64** [comment]
@kimmking  I will fix it.
