### ISSUE TITLE
The heartbeat mechanism: both consumer and provider are sending heartbeat, can it be optimized and only keep heartbeat on consumer side?

### ISSUE THREAD

**Issue by zhaojigang** [alibaba/dubbo#1365]
dubbo的心跳机制，目前看是provider和consumer都在发，是否只要consumer端发送就ok了？而且目前来看，如果真的心跳超时了，reconnect的操作只有客户端可以发起

**Comment by qcxyzff** [comment]
客户端发心跳主要是为了reconnect，服务端发主要是为了防空闭。当然仅仅只是客户端发，也都可以做得到。

**Comment by chickenlj** [comment]
Would you please create a PR?
And i will also have a check on this issue recently.

**Comment by zhaojigang** [comment]
重新看了代码，发现provider端发送心跳是有必要的。假设consumer端挂了，如果provider端没有心跳机制，那么可能会导致资源泄露。
NettyChannel的close方法如下：
public void close() {
        // 1 将close属性设为true
        try {
            super.close();
        } catch (Exception e) {
            logger.warn(e.getMessage(), e);
        }
        // 2 从全局NettyChannel缓存器中将当前的NettyChannel删掉
        try {
            removeChannelIfDisconnected(channel);
        } catch (Exception e) {
            logger.warn(e.getMessage(), e);
        }
        // 3 清空当前的NettyChannel中的attributes属性
        try {
            attributes.clear();
        } catch (Exception e) {
            logger.warn(e.getMessage(), e);
        }
        // 4 关闭netty的channel，执行netty的channel的优雅关闭
        try {
            if (logger.isInfoEnabled()) {
                logger.info("Close netty channel " + channel);
            }
            channel.close();
        } catch (Exception e) {
            logger.warn(e.getMessage(), e);
        }
    }

**Comment by zhaojigang** [comment]
I closed this issue
