### ISSUE TITLE
How to extend the "Exchanger" SPI? I want to add parameters to URL dynamically.

### ISSUE THREAD

**Issue by ducat7** [alibaba/dubbo#1367]
信息交换扩展，这方面介绍的不多，怎么自定义实现啊？
基于传输层之上，实现 Request-Response 信息交换语义。
<dubbo:protocol exchanger="xxx" />
扩展接口：
com.alibaba.dubbo.remoting.exchange.Exchanger
com.alibaba.dubbo.remoting.exchange.ExchangeServer
com.alibaba.dubbo.remoting.exchange.ExchangeClient

需求：
Dubbo与Spring Session如何共享session？
我把Dubbo配置成http协议，放在Tomcat下。
已经扩展了Spring Session在Cookie、URL里获取sessionId。
现在是在Dubbo下如何扩展在Cookie、URL里设置sessionId？？？
（代码修改量少）
这个Exchanger层是怎么自定义实现的？
我看到里面有URL参数类型，这个是否可以添加URL里的参数，以达到consume端发送调用请求时传送sessionId，Spring Session在provide端拦截URL获取sessionId。
即：Spring Session同步sessionId，以达到session共享。
（解析Spring Session源码，这样是可以达到session共享的在servlet3下）
求指教...

**Comment by kimmking** [comment]
I dotnot understand why you broadcast http session to dubbo service。
in my opinion，generally dubbo service is a biz layer and independent with session。you can create a session filter attached to dubbo just like dubbox。then any parameter in session will recovered and passed to certainly service。

**Comment by chickenlj** [comment]
I also do not fully understand your requirement. I think you just want to pass the `sessionid` downstream when making a dubbo remote call, and `sessionid` will only be used on biz layer. Dubbo attachments is designed for that purpose.

And i have noticed that you use `http` protocol, Exchanger is only a abstract for `dubbo` protocol and it won't works for protocols like `http` or `hessian`.

**Comment by ducat7** [comment]
@kimmking @chickenlj 
1、项目需要共享session，在不改变现有业务代码基础上，穿插调用了session里保存的信息。
2、项目已经是通过Spring Session+Redis共享了session，现在只需要通过Cookie、URL传参把sessionId传递到各地业务实现层。
3、Spring Session是通过拦截Cookie、URL特定参数获取sessionId，再去Redis里寻找 相对应的session信息。

如此，Dubbo发送的URL里只要添加特定参数，那么，Spring Session首先拦截获取到sessionId就可以共享session了，不必变更业务代码了。否则，重构量很大。

我在寻找能在Dubbo consume端向provide端发送URL时，加入特定参数，以达到发送sessionId给provide端，让Spring Session自动拦截、获取、装载session。

即：如何给Dubbo URL里添加特定参数？？？

**Comment by chickenlj** [comment]
@ducat7 I think i understand your requirement now, do you mean `'http request'` when saying `URL`? I mistook it as `Dubbo URL`. 

Which protocol do you use, `http` or `hessian`? I think `attachments` should be the proper way to achieve this, but i remember that `attachments` doesn't support `http` and `hessian` currently. 

> 如此，Dubbo发送的URL里只要添加特定参数，那么，Spring Session首先拦截获取到sessionId就可以共> 享session了，不必变更业务代码了。否则，重构量很大。

What position should the parameter be added to the URL, will a request header work？
