### ISSUE TITLE
动态指定group来区别不同实现

### ISSUE THREAD

**Issue by zy198804065** [alibaba/dubbo#138]
请教个问题。一个接口有不同实现 除了用（group）预先配置好是哪一个实现外，还有通过编程的方式 动态指定的没？

**Comment by zy198804065** [comment]
消费端如下：@Reference()
	       private H200001Dubbo h200001Dubbo;  调用的时候 可以动态设置group么？用编程的方式

**Comment by teaey** [comment]
没能理解你说的
一般用版本区分不同实现
