### ISSUE TITLE
Ask for compatible problem

### ISSUE THREAD

**Issue by lintghi** [alibaba/dubbo#1383]
Our system A using dubbo 2.5.3 + Jdk1.6 + ZK 3.3.6 . 
Now  i want to new dubbo(2.5.9) and jdk (1.8) version in new module B. 
Can i upgrade zk to 3.4.6 and keep A using dubbo 2.5.3 + Jdk1.6, and A as consumer , B as provider?

**Comment by kimmking** [comment]
I think that's OK.
But my suggestion is that you should take some test case for it.
