### ISSUE TITLE
The url 404, and no any web page

### ISSUE THREAD

**Issue by netroby** [alibaba/dubbo#1392]
http://incubator.apache.org/projects/dubbo.html

Though the dubbo enter apache incubator, and list at the http://incubator.apache.org
There no web page at the url

**Comment by ralf0131** [comment]
Thanks for reporting, we've noticed this issue, and are working on fixing it.

Just stay tuned!

**Comment by ralf0131** [comment]
Hi, this is fixed.

Please check it again!

**Comment by netroby** [comment]
Nice job， have a good day

**Comment by netroby** [comment]
ping @ralf0131 ,  the main url still 404

http://dubbo.incubator.apache.org

**Comment by ralf0131** [comment]
Yes, there is still some transition work on going. You may [subscribe](https://github.com/alibaba/dubbo/issues/1393) to dev@dubbo.apache.org to get the latest updates.
