### ISSUE TITLE
Number type config data is lost in yaml file

### ISSUE THREAD

**Issue by daocr** [alibaba/dubbo#1399]
spring-boot-version : 1.5.9.RELEASE
dubbo.version : 2.6.0

bug 出现场景：
1、使用了@EnableDubbo 注解
2、配置文件使用的是 “.yml” 格式的文件 
![image](https://user-images.githubusercontent.com/28719772/36659592-edbbc7d4-1b0f-11e8-8dbf-d938ed49a840.png)

bug出现原因：
![image](https://user-images.githubusercontent.com/28719772/36659746-6ecd6ef4-1b10-11e8-87b5-942cb4ee1af1.png)

在yml 文件中，值是有数据类型的区分的，如果直接这样判断，会导致有些值被忽略

**Comment by ralf0131** [comment]
Hi, welcome to Dubbo community!

Please consider using English, Dubbo is a global community, and all the issues may be viewed and discussed by people all over the world.

Meanwhile, you can send email to dev@dubbo.apache.org or subscribe it, which is preferred way for discussing questions like this.

**Comment by lovepoem** [comment]
Fixed
