### ISSUE TITLE
tomcat8 appeared memory lean when shutdown

### ISSUE THREAD

**Issue by zjw2011** [alibaba/dubbo#1402]
/Users/apple/Documents/software/apache-tomcat-8.5.24/bin/catalina.sh stop
26-Feb-2018 17:54:03.192 信息 [main] org.apache.catalina.core.StandardServer.await A valid shutdown command was received via the shutdown port. Stopping the Server instance.
26-Feb-2018 17:54:03.192 信息 [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8081"]
26-Feb-2018 17:54:03.251 信息 [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["ajp-nio-53733"]
26-Feb-2018 17:54:03.305 信息 [main] org.apache.catalina.core.StandardService.stopInternal Stopping service [Catalina]
26-Feb-2018 17:54:03.317 警告 [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [DubboResponseTimeoutScanTimer] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.dubbo.remoting.exchange.support.DefaultFuture$RemotingInvocationTimeoutScan.run(DefaultFuture.java:296)
 java.lang.Thread.run(Thread.java:748)
26-Feb-2018 17:54:03.330 信息 [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-8081"]
26-Feb-2018 17:54:03.331 信息 [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["ajp-nio-53733"]
26-Feb-2018 17:54:03.332 信息 [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-8081"]
26-Feb-2018 17:54:03.333 信息 [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["ajp-nio-53733"]

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "DubboZkclientConnector-EventThread"

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "DubboZkclientConnector-SendThread(192.168.0.109:2181)"
Disconnected from server

PLEASE HELP!!!!!!!

**Comment by beiwei30** [comment]
This message can be simply ignored. It's usually happened when one class is tried to load after tomcat's classloader gets closed when server shuts down.
