### ISSUE TITLE
debug info containing "dubboserverhandler" keeps printing on console

### ISSUE THREAD

**Issue by imxig** [alibaba/dubbo#1404]
请问一下，如何解决控制台一直打印dubboserverhandler???
如：[DubboServerHandler-x.x.x.x:20881-thread-193] DEBUG org.mybatis.spring.SqlSessionUtils.........

**Comment by beiwei30** [comment]
DubboServerHandler-x.x.x.x:20881-thread-193 is thread name, check your application's log level. Your current level is DEBUG

**Comment by imxig** [comment]
my application's log level is not DEBUG，mycurrent level is INFO
