### ISSUE TITLE
How to disable qos or change qos port in XML config file ?

### ISSUE THREAD

**Issue by ldcsaa** [alibaba/dubbo#1410]
我的一台机器运行多个dubbo服务进程，它们共用一个固定的 dubbo.properties 文件，用于配置注册中心等全局配置信息。
在每个应用程序内部则使用 dubbo XML 配置文件来配置服务提供者（或消费者）的私有配置信息（如dubbo端口）。
但升级到2.6.0后碰到问题了，如果qos端口只能在dubbo.properties 文件中配置，多个服务启动时肯定会造成端口冲突。请问有没有办法在XML配置文件中修改qos端口或禁止qos？？？

**Comment by chickenlj** [comment]
You can use JVM properties: `-Ddubbo.qos.enable=false`

**Comment by xiaoniutect** [comment]
2.6.2是这样的：在配置文件里面`dubbo.application.qos-enable = false`或者JVM启动参数：`-Ddubbo.application.qosEnable=false`

**Comment by steveguoshao** [comment]
在2.6.2版本是这样设置的
配置文件：`dubbo.application.qos-enable = false`  或者  `dubbo.application.qosEnable = false`，如果是Spring Boot环境，以上两种都支持，如果是非Spring Boot环境，则只支持第二种
设置JVM启动参数：`-Ddubbo.application.qosEnable = false`

**Comment by newpanjing** [comment]
直接设置环境变量也可以

` public static void main(String[] args) {

        System.setProperty("dubbo.qos.port", "22223");
        SpringApplication.run(ApiApplication.class, args);
    }`
