### ISSUE TITLE
Hope "dubbo:consumer" add "url" property, so we can set default url for all services .

### ISSUE THREAD

**Issue by ananas-hebo** [alibaba/dubbo#1414]
类似:
`<dubbo:consumer url="10.0.6.158:30019"/>`

因测试需要，需要将全部请求指定到某个provider上去。

**Comment by limingwei** [comment]
用一个专门配置的 group 或 version 或 registry 能不能满足需要？

**Comment by chickenlj** [comment]
@ananas-hebo, i think limingwei's suggestion can meet your requirement.

**Comment by ananas-hebo** [comment]
@limingwei @chickenlj 
如果单独配置group和version，是不是需要修改服务端的配置？
