### ISSUE TITLE
Failed to specify ip use dubbo:protocol.host.

### ISSUE THREAD

**Issue by huangxincheng** [alibaba/dubbo#1415]
服务器的 /etc/hosts 文件指定的机器码是 内网地址，但是有需求我们改  /etc/hosts文件里面的内容
想要早dubbo.xml 修改 host为外网地址 发现 一直提示绑定端口失败

**Comment by s614053620** [comment]
是要在外网发布dubbo服务吗？

**Comment by chickenlj** [comment]
Hi, welcome to Dubbo community!

Please consider using English, Dubbo is a global community, and all the issues may be viewed and discussed by people all over the world.

Meanwhile, you can send email to dev@dubbo.apache.org or subscribe it, which is preferred way for discussing questions like this. And we will make sure that every email will receive a reply.

Github issues should be a pure place for tracking determined `features`, `enhancements` or  `bugs`.

**Comment by chickenlj** [comment]
Please send your full exception stack to  dev@dubbo.apache.org  and [subscribe to it](https://github.com/alibaba/dubbo/issues/1393) to receive any discussions.
