### ISSUE TITLE
dubbo-maven is deleted  ?

### ISSUE THREAD

**Issue by changealice** [alibaba/dubbo#1416]
i download dubbo version 2.6.0 from mvnrepository.com ,maven pom.xml use 
```<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo</artifactId>
            <version>2.6.0</version>
        </dependency>
```

open dubbo-2.6.0.jar/META-INF/maven/com.alibaba/dubbo/pom.xml
```
<dependency>
            <groupId>org.apache.mina</groupId>
            <artifactId>mina-core</artifactId>
            <version>1.1.7</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.grizzly</groupId>
            <artifactId>grizzly-core</artifactId>
            <version>2.1.4</version>
            <scope>provided</scope>
        </dependency>
```
 jar scope is provider ,
i git checkout master branch and manual exec 

```mvn clean install -DskipTests ```

open local dubbo/all/target/dubbo-2.6.1.jar/META-INF/maven/com.alibaba/dubbo/pom.xml

```
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo-cluster</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>

```
why maven scope seem diff

and i'm git checout branch 2.5.x  find it's config in sub module ``` dubbo-maven ``` 
current master branch it's delete  ?
how i build dubbo.jar myself ?

**Comment by chickenlj** [comment]
First, pull `master` branch again, see if you have the latest changes we have made.

`dubbo-maven` module has been deleted in 2.6.x. It is used for central repository deploy.
Now, you execute `mvn clean install -DskipTests` on root directory, all packages will be packaged properly.

**Comment by chickenlj** [comment]
We recommend you send email to dev@dubbo.apache.org or subscribe it, which is preferred way for discussing questions like this.
