### ISSUE TITLE
application.yml doesn't support dubbo.protocol.port: 12346 （BUG）

### ISSUE THREAD

**Issue by jiaopy** [alibaba/dubbo#1418]
在yml中dubbo.protocol.port的配置，修改端口号后还是取的默认的
在application.properties中配置就没事

**Comment by beiwei30** [comment]
pls. attach a test case to reproduce the problem.

**Comment by lovepoem** [comment]
Duplicate of alibaba/dubbo#1399

It is fixed in alibaba/dubbo#1401 ，will be released in next version

**Comment by jiaopy** [comment]
About what time?

**Comment by chickenlj** [comment]
@jiaopy Please subscribe to  dev@dubbo.apache.org, release plans will be published here.

**Comment by jiaopy** [comment]
thanks
