### ISSUE TITLE
关于README的介绍翻译问题

### ISSUE THREAD

**Issue by Theo1016** [alibaba/dubbo#142]
Dubbo is a distributed service framework enpowers applications with service import/export capability with high performance RPC.

其中，enpowers这个词应该是用错了吧，完全没查到这个词有任何意义，这里应该用 be committed to之类的吧

**Comment by henrywhy** [comment]
显然是单词拼写错了，是empower

**Comment by henrywhy** [comment]
已提交pull request，等待合并
