### ISSUE TITLE
Problems with zookeeper registry migration.

### ISSUE THREAD

**Issue by ygypc** [alibaba/dubbo#1420]
上周运维同学把zookeeper服务器换物理机了，数据全没有了，dubbo没有重新注册服务，重启就好了，象这种情况是一定要重启业务系统吗还是有配置？

**Comment by kimmking** [comment]
dubbo不知道你的新zk在哪儿呀

**Comment by chickenlj** [comment]
Hi ygypc,

Please consider using English, Dubbo is a global community, and all the issues may be viewed and discussed by people all over the world.

Meanwhile, you can send any question to dev@dubbo.apache.org to discuss questions like this, we highly recommend you subscribe to dev@dubbo.apache.org to receive any discussions and news of dubbo. And we will make sure that every email will receive a reply.

Github issues should be a pure place for tracking determined features, enhancements or bugs.
