### ISSUE TITLE
how to close telnet

### ISSUE THREAD

**Issue by thanks0rf** [alibaba/dubbo#1433]
如何通过配置关闭相关telnet命令(ls invoke等)?

**Comment by liangfei0201** [comment]
filter="-telnet"，注意“-”号

2018-03-08 10:54 GMT+08:00 thanks0rf <notifications@github.com>:

**Comment by beiwei30** [comment]
feel free to reopen if @liangfei0201's suggestion doesn't work.

**Comment by moyuqingxin** [comment]
请问filter="-telnet"是在哪里设置呢，dubbo version 2.5.3
