### ISSUE TITLE
dubbo以 spring-boot方式启动飞得同时启动一个内嵌的web容器吗？

### ISSUE THREAD

**Issue by githubxingyuntian** [alibaba/dubbo#1436]
对于一个单纯的rpc应用来说，其实很多时候根本用不着web呀啊，我们只想用spring-容器管理对象，同时用spring-boot打包。每个应用都平白无故的多占用一个tcp端口。

**Comment by LiJohnson** [comment]
可以不用web窗容器，不过让它以服务的形式一直跑，要另外加些代码。

```java
@SpringBootApplication
@EnableScheduling
public class Application  {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
	@Scheduled(fixedDelay = 100000)
	public void keepRunning() {}
}
```

**Comment by githubxingyuntian** [comment]
good，这样是可以，能简单说一下，如果不这样，为什么进程会被杀掉呢？我们不是用netty起了个tcp-socket吗？理解的不太透彻，能说一下吗？

**Comment by foreveryang321** [comment]
@SpringBootApplication
@DubboComponentScan(basePackages = {"x.xx.xxx.xxxx"})
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application .class, args);
        synchronized (Application .class) {
            while (true) {
                try {
                    Application .class.wait();
                } catch (Exception e) {
                    e.printStackTrace();
                    break;
                }
            }
        }
    }
}

**Comment by mercyblitz** [comment]
Non-Web Spring Boot Application is not blocking bootstrap , thus developer have to wait by some code

**Comment by githubxingyuntian** [comment]
understand ,thanks，help very much
