### ISSUE TITLE
能不能零配置文件结合spring boot实现客户端？

### ISSUE THREAD

**Issue by Dreampie** [alibaba/dubbo#144]

**Comment by shevawen** [comment]
关注此issue

**Comment by xiaozhen57520** [comment]
已经在项目中使用spring-boot零配置使用dubbo,也遇到一些问题和内部争议,希望有经验的一起讨论。邮箱xiaozhen57520@126.com.

**Comment by Dreampie** [comment]
@xiaozhen57520 希望共享出来  大家一起讨论一下

**Comment by xiaozhen57520** [comment]
@Dreampie 好的，我整理下，共享出来。

**Comment by qibaoguang** [comment]
@Dreampie 可以参考下这个项目 https://github.com/Percy0601/boot-dubbo，Spring boot结合dubbox

**Comment by Dreampie** [comment]
看过了  有xml，没有xml的好像是个rest的  我需要一个只注解就能像普通客户端使用的方式  rest
也不需要

**Comment by happyiwin** [comment]
关注下，提个问题：我现在的项目里引用的是spring4, dubbo里面怎样配置可以支持的？我发现dubbo里面是spring2.5, 里面的jdkversion支持到java7, 项目里面是java8，启动出错，怎么解决的。请教下。

**Comment by wuwen5** [comment]
@happyiwin 我们线上环境就是用的spring4.1.7 dubbo2.5.3
只需要排除掉dubbo的spring依赖
```xml
<dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>dubbo</artifactId>
                <version>${dubbo.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.springframework</groupId>
                        <artifactId>spring</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.jboss.netty</groupId>
                        <artifactId>netty</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
```

**Comment by happyiwin** [comment]
@wuwen5 采用了你的配置，项目run起来了。非常感谢。

**Comment by visionwang** [comment]
mark这个issue

**Comment by majinkai** [comment]
我们的项目都是无任何xml的，但是dubbo有点问题，需要改动一点源码才可以，dubbox已经修复了

**Comment by justein** [comment]
dubbo目前正在摸索学习中，还是要从RPC开始看起，以前不怎么搞分布式的

**Comment by Dreampie** [comment]
spring boot 结合 spring cloud config 远程配置的方式 非常好用，建议维护人员 尽快提供一个  我觉得对dubbo的发展会极大的有利

**Comment by zouchunhui** [comment]
mark一下。

**Comment by lovepoem** [comment]
please see this official project https://github.com/dubbo/dubbo-spring-boot-project
