### ISSUE TITLE
Dubbo配置threads线程池大小后，线程编号不断叠加直到最大值。并且thead_blocked

### ISSUE THREAD

**Issue by hank0chan** [alibaba/dubbo#1455]
使用dubbo在服务提供者端配置了theads参数为2048，然后应用正常提供服务。日志显示DubboServerHandler的线程池编号是一直增大的，并且在运行一段时间（大概3天）后，应用挂了，报错OutOfMemoryError，通过dump信息看到线程池似乎一直处在thread_blocked状态，并且不断叠加，导致异常。请问可能是哪方面的原因？
-------------------------------------------------------------------------------

---------------  T H R E A D  ---------------

Current thread (0x0000000014f39800):  VMThread [stack: 0x0000000016c20000,0x0000000016d20000] [id=56868]

Stack: [0x0000000016c20000,0x0000000016d20000]
[error occurred during error reporting (printing stack bounds), id 0xc0000005]

Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)

VM_Operation (0x000000004630e500): BulkRevokeBias, mode: safepoint, requested by thread 0x000000001c235000
---------------  P R O C E S S  ---------------
Java Threads: ( => current thread )
  0x00000000185bc800 JavaThread "DubboServerHandler-114.55.150.158:30001-thread-2048" daemon [_thread_blocked, id=25184, stack(0x000000006cec0000,0x000000006cf40000)]
  0x00000000185bb000 JavaThread "DubboServerHandler-114.55.150.158:30001-thread-2047" daemon [_thread_blocked, id=9668, stack(0x000000006ce40000,0x000000006cec0000)]
  0x00000000185b6800 JavaThread "DubboServerHandler-114.55.150.158:30001-thread-2046" daemon [_thread_blocked, id=68976, stack(0x000000006cdc0000,0x000000006ce40000)]
  0x00000000185b9800 JavaThread "DubboServerHandler-114.55.150.158:30001-thread-2045" daemon [_thread_blocked, id=51120, stack(0x000000006cd40000,0x000000006cdc0000)]
  0x00000000185b8800 JavaThread "DubboServerHandler-127.0.0.1:30001-thread-2044" daemon [_thread_blocked, id=69100, stack(0x000000006cfc0000,0x000000006d040000)]
  0x00000000185b8000 JavaThread "DubboServerHandler-127.0.0.1:30001-thread-2043" daemon [_thread_blocked, id=40044, stack(0x000000006cf40000,0x000000006cfc0000)]
  0x00000000185b4000 JavaThread "DubboServerHandler-127.0.0.1:30001-thread-2042" daemon [_thread_blocked, id=39416, stack(0x000000006ccc0000,0x000000006cd40000)]
  0x00000000185b5000 JavaThread "DubboServerHandler-127.0.0.1:30001-thread-2041" daemon [_thread_blocked, id=51748, stack(0x000000006cc40000,0x000000006ccc0000)]
  0x00000000185b7000 JavaThread "DubboServerHandler-127.0.0.18:30001-thread-2040" daemon [_thread_blocked, id=36968, stack(0x000000006c7c0000,0x000000006c840000)]
  0x00000000185b3800 JavaThread "DubboServerHandler-127.0.0.1:30001-thread-2039" daemon [_thread_blocked, id=72776, stack(0x000000006c740000,0x000000006c7c0000)]
  0x00000000185b5800 JavaThread "DubboServerHandler-127.0.0.1:30001-thread-2038" daemon [_thread_blocked, id=14716, stack(0x000000006c6c0000,0x000000006c740000)]
  0x00000000185af800 JavaThread "DubboServerHandler-127.0.0.1:30001-thread-2037" daemon [_thread_blocked, id=21636, stack(0x000000006c640000,0x000000006c6c0000)]
  0x00000000185b2800 JavaThread "DubboServerHandler-127.0.0.1:30001-thread-2036" daemon [_thread_blocked, id=57580, stack(0x000000006cbc0000,0x000000006cc40000)]
  0x00000000185af000 JavaThread "DubboServerHandler-127.0.0.1:30001-thread-2035" daemon [_thread_blocked, id=69596, stack(0x000000006cb40000,0x000000006cbc0000)]
  0x00000000185b0800 JavaThread "DubboServerHandler-127.0.0.1:30001-thread-2034" daemon [_thread_blocked, id=12104, stack(0x000000006cac0000,0x000000006cb40000)]
  0x00000000185b2000 JavaThread "DubboServerHandler-127.0.0.1:30001-thread-2033" daemon [_thread_blocked, id=12632, stack(0x000000006ca40000,0x000000006cac0000)]

**Comment by kimmking** [comment]
can you submit some details log, such as jstack and jvm options.

**Comment by hank0chan** [comment]
我想我知道为什么了
