### ISSUE TITLE
application.yml doesn't support dubbo.protocol.port:  12345 (BUG)

### ISSUE THREAD

**Issue by jiaopy** [alibaba/dubbo#1462]
in dubbo-spring-boot-sample-provider <version>0.1.0</version>
i alter application.properties to application.yml
then i find dubbo.protocol.port: 12345 is not supported ,the port will be 20880

**Comment by lovepoem** [comment]
Duplicate of https://github.com/alibaba/dubbo/issues/1399

It is fixed in https://github.com/alibaba/dubbo/pull/1401   ，will be released in v2.6.1
