### ISSUE TITLE
.yml file. "dubbo.registries.xx.address"  don't work.

### ISSUE THREAD

**Issue by lovefit** [alibaba/dubbo#1481]
I want to configure multiple registry centers
Referring to the "[Auto-Configure](https://github.com/apache/incubator-dubbo-spring-boot-project/tree/master/dubbo-spring-boot-autoconfigure)" document, I found this configuration:
`dubbo.registries.registry1.address = zookeeper://192.168.99.100:32770`
So in my project:

dubbo:
  registries:
    xxxx:
      protocol: zookeeper
      address: @dubbo.xxxx.address@
      client: zkclient
      group: xxxx

But it doesn't work.
See `DubboRegistryFactory.getRegistries();` size 0.

Finally, I configure it like this:

dubbo:
  config:
    multiple: true
  registry:
    xxxx:
      protocol: zookeeper
      address: @dubbo.xxxx.address@
      client: zkclient
      group: xxxx

Succeed。
See `DubboRegistryFactory.getRegistries();` size 1.

Version: dubbo 2.6.0 springboot 1.5.8
I have wasted a long time. 
I want to know why, how to use the ‘registries’ in document.
Which document I should look at on this question.

**Comment by lovepoem** [comment]
You can see https://github.com/alibaba/dubbo/pull/1401

 dubbo 2.6.1 has fixed this bug

**Comment by lovefit** [comment]
OK,Thank you!
