### ISSUE TITLE
返回结果是泛型的接口，consumer取到的对象属性全是null

### ISSUE THREAD

**Issue by linminqin** [alibaba/dubbo#155]
接口如下：
```
public <T extends BasePojo> T find(Class<T> pojoClass, Long id);
```
实际的返回结果是一个子类，调试发现属性全部都是null

**Comment by yinheli** [comment]
能不能贴多一点代码以及测试? 

每个人都很懒, 不利于解决问题

**Comment by linminqin** [comment]
不好意思啊，在别的论坛贴了代码跟配置文件，在这里忘记贴了，后来我自己找到原因了，是因为我mybatis开启懒加载，所以接口返回的是代理对象，dubbo是不是无法序列化代理对象，我关掉懒加载之后就没问题了
