### ISSUE TITLE
Log system flaw?

### ISSUE THREAD

**Issue by vongosling** [alibaba/dubbo#17]
I can not swith log4j to logback.
After exclude log4j dependency and add logback-classic,it reports such warnings;
log4j:WARN No appenders could be found for logger (com.alibaba.dubbo.common.logger.LoggerFactory).

Why not follow the slfj standard , but develop another log module?

**Comment by wangjingfei** [comment]
I've met the same problem. My whole project uses logback for logging, but dubbo's introduing log4j breaks everything down...

**Comment by teaey** [comment]
We will to consider using slf4j as the standard log framework。
