### ISSUE TITLE
Dubbo Injvm协议会导致异步调用失效

### ISSUE THREAD

**Issue by luoyan35714** [alibaba/dubbo#175]
原先的注册中心和协议是ZK和Dubbo,现在改成multicast和injvm之后发现异步调用都失效了，变成了同步。

**Comment by patternman** [comment]
InjvmInvoker里我没看到读取timeout和使用future去做异步调用，没理解错的话 Injvm协议下 异步是失效的。

**Comment by luoyan35714** [comment]
public Result doInvoke(Invocation invocation) throws Throwable {
        Exporter<?> exporter = InjvmProtocol.getExporter(exporterMap, getUrl());
        if (exporter == null)  {
            throw new RpcException("Service [" + key + "] not found.");
        }
        RpcContext.getContext().setRemoteAddress(NetUtils.LOCALHOST, 0);
        return exporter.getInvoker().invoke(invocation);
    }
确实没有。。非常感谢，提醒了下去看了看源码
