### ISSUE TITLE
项目有多个ClassLoad时使用dubbo出错；

### ISSUE THREAD

**Issue by violetgo** [alibaba/dubbo#178]
在项目中使用pf4j来做插件框架；dubbo的客户端被作为插件使用；
dubbo依赖文件及接口定义均被加载到pf4jClassLoad内；
然后调用duboo就会有如下提示；

![image](https://cloud.githubusercontent.com/assets/5086059/11290961/4fdd4924-8f76-11e5-81d8-7fdd58c3d174.png)

图中所示，dubbo在映射接口时使用的classload实际为systemload；
不知是否为bug?

**Comment by teaey** [comment]
调用dubbo前，调用Thread.currentThread().setContextClassLoader，设置ccl为pf4j的classload即可

**Comment by oldratlee** [comment]
:+1: @teaey

**Comment by teaey** [comment]
@oldratlee 前辈:smile:

**Comment by violetgo** [comment]
@teaey 在dubbo调用完成后是否还要在设置回来？

**Comment by teaey** [comment]
@violetgo 看你的需求
