### ISSUE TITLE
DubboMonitorFactroy spelling

### ISSUE THREAD

**Issue by sgwerder** [alibaba/dubbo#190]
I guess it should be "DubboMonitorFactory" instead of "DubboMonitorFactroy"

https://github.com/alibaba/dubbo/blob/master/dubbo-monitor/dubbo-monitor-default/src/main/java/com/alibaba/dubbo/monitor/dubbo/DubboMonitorFactroy.java

**Comment by Liuxboy** [comment]
yeah, it's a spelling mistake

**Comment by javahongxi** [comment]
oo, low mistake

**Comment by lovepoem** [comment]
fixed
