### ISSUE TITLE
Would anyone please tell me why we must throw an IllegalStateException when the named bean already exist?

### ISSUE THREAD

**Issue by soiff** [alibaba/dubbo#193]
Can we just return the existing BeanDefinition instead of throw an exception?

**Comment by 383124397** [comment]
what kind of exception? if it's a RuntimeException, we should let it go or not a Bean, do you get the point?

**Comment by teaey** [comment]
But, you declare a dubbo service bean , dubbo cant return a normal service instate of dubbo service bean.

**Comment by soiff** [comment]
@383124397 At this point, that's right. However, not all RuntimeException are fatal!

@teaey I just want to de-weight the same service bean automatically (eg, with same interface, version, group,etc) if declaration of a service bean repeatedly included.
