### ISSUE TITLE
Maven依赖找不到

### ISSUE THREAD

**Issue by IamFive** [alibaba/dubbo#21]
RT，opensesame的包无法下载，[Maven][http://repo1.maven.org/maven2/com/alibaba/] 中也无法找到对应的包，下的dubbo项目无法编译。

``` xml
    <parent>
        <groupId>com.alibaba</groupId>
        <artifactId>opensesame</artifactId>
        <version>2.0</version>
    </parent>
```

**Comment by nyzoupu** [comment]
@lishunli 那个master的链接失效了吗，怎么打不开页面

**Comment by lishunli** [comment]
@nyzoupu 
嗯，已经失效，重新上传一份
alibaba-dubbo-dependency.zip

**Comment by lishunli** [comment]
@nyzoupu 
嗯，已经失效，重新上传了一份
[alibaba-dubbo-dependency.zip](https://github.com/alibaba/dubbo/files/310085/alibaba-dubbo-dependency.zip)

**Comment by zouchunhui** [comment]
mark.

**Comment by cuisongliu** [comment]
我build的时候也发现了 大家可以设置maven仓库链接到 http://maven.cuisongliu.com/content/groups/public 我已经上传了opensesame的pom到中央仓库。
