### ISSUE TITLE
code.alibabatech.com不能访问了，是阿里不让用了吗

### ISSUE THREAD

**Issue by ghost** [alibaba/dubbo#22]
http://code.alibabatech.com/wiki/display/dubbo
不能访问，我还有好多dubbo的配置要去查呢，怎么办？

**Comment by zhangyijun** [comment]
你好，过程中的Repository都已经不可用了。mirror（http://mirrors.ibiblio.org/maven2/com/alibaba/）虽然可用，但是缺少许多包，目前完全无法构建。
1 opensesame 缺少，可用通过github上的库手工解决。OK
2 fastjson_version问题，可以参考前面意见，使用更新的版本1.1.38例如。OK
3 hessian lite完全找不到
暂时卡在这里无法继续，也请能给予帮助，谢谢

**Comment by JDFISH** [comment]
Connect to maven.kafeitu.me:80 [maven.kafeitu.me/120.25.228.112] failed: Connection refused

额是我这边墙太高了吗

**Comment by nyzoupu** [comment]
貌似#21 添加的mirror现在好像都不可用了，所以master的依赖包，仍然无法下载，有谁可以分享下吗

**Comment by beiwei30** [comment]
not an issue any longer
