### ISSUE TITLE
dubbo monitor ip调用次数统计问题

### ISSUE THREAD

**Issue by chenliufei** [alibaba/dubbo#232]
昨天在dubbo监控的ip调用次数统计页面发现某服务中许多不明ip的调用， 经排查这些ip是在某服务中调用的另外一个服务的提供者的ip。 也就是说 A invoke B, B invoke C, 这时候在B的调用次数统计页面会显示C调用了B。  在MonitorFilter源码中发现ip是通过 context.getRemoteHost()获得的， 由于RpcContext是临时记录了最近一次调用的上下文信息，那就可以解释ip统计的问题了。  目前还不确定是使用配置问题还是dubbo问题，  请教一下， 同学们没有遇到过这个问题吗？ 是怎么解决的？

**Comment by chickenlj** [comment]
RpcContext中的上下文信息，在每次rpc调用后都会更新：http://dubbo.io/user-guide/demos/%E4%B8%8A%E4%B8%8B%E6%96%87%E4%BF%A1%E6%81%AF.html

`
if (Constants.CONSUMER_SIDE.equals(invoker.getUrl().getParameter(Constants.SIDE_KEY))) {
                // ---- 服务消费方监控 ----
                context = RpcContext.getContext(); // 消费方必须在invoke()之后获取context信息
                localPort = 0;
                remoteKey = MonitorService.PROVIDER;
                remoteValue = invoker.getUrl().getAddress();
            } else {
                // ---- 服务提供方监控 ----
                localPort = invoker.getUrl().getPort();
                remoteKey = MonitorService.CONSUMER;
               //FIXME 这里的地址可能已经被后面的调用链更新了
                remoteValue = context.getRemoteHost();
            }
`
