### ISSUE TITLE
Dubbo-Admin在Zookeeper注册中心不使用默认的根目录的时候无法获取到服务

### ISSUE THREAD

**Issue by BadSmile01** [alibaba/dubbo#237]
因为公司还有其他项目使用zookeeper，所以我们的dubbo不能使用根目录，我们自定义了一个目录：
`<dubbo:registry group="tccarInnovation" 其他配置省略 />`
这样我们在服务提供方和服务消费方都正确使用了，然后配置monitor的时候，在配置文件中增加了一行
`dubbo.registry.group=tccarInnovation`
然后monitor也能正确统计套服务数据，但是dubboadmin却怎么也不行，在配置文件里面增加了一行上面的配置，还是不行，不知道是什么原因？有大神遇到过吗？

**Comment by BadSmile01** [comment]
已经解决了，下载了dubboAdmin的源码，发现他里面的dubbo-admin.xml里面的
<dubbo:registry address="${dubbo.registry.address}"  check="false" file="false" />配置中没有配置group，所以自己加了一个就好了，修改后的结果如下：
已经解决了，下载了dubboAdmin的源码，发现他里面的dubbo-admin.xml里面的
<dubbo:registry address="${dubbo.registry.address}" group="${dubbo.registry.group}" check="false" file="false" />

**Comment by BadSmile01** [comment]
已经解决了，下载了dubboAdmin的源码，发现他里面的dubbo-admin.xml里面的
<dubbo:registry address="${dubbo.registry.address}"  check="false" file="false" />配置中没有配置group，所以自己加了一个就好了，修改后的结果如下：
已经解决了，下载了dubboAdmin的源码，发现他里面的dubbo-admin.xml里面的
<dubbo:registry address="${dubbo.registry.address}" group="${dubbo.registry.group}" check="false" file="false" />

**Comment by gMan1990** [comment]
dubbo.properties
```properties
dubbo.registry.address=zookeeper://127.0.0.1:2181?group= tccarInnovation
```
