### ISSUE TITLE
dubbo路由问题

### ISSUE THREAD

**Issue by huapuyu** [alibaba/dubbo#238]
想根据方法对dubbo调用进行路由，发现不行，例如
getById走provider A
save走provider B

然后想对路由进行扩展
但根据官网的开发指南，发现也不行

不知道dubbo的路由功能是不是没有完全开源，谢谢！

**Comment by oldratlee** [comment]
> 不知道dubbo的路由功能是不是没有完全开源

**Comment by orika** [comment]
@huapuyu 路由规则应该是按照IP配置的，应该做不到接口级别

**Comment by wuqqq** [comment]
@huapuyu ，ConditionRouter应该不支持method级别的，因为url中没有method参数，只有methods参数列出了接口的所有method，可以试试ScriptRouter，从invocation中获取consumer调用的method

**Comment by EdwardLee03** [comment]
@huapuyu  路由规则可以实现读写分离
![b90990cf-77d6-4ee8-bab8-9c4a2447bd45](https://user-images.githubusercontent.com/1811851/32313637-e018c23a-bfde-11e7-9c19-c0086f9b21d0.png)
