### ISSUE TITLE
请问Consumer和Provider有启动顺序要求么

### ISSUE THREAD

**Issue by luoyan35714** [alibaba/dubbo#251]
请问Consumer和Provider有启动顺序要求么？我先启动Consumer，然后启动Provider，一直报找不到Provider。我的理解是每次发送请求都会去注册中心寻找，不应该有这种问题啊。注册中心用的Zookeeper。

**Comment by afredlyj** [comment]
这个是可以通过配置修改的，具体说明可以参考文档[启动时检查](http://dubbo.io/Check+On+Startup-zh.htm)。

**Comment by luoyan35714** [comment]
嗯~问题解决，多谢了！！！
