### ISSUE TITLE
按照readme不能成功编译

### ISSUE THREAD

**Issue by teager** [alibaba/dubbo#27]
在执行mvn eclipse：eclipse 命令的时候很多包下载不到
com.alibaba:hessian-lite:jar:3.2.1-fixed-2
 com.alibaba:fastjson:jar:1.1.8
.....
http://code.alibabatech.com 网站关闭了，什么时候会有更新。

**Comment by beiwei30** [comment]
not an issue any longer

**Comment by indie21** [comment]
最新的tag dubbo-2.5.3 又访问
to {}->http://code.alibabatech.com:80: SOCKS: Network unreachable
了。

**Comment by indie21** [comment]
神奇的切换到master又成功了
