### ISSUE TITLE
管理后台禁用服务提供者不成功

### ISSUE THREAD

**Issue by yutian** [alibaba/dubbo#28]
在后台禁用服务提供者，消费者依然能请求，而且服务者依然能工作
![35081-b458dc43eca3c9a9ddf16e70359449f6](https://f.cloud.github.com/assets/1321293/2270494/249e3004-9eee-11e3-954c-e0163711502c.jpg)

消费者依然能正常请求:如下图:
![35821-156d66fdbae3b42b13e99a6b94e90058](https://f.cloud.github.com/assets/1321293/2270500/3d8f6a1a-9eee-11e3-8eae-72afcaebb941.jpg)

**Comment by bylijinnan** [comment]
如 ronaldoliubo  所说，当只有一个服务提供者时，禁用是不起作用的；但如果有两个服务提供者，则可以成功禁用其中一个；禁用了一个以下，剩下的这个服务提供者再禁用，就不起作用了

**Comment by justein** [comment]
事实情况是即便有多个服务，仍然也禁用不了

**Comment by it-noob** [comment]
@justein 多个服务是可以禁用的

**Comment by caiqien** [comment]
我这边试过了，多个提供者服务也是禁用不了的。禁用之后仍然可以访问到服务
