### ISSUE TITLE
 请问这个项目还在升级、维护吗？

### ISSUE THREAD

**Issue by wangjia2016** [alibaba/dubbo#316]
请问这个项目还在升级、维护吗？

**Comment by zsyubo** [comment]
现在基本没有大更新了吧,偶尔有下小更新,主要dubbo现在稳定了,至于rest,用dubbox, ,不过如果很介意的话可以试下cloud,

**Comment by bwzhang2011** [comment]
cloud是什么, spring cloud麽。

**Comment by xiruibing** [comment]
现在不太维护了，阿里已经不用这个了

**Comment by lvkai** [comment]
阿里在用。

2016-10-28 13:25 GMT+08:00 Ruibin Xi <notifications@github.com>:

**Comment by xuhuisheng** [comment]
Spring Cloud靠谱

**Comment by oldratlee** [comment]
@xiruibing 呃，这位同学是阿里的么，如果是可以问问阿里的不同bu，在用的，具体我不说了。如果不是，呃……😖
