### ISSUE TITLE
dubbo_admin 访问404问题

### ISSUE THREAD

**Issue by zhengsh** [alibaba/dubbo#382]
ide: sts 
系统：win10 
web容器：tomcat
访问 ：http://localhost:8080/dubbo-admin

返回404

**Comment by niweicumt** [comment]
应用没部署好吧，你的tomcat的webapps目录下看看有没有dubbo-admin目录，内部是不是一个web项目格式。

**Comment by zhengsh** [comment]
我打的war 包有问题，重新打个war包又可以了

**Comment by takeseem** [comment]
@zhengsh 既然没有问题了就关闭问题吧
