### ISSUE TITLE
注册中心选用zookeeper好还是redis好

### ISSUE THREAD

**Issue by 15174834** [alibaba/dubbo#418]
注册中心选用zookeeper好还是redis好

**Comment by yunhaibin** [comment]
个人认为Zookeeper稳定一些，使用Zookeeper集群部署方式保证高可用，性能方面也不用特别担忧

**Comment by 15174834** [comment]
因为之前zookeeper老是挂掉，所有有点害怕，而现在redis用的是阿里云的，不担心宕机，所以，我有这个疑惑。

**Comment by yunhaibin** [comment]
Zookeeper还能经常挂掉。。。。我们线上3个Zookeeper集群已经稳定运行2年多了，从没出现挂掉的现象，最多就是有时候网络抖动，线上消费服务1200多个，提供服务300多个

**Comment by 15174834** [comment]
确实挂了，3台SSD ECS ，16U64G，并发一千多万个节点。。。 100G磁盘满了，所以挂掉了

**Comment by yunhaibin** [comment]
1000多万个节点？？？？？？你们哪能有这么多消费方和提供方？

**Comment by 15174834** [comment]
不光是给dubbo用，程序里再用，做协调用的

**Comment by yunhaibin** [comment]
你们对Zookeeper用的够扎实啊，Zookeeper在性能上不是特别好，不太了解你们的业务
个人建议：
1、换掉Zookeeper，看看Go实现的Etcd性能如何，Go在这方面还是表现不错；
2、扩展Zookeeper集群，横向提升性能；

**Comment by 15174834** [comment]
小弟在此多谢

**Comment by yunhaibin** [comment]
@15174834 客气了，互相学习
