### ISSUE TITLE
给monitor设计提个建议

### ISSUE THREAD

**Issue by mjaow** [alibaba/dubbo#422]
很多公司在使用dubbo的时候会很重视monitor，但是现在simple-monitor统计的东西太粗略，比如平均rt，非常不精确。很多时候没办法定位问题。

建议加上统计rt分布的功能，比如抽样收集1000个rt，算出99%的在哪个区间，90%的在哪个区间，这样对系统监控能力更清晰

**Comment by yunhaibin** [comment]
@mjaow 可以根据个人需要去扩展monitor的功能，dubbo自身的monitor功能非常简单，实现的功能比较简单，你可以看看这个项目[dubbokeeper](https://github.com/dubboclub/dubbokeeper)

**Comment by mjaow** [comment]
@yunhaibin 确实，公司在用dubbo的时候发现monitor太过简单，没办法满足需求，就只能自己改造了
