### ISSUE TITLE
抛Null异常【忽略】

### ISSUE THREAD

**Issue by shuohao** [alibaba/dubbo#459]
![qq 20170616152802](https://user-images.githubusercontent.com/4637107/27216458-6dfce706-52a8-11e7-9db3-7193141840fb.png)
调用dubbo服务，客户端抛这个异常，这个是什么问题啊，dubbo服务端服务正常

**Comment by shuohao** [comment]
奇怪的是DefaultFuture.java 34行是个import

**Comment by lipenglong24** [comment]
我也遇到了相同的问题，生产环境dubbo的版本是2.4.5，过一段时间就出现了这样的问题，重启客户端就没问题了，现在问题解决了吗？

**Comment by shuohao** [comment]
因为用了听云做监控，是听云的问题，听云对dubbo这个模块儿重写了

**Comment by lipenglong24** [comment]
你这么一说还真是。。。我们的项目也加了听云的监听，但是我没想到会跟听云的监听有关系，一直在代码和dubbo上面寻找原因，现在想想加听云的监听前，这个异常还真没出现过

**Comment by oldratlee** [comment]
> @shuohao
> 因为用了听云做监控，是听云的问题，听云对dubbo这个模块儿重写了

Close了
