### ISSUE TITLE
tomcat lib javassist

### ISSUE THREAD

**Issue by qq331077064** [alibaba/dubbo#46]
部署dubbo的provider在tomcat下,把所有需要的jar包拷到tomcat的lib下,war包的WEB-INF/lib被删除,启动报错,主要是javassist的MemberResolver报出的错,#searchImports,#lookupClass等等。希望能得到帮助，谢谢，可以发我邮箱331077064@qq.com

**Comment by javahongxi** [comment]
用不着tomcat啊，亲

**Comment by qq331077064** [comment]
谢谢，现在不在tomcat下部署了。


原始邮件
发件人:git.toutiao.imnotifications@github.com
收件人:alibaba/dubbodubbo@noreply.github.com
抄送:qq331077064331077064@qq.com; Authorauthor@noreply.github.com
发送时间:2017年12月2日(周六) 22:56
主题:Re: [alibaba/dubbo] tomcat lib javassist (#46)


用不着tomcat啊，亲
