### ISSUE TITLE
accesslog自定义路径的访问日志文件会按天翻滚吗

### ISSUE THREAD

**Issue by shuohao** [alibaba/dubbo#475]
还是一直往这个文件里打

**Comment by chickenlj** [comment]
accesslog提供有两种策略可选：
1. 使用log框架，如log4j，具体日志文件翻滚策略取决于工程的配置
2. dubbo框架直接写日志文件，这种策略会按天翻滚

参考 http://dubbo.io/user-guide/demos/%E8%AE%BF%E9%97%AE%E6%97%A5%E5%BF%97.html
