### ISSUE TITLE
多台消费者一致性哈希结果保持一致性的问题

### ISSUE THREAD

**Issue by codeyuan** [alibaba/dubbo#480]
dubbo采用一致性哈希做lb策略时，能够保证相同的请求参数总落到同一台provider上，但是多台consumer表现不一致，例如：同样的参数，消费者A和B计算出来的provider会出现不一样的情况，麻烦请教，dubbo在这方面有解决吗？

**Comment by zhuyuesut** [comment]
解决后的结果预期是什么样的？

**Comment by codeyuan** [comment]
我希望不同的消费者处理同一服务相同参数的请求总是发到同一提供者，我已经通过扩展dubbo的一致性hash解决这个问题了

**Comment by mercyblitz** [comment]
能不能贴一下代码，帮助其他同学呢

**Comment by zyokia** [comment]
我现在也遇到这个问题，同一台consumer重启后，再调，相同参数可能会落到另一台provider上
请问，你是怎么解决的

**Comment by codeyuan** [comment]
我的做法比较简单粗暴，就是扩展了dubbo的负载均衡算法，把一致性哈希key中受provider影响的参数去掉了，把原来的一致性hash编成了这样
`public ConsistentHashSelector(List<Invoker<T>> invokers, String methodName, int identityHashCode) {
            this.virtualInvokers = new TreeMap<Long, Invoker<T>>();
            this.identityHashCode = System.identityHashCode(invokers);
            URL url = invokers.get(0).getUrl();
            this.replicaNumber = url.getMethodParameter(methodName, "hash.nodes", 160);
            String[] index = Constants.COMMA_SPLIT_PATTERN.split(url.getMethodParameter(methodName, "hash.arguments", "0"));
            argumentIndex = new int[index.length];
            for (int i = 0; i < index.length; i++) {
                argumentIndex[i] = Integer.parseInt(index[i]);
            }
            for (Invoker<T> invoker : invokers) {
                for (int i = 0; i < replicaNumber / 4; i++) {
                    String fullUrl = handleFullURl(invoker.getUrl().toFullString());

                    byte[] digest = md5(fullUrl + i);
                    for (int h = 0; h < 4; h++) {
                        long m = hash(digest, h);
                        virtualInvokers.put(m, invoker);
                    }
                }
            }
        }

        private String handleFullURl(String fullUrl ){
            int startPid = fullUrl.indexOf("&pid=");
            if (startPid != -1) {
                fullUrl = fullUrl.substring(0, startPid);
            }
            int startTimestamp = fullUrl.indexOf("&timestamp=");
            if (startTimestamp != -1) {
                fullUrl = fullUrl.substring(0, startTimestamp);
            }
            return fullUrl;
        }`

**Comment by zyokia** [comment]
嗯 那也要修改源码了

**Comment by codeyuan** [comment]
不用改，dubbo负载均衡算法可扩展，把一致性hash算法按照上面的改下，就可以了
