### ISSUE TITLE
Dubbo开始维护了？

### ISSUE THREAD

**Issue by linving** [alibaba/dubbo#481]
现在又开始维护了？不是说以前不维护了？

**Comment by kimmking** [comment]
@liangfei0201

**Comment by zuohl** [comment]
同问

**Comment by takeseem** [comment]
dubbo需要重新设计了，要不然性能跟不上时代了。

**Comment by niweicumt** [comment]
同好奇，朋友圈里看到截图说又重新开始维护了。

**Comment by eonezhang** [comment]
不支持响应式编程真的会out的

**Comment by xiaolongyuan** [comment]
+1

**Comment by yunhaibin** [comment]
@oldratlee 准备开始优化了？

**Comment by davidzzw** [comment]
已结维护了

**Comment by oldratlee** [comment]
@yunhaibin 

是的，有专职的同学投入了

**Comment by xiaolongyuan** [comment]
@oldratlee 有路线图么？

**Comment by yunhaibin** [comment]
@oldratlee 哪个团队在维护呢？是你们淘宝技术部？还是中间件团队？

**Comment by muyl** [comment]
dubbo项目将正式得到官方维护与支持，我们期待这款优秀的开源项目在未来持续保持活力，引领开源服务框架 

--Alibaba dubbo-team

**Comment by xiaolongyuan** [comment]
@muyl 有没有规划（路线图） 让大家知道未来dubbo会怎么样

**Comment by Zavien** [comment]
希望可以继续维护，国内已经很难找到这样的优秀的RPC服务框架了，更何况，技术在不断进步，有维护才能促进繁荣。广大用户也可以进行捐赠的，千万别让这个框架没落下去。祈祷！

**Comment by stoneapple** [comment]
同求规划图，能介绍下dubbo后续的发展方向吗

**Comment by githublaohu** [comment]
是否重构，重构是否可以算我一个。

**Comment by xiaods** [comment]
同求规划图，能介绍下dubbo后续的发展方向吗

**Comment by MerGades** [comment]
关注

**Comment by justein** [comment]
15年开始用的，好几个项目了，虽说偶有小坑，但也都填上了，非常希望能看到dubbo重生！期待！

**Comment by benyVip** [comment]
期待哈哈哈

**Comment by qixiaobo** [comment]
http://www.oschina.net/news/87355/dubbo-maintained-and-supported-officially

**Comment by duanzhanling** [comment]
呵呵 终于开始维护了
期待啊

**Comment by PeterRJP** [comment]
期待呀哈哈

**Comment by lipengbin** [comment]
好消息啊，值得期待！

**Comment by yourchanges** [comment]
不错，支持下

**Comment by xudongQiu** [comment]
支持
