### ISSUE TITLE
2.5.3会间歇性连接超时

### ISSUE THREAD

**Issue by duanzonglong** [alibaba/dubbo#482]
http://blog.csdn.net/csujiangyu/article/details/51984600
这是看到的其他帖子里说的解决方法 麻烦确认下是否存在问题 我们生产环境此问题出现很多回了

**Comment by kimmking** [comment]
我告诉你一个简单办法，改本地的hosts文件

**Comment by duanzonglong** [comment]
能否在下个版本里解决，由于使用了docker各个生产环境都要维护hosts文件势必会有点复杂了

**Comment by chickenlj** [comment]
这个是已知问题，MonitorFilter中，注册中心getHostByIp的操作会阻塞正常请求流程，会在下个版本中修复。

**Comment by beiwei30** [comment]
@kimmking 你能贴一下你的 monitor service 是如何配置的吗？是不是 DNS 解析有问题造成的呢？

**Comment by beiwei30** [comment]
https://github.com/alibaba/dubbo/commit/57c1d686ca53791bdfc5843020683e23564db1d3 should solve the problem.
