### ISSUE TITLE
dubbo项目将再次迎来更新吗？

### ISSUE THREAD

**Issue by anancc** [alibaba/dubbo#485]
我看Dubbo 官网更新了， "dubbo项目将正式得到官方维护与支持，我们期待这款优秀的开源项目在未来持续保持活力，引领开源服务框架 " ，这是否意味着dubbo项目将再次迎来更新？

**Comment by wanjun123** [comment]
maybe

**Comment by chenhangbiao** [comment]
这个公告挂出来多久了？

**Comment by ityouknow** [comment]
现在spring boot/cloud发展这么火的情况下，dubbo很难再崛起了。在spring boot没有出来之前，那么多大好的机会没有抓住很可惜。

**Comment by luoyifan** [comment]
踩过spring-cloud坑，稀烂的东西，一路走一路给他填坑。
期待 dubbo 更新

**Comment by MerGades** [comment]
期待更新。

**Comment by justein** [comment]
cloud实在太重，各种组件学习成本太高。还是期待dubbo

**Comment by carvendy** [comment]
赶紧起来呀。

**Comment by dadalgq** [comment]
活跃用户还是很多的嘛

**Comment by dongguangwang** [comment]
期待更新。

**Comment by javaChain** [comment]
坐等更新

**Comment by lizhouyang** [comment]
好期待

**Comment by genghaizhou** [comment]
spring-cloud 太重了, 希望快点更新吧

**Comment by liangsijian** [comment]
this is helpful for me

**Comment by zlikun** [comment]
别的都还好说，版本升级一下吧，相关组件的，特别是`spring`的版本。另外也希望出一个`spring-boot-starter-dubbo`的官方版本(并非一定要与`spring-cloud`做适配)。

**Comment by wwulfric** [comment]
一人血书请求合并dubbox

**Comment by oawang** [comment]
后续更新框架蓝图呢

**Comment by davidzzw** [comment]
之前用dubbo启动死活报错 查了下是spring版本的问题。。。。。。。

**Comment by cg199082** [comment]
spring cloud太繁琐，期待dubbo更新。

**Comment by chickenlj** [comment]
dubbo后续会得到官方的重点维护，会有专门的人员&团队来跟进

**Comment by lxl514614** [comment]
期待dubbo更新,希望越来越好

**Comment by BomOwen** [comment]
Good news ~
Dubbo 设计优雅， 简单高效 !
期待更好维护和更新 ！
