### ISSUE TITLE
有没有人遇到消费者调用dubbo服务 Forbid 问题

### ISSUE THREAD

**Issue by haiboyang** [alibaba/dubbo#487]
有没有人遇到dubbo消费者在调用dubbo服务是隔断时间会出现Forbid 问题,dubbo2.5.3,2.5.4都有这问题，
很确定服务端没有设置黑白名单
com.alibaba.dubbo.rpc.RpcException: Forbid consumer 192.168.xxx.xxx access service com.iflytek.edu.message.api.CenterMessageBill from registry 192.168.xxx.xxx3181 use dubbo version 2.5.3, Please check registry access list (whitelist/blacklist).

**Comment by yibin001** [comment]
这是Provider挂了吧。

**Comment by wangpengyan123** [comment]
我也遇到过哎，一段时间会出现返回特别慢，超时，同求答案

**Comment by AnyinSong** [comment]
如果不是真的被forbid那就是provider从注册中心消失了，可以看下对应时间provider侧是否出现和注册中心断开的情况

**Comment by wuwen5** [comment]
1.检查下各服务器系统时间.
2.dubboadmin 检查provider信息，如时间戳.

**Comment by 472827074** [comment]
遇到过，每次都是莫名其妙后面自愈了，不过有一次是因为我加了版本号，客户端没指定对应版本号。

**Comment by chickenlj** [comment]
@haiboyang 

这个绝大多数场景下都是provider掉线导致的，consumer找不到任何provider。这块的异常信息有一定误导性，下个版本会考虑优化一下

**Comment by haiboyang** [comment]
看了下provider服务是在的，就是他们没有写group，使用dubbo默认的group，这个group里面api很多不知道是不是有服务更新了导致其他服务受到影响，现在重新创建group暂时没发现问题，不知道是不在这个原因

**Comment by paopaoteng** [comment]
如果provider掉线报forbid的错误，那什么时候会报no provider的错误呢？

**Comment by diecui1202** [comment]
This exception message is not correct, we have fixed it in #566. Pls check the newest version.

**Comment by hunterzhang86** [comment]
> 遇到过，每次都是莫名其妙后面自愈了，不过有一次是因为我加了版本号，客户端没指定对应版本号。

我也是加上版本号就好了。
