### ISSUE TITLE
维护的方向是什么，未来的规划呢？

### ISSUE THREAD

**Issue by FutureElement** [alibaba/dubbo#489]

**Comment by FutureElement** [comment]
是不是先能把一些client做好

**Comment by mercyblitz** [comment]
有什么建议吗？

**Comment by FutureElement** [comment]
1.我们目前使用的dubbo的2.5.3版本相关maven依赖都太老了，spring是默认用2.5.6，fastjson都还是1.1.18，能否把相关组件都升级一下？
2.官方推荐使用zookeeper，但dubbo对zk的client支持的不好，最老的zkclient还是个多年不维护的个人开源项目，能不能官方出一些client或者在dubbo内嵌支持，不需要外部依赖？
3.dubbo admin 是个好东西，可以好好规划优化下
4.目前spring boot，spring cloud等可以提供微服务全家桶所有相关的东西，关于现在流行的技术，相关服务监控，治理等，是不是也可以考虑有类似全家桶的扩展圈发展？

**Comment by SoyMeng** [comment]
最好还是能兼容spring cloud，类型netflix组件

**Comment by liaoqn** [comment]
建议：
先把2.5.4发了，基本的缺陷修复了，用2.5.3的项目升级也完全兼容；
合并dubbox，发个2.9，阿里小伙伴当当网这些年做了很多贡献，也有很多项目使用dubbox，合并很有必要；
3.0再做大调整。

**Comment by lipengbin** [comment]
一点建议
1：微服务方向吧。
2：直接build成Docker。
3：框架自身的具有配置中心，熔断机制，分布式跟踪，消息总线，自动发现等等。。
4：消费生产通过注解定义这个的支持吧。
5：通信采用自己的协议以及连接方式，保证高效。

**Comment by treemanfm** [comment]
dubbo跟微博的轻量级RFC 框架motan跟比起来，有什么不一样的地方么?

**Comment by EdwardLee03** [comment]
@kimmking 的想法：

**Comment by lovepoem** [comment]
https://github.com/alibaba/dubbo/issues/745

**Comment by lovepoem** [comment]
@treemanfm
http://blog.csdn.net/liubenlong007/article/details/54692241
服务化实战之 dubbo、dubbox、motan、thrift、grpc等RPC框架比较及选型

**Comment by hanwangkun** [comment]
微服务就dubbo,dubbox,spring cloud三者在pk了

**Comment by darknesstm** [comment]
@Refrence 这个注解总是很变扭，为什么不能直接融入到spring的上下文中去，让spring进行注入
还有 @Service的注解和spring的冲突，是不是可以改个名字或者加上前缀
