### ISSUE TITLE
国内很多人还是期待dubbo更新啊！

### ISSUE THREAD

**Issue by J-Chung** [alibaba/dubbo#493]
但是还是希望优先对spring等升级，以及改掉现有的一些bug。

**Comment by wukong0503** [comment]
这问题一股贴吧的味道

**Comment by xiaolongyuan** [comment]
![image](https://user-images.githubusercontent.com/3142363/28952012-13530568-7901-11e7-8450-174e3d9e408b.png)
看看fork出去的版本 就知道有很多遗留的问题
