### ISSUE TITLE
容错策略

### ISSUE THREAD

**Issue by buptstehc** [alibaba/dubbo#508]
默认容错策略为failover，消费者调用时走FailoverClusterInvoker，但是，发现有走AvailableClusterInvoker的情况，请问是什么原因？

**Comment by justein** [comment]
不会吧？AvailableCI貌似在Dubbo里都是never used

2017-08-10 

james_gosling 



发件人：buptstehc <notifications@github.com>
发送时间：2017-08-10 14:46
主题：[alibaba/dubbo] 容错策略 (#508)
收件人："alibaba/dubbo"<dubbo@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

默认容错策略为failover，消费者调用时走FailoverClusterInvoker，但是，发现有走AvailableClusterInvoker的情况，请问是什么原因？

**Comment by chickenlj** [comment]
在配置了多注册中心的情况下，是会启用AvailableCluster策略

**Comment by buptstehc** [comment]
日志里面抛了这个异常：No provider available in，所以怀疑是走了AvailableClusterInvoker

**Comment by justein** [comment]
查看提供方是否正常运行，zk节点检查注册状态，黑白名单等，这个异常跟后面这个没关系。

2017-08-10 

james_gosling 



发件人：buptstehc <notifications@github.com>
发送时间：2017-08-10 17:01
主题：Re: [alibaba/dubbo] 容错策略 (#508)
收件人："alibaba/dubbo"<dubbo@noreply.github.com>
抄送："Lyn"<james_gosling@163.com>,"Comment"<comment@noreply.github.com>

日志里面抛了这个异常：No provider available in，所以怀疑是走了AvailableClusterInvoker
