### ISSUE TITLE
dubbo文档现在的展现方式太丑了，没有整体感，不如以前。

### ISSUE THREAD

**Issue by XUZHOUWANG** [alibaba/dubbo#511]
本来阅读内容的连续的，现在每次都被点击下一页打断思考的连续性。 丑丑丑

**Comment by takeseem** [comment]
同感，还是喜欢all in one page。
一个Ctrl+F就都有了，其实可以做一个模板整合到一起。

**Comment by chickenlj** [comment]
感谢提供意见，我们会根据实际使用的反馈情况做调整

**Comment by fachilles** [comment]
何不一起为其制作一个SPA？
