### ISSUE TITLE
优雅停机如何配置

### ISSUE THREAD

**Issue by why7282** [alibaba/dubbo#534]
管理台可以通过路由禁止访问某个服务，但是无法批量设置某个项目的所有服务都禁用，一个一个会很复杂。顾想采用优雅停机的方案来处理发版时的边界问题。但是优雅停机官网文档的：
<dubbo:application ...>
<dubbo:parameter key="shutdown.timeout" value="60000" /> 
</dubbo:application>

这个配置压根就不能配置，启动直接报错，具体如何配置有人有方案？或者有在线上试运行过？

**Comment by chickenlj** [comment]
当前优雅停机逻辑存在无法等待timeout的bug，会在接下来的版本中修复。文档配置也会相应更新

**Comment by BugZuo** [comment]
需要多久可以更新呢 很期待的说
