### ISSUE TITLE
服务延迟(delay)暴露时存在并发问题

### ISSUE THREAD

**Issue by chickenlj** [alibaba/dubbo#543]
在启用延迟暴露时，同一个工程的多个服务可能会被暴露在不同的端口：
如8个服务在端口20880，2个服务在20881

`public synchronized void export() {
        if (provider != null) {
            if (export == null) {
                export = provider.getExport();
            }
            if (delay == null) {
                delay = provider.getDelay();
            }
        }
        if (export != null && ! export.booleanValue()) {
            return;
        }
        if (delay != null && delay > 0) {
            Thread thread = new Thread(new Runnable() {
                public void run() {
                    try {
                        Thread.sleep(delay);
                    } catch (Throwable e) {
                    }
                    doExport();
                }
            });
            thread.setDaemon(true);
            thread.setName("DelayExportServiceThread");
            thread.start();
        } else {
            doExport();
        }
    }
    
    protected synchronized void doExport() {
        if (unexported) {
            throw new IllegalStateException("Already unexported!");
        }
     ...
  }
`

**Comment by huzhongchun0918** [comment]
请教下，如果协议里面没有配置端口号，发布时的端口号会选择协议默认的端口号，为什么会有不同的端口号呢？

**Comment by KoneZJ** [comment]
protocol没有配置端口，协议默认端口如果为0，就会出现并发去取random port。
