### ISSUE TITLE
请教自己下载dubbo源码(dubbo-2.5.3 tag)打包和官方发布的包(2.5.3)在jar"/META-INF/maven/**"目录下的差异问题

### ISSUE THREAD

**Issue by lanyejingyu** [alibaba/dubbo#544]
如题描述，自己修改些东西然后打包jar包中/META-INF/maven/目录下包含`maven-shade-plugin`引入的所有模块,而官方打出包只有dubbo-2.5.3.jar!/META-INF/maven/com.alibaba/dubbo/目录，这个是打包后怎样特殊处理的吗？ （差异不影响使用，但在通过/META-INF/maven/**/pom.properties分析依赖jar包版本的时候会有差异）

**Comment by chickenlj** [comment]
打包位置和命令用的不同而已，这个不要紧
