### ISSUE TITLE
com.alibaba.dubbo.common.serialize.support.dubbo.Builder#newObjectBuilder 存在死循环的风险

### ISSUE THREAD

**Issue by xiongran** [alibaba/dubbo#558]
![image](https://user-images.githubusercontent.com/13461531/29758558-19b672de-8be7-11e7-88d3-6f160bc82eb7.png)

449行应该是  cs = t.getDeclaredConstructors(); 才对。

**Comment by qinliujie** [comment]
十分感谢，如果能提个PR就更好了〜
