### ISSUE TITLE
哪里可以设置zookeeper长连接关闭的时间?

### ISSUE THREAD

**Issue by highfei2011** [alibaba/dubbo#563]
dubbo处理完客户端请求后，后台zookeeper机器之间的链接还没有关闭，而且越来越多。如果客户端没有主动关闭长连接，那么我们该怎么关闭呢？ @zhuzhaoyuan @wangchangbing @kiminotes 麻烦帮看看，谢谢。

**Comment by chickenlj** [comment]
“客户端”是什么指什么客户端？在dubbo生命周期内，活跃的provider consumer就是要与zk保持长连接才对

**Comment by highfei2011** [comment]
客户端是浏览器，也就是consumer，那么dubbo的生命周期可以指定吗？谢谢@ @chickenlj

**Comment by highfei2011** [comment]
这是出现的报错信息------>https://github.com/dangdangdotcom/dubbox/issues/355 。
