### ISSUE TITLE
浮点型精度变化bug

### ISSUE THREAD

**Issue by miaoyoumeng** [alibaba/dubbo#57]
dubbo远程调用带HashMap参数时，如果HashMap中的值是float类型，那么在provider方接受到的对应参数值将发生变化。
例如，rpc请求发送参数：
        HashMap<String, Object> contentMap = new HashMap<String, Object>();
        contentMap.put("price", Float.valueOf(21.32f));
那么在provider方接受到的对应的“price”值为:21.31999969482422。
我们对这个问题的修改方案是在BasicSerializer类的writeObject方法的FLOAT和DOUBLE分别处理。
我的联系邮箱：miaoyoumeng@gmail.com

**Comment by YuanJiaYuan** [comment]
退订






发自网易邮箱大师


在2017年10月16日 16:46，qinliujie<notifications@github.com> 写道：

Closed #57.
