### ISSUE TITLE
dubbo 令牌验证

### ISSUE THREAD

**Issue by pengyonglei** [alibaba/dubbo#609]
您好: 
    请问dubbo的令牌验证只需要在provider方加上token的配置就可以了吗 ? 消费者或者注册中心需要修改什么吗  ? 我使用zookeeper作为注册中心 . 还有就是如何验证我加的token是否真的有效呢 ? @qinliujie

**Comment by chickenlj** [comment]
token主要限制绕过注册中心的直连，你provider加上token后，consumer端配置[提供者直连](https://dubbo.gitbooks.io/dubbo-user-book/content/demos/explicit-target.html)被拒绝就是ok了

**Comment by wangxuebin01** [comment]
意思就是说就是说如果客户端和服务端都能连接到注册中心，就有权限访问了？

**Comment by wangxuebin01** [comment]
意思就是说就是说如果客户端和服务端都能连接到注册中心，就有权限访问了？@chickenlj
