### ISSUE TITLE
pom中应该加入eclipse-plugin的设置，否则导入eclipse中可能编码集不是UTF-8

### ISSUE THREAD

**Issue by ghostsun** [alibaba/dubbo#62]
如果eclipse默认编码集为GBK，导入eclipse之后，会报错，建议主pom中加入对插件的设置，指定编码及为UTF-8
设置如下：
<plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-eclipse-plugin</artifactId>
                    <version>2.9</version>
                    <configuration>
                       <additionalConfig>
                          <file>
                             <name>.settings/org.eclipse.core.resources.prefs</name>
                             <content>
                                <![CDATA[eclipse.preferences.version=1${line.separator}encoding/<project>=UTF-8${line.separator}]]>
                             </content>
                          </file>
                       </additionalConfig>
                    </configuration>
                 </plugin>

**Comment by jacarrichan** [comment]
<project.build.sourceEncoding>${file_encoding}</project.build.sourceEncoding>
根据这个看，setting.xml需要有对应项
