### ISSUE TITLE
dubbo-admin在启动后报错

### ISSUE THREAD

**Issue by konglingjuanyi** [alibaba/dubbo#623]
提示没有找到applicationContextxml文件

**Comment by huanghaojian** [comment]
我启动也是FileNotFoundException: Could not open ServletContext resource [/WEB-INF/applicationContext.xml]

**Comment by chickenlj** [comment]
确认是dubbo-admin中webx版本和spring4.x不兼容的问题，目前还没有找到合适的webx版本，dubbo-admin暂时修复用3.x版本

**Comment by konglingjuanyi** [comment]
关键特么现在2.5.5也还是报错哇
