### ISSUE TITLE
RpcContext多级调用判断问题

### ISSUE THREAD

**Issue by kainhong** [alibaba/dubbo#628]
isProviderSide/isConsumerSide 判断过于简单，如果是有三个服务调用顺序为A->B->C，在B即是服务端又是客户端，因此只是简单通过url和ip地址判断太过于简单了。RpcContext简单使用ThreadLocal来判断也不合适，应该使用一个链表来保存服务调用链中的RpcContext。

**Comment by chickenlj** [comment]
@kainhong  请问有增加什么判断指标的建议吗？目前的情况下实际使用中遇到哪些问题？
