### ISSUE TITLE
log4j2 会得到官方的支持吗？

### ISSUE THREAD

**Issue by wxiangliang** [alibaba/dubbo#641]
如题！

**Comment by Comven** [comment]
日志框架完全可以由自己控制的，与dubbo没有关系的，项目开发使用slf4j这类的日志接口工具包，底层根据你自己需要来选择，配置好日志实现包之间的桥接关系就可以

**Comment by wxiangliang** [comment]
我的意思是现在dubbo 日志组件都是都是直接用log4j ，是不是改成slf4j好点，不需要关心具体日志组件。

**Comment by Comven** [comment]
@wxiangliang 你可以采用slf4j的log4j-over-slf4j工具包做日志桥接呀，依赖包采用什么日志框架都没有关系，可以参考springframework的日志方式
