### ISSUE TITLE
提个建议关于@Service注解

### ISSUE THREAD

**Issue by devcooperation** [alibaba/dubbo#643]
有时候使用dubbo注解功能简单配置 spring本身的@Service注解 和 dubbo的 @Service 容易混淆，可以再加个@DubboService之类的注解不，以示区分？谢谢~

**Comment by glameyzhou** [comment]
乍一看，确实容易混淆。

**Comment by DayuZhu** [comment]
看包引用就ok了

**Comment by search-cloud** [comment]
我们自己维护的版本里面就是改成了：@DubboService，建议改成：@DubboService

**Comment by yjqg6666** [comment]
+1

**Comment by lintghi** [comment]
+1

**Comment by xiaolongyuan** [comment]
+1

**Comment by snifferhu** [comment]
+1

**Comment by lxyzxq2008** [comment]
+1

**Comment by amwei** [comment]
+1

**Comment by halober** [comment]
觉得没啥必要，本来就是spring @service和dubbo @service两个只能选一个。

**Comment by jiahut** [comment]
dubbo 的 `@service` 和 spring 的 `@service` 语义不一样吧， dubbo `@service`  类似于 spring mvc 的 `@controller`层，建议的话 叫`@exposure`  不更好么， 和`@reference`  一对。

**Comment by halober** [comment]
我觉得，区别不大，他主要是发布服务层，而不是控制器层，提供给外部调用。

**Comment by yjqg6666** [comment]
@search-cloud 整个PR ?

**Comment by lintghi** [comment]
+1

**Comment by CodingOX** [comment]
+1

**Comment by ayhero** [comment]
+1

**Comment by javahongxi** [comment]
完全没必要，bad idea, dubbo服务和一般的service不在同一包层次，事实上dubbo服务和Controller是同一层次

**Comment by javahongxi** [comment]
bad idea, dubbo services and other services are in diffrent package.

**Comment by xin497668869** [comment]
+1

**Comment by zhusaidong** [comment]
> 觉得没啥必要，本来就是spring @service和dubbo @service两个只能选一个。

对服务进行单元测试时2个都要有吧。

**Comment by small-Teenager** [comment]
+1
