### ISSUE TITLE
作为一个专业的喷子，我决定喷你们一下

### ISSUE THREAD

**Issue by newpanjing** [alibaba/dubbo#649]
一个中国人写的中国产品，官网为什么用英文？高大上么？逼格高么？

**Comment by nvgui** [comment]
大公司的文档全部是英文的

**Comment by Leviathans** [comment]
有中文的

**Comment by dchack** [comment]
dubbo目前使用了alibaba的域名，作为国际公司，使用英语是必备的选项。加上git本来就是国际化的。
可惜的是中文没能成为世界通用语言，希望你也努力推广中文向其他非中文国家。

**Comment by abatorQ** [comment]
【希望你也努力推广中文向其他非中文国家】，这是从英语翻译过来的吗？还好中文过了四级啊，不然都看不懂了。

**Comment by dchack** [comment]
@abatorQ 还好你看懂了 感觉好荣幸

**Comment by newpanjing** [comment]
看是看得懂，主要是觉得很别扭，感觉自家的东西却要用别人家的语言～，要是默认中文的话多好，让老外体验下学中文～

**Comment by oldratlee** [comment]
Issue 是讨论项目的。如对项目没有改进，而是个人感情上的倾向，不在Issue里说了。

减少大家过Issue时的噪音 :)
