### ISSUE TITLE
dubbo源码会适当多增加一些注释吗？ 

### ISSUE THREAD

**Issue by zhangyinyue** [alibaba/dubbo#651]
dubbo源码会适当多增加一些注释吗？  或者说，如果我们来贡献这些注释，做这个有意义吗？ 对比jdk源码，可以看到他们基本都是注释比代码多

**Comment by chickenlj** [comment]
可以提交源码注释呀，提交PR，我们会有人来处理的；或者做一些源码解读/架构设计的分享也可以作为官方文档的补充

**Comment by chickenlj** [comment]
@zhangyinyue 有问题可以到gitter中讨论，issue适合跟踪一些确定的、需要代码改进的问题
https://gitter.im/alibaba/dubbo
