### ISSUE TITLE
使用api配置服务暴露失败

### ISSUE THREAD

**Issue by shitongtong** [alibaba/dubbo#653]
官网代码：
```
// 连接注册中心配置
RegistryConfig registry = new RegistryConfig();
registry.setAddress("10.20.130.230:9090");
...
```
我的代码：
```
...
registry.setAddress("zookeeper://192.168.1.219:2181");
...
```
其他代码一致（service为自己的service）。
启动无异常，但是服务暴露失败。不知道是什么原因？

**Comment by chickenlj** [comment]
使用问题的讨论或疑问请到 [gitter](https://gitter.im/alibaba/dubbo) 或 [邮件组](https://groups.google.com/forum/#!forum/dubbo) 详细描述你的问题
