### ISSUE TITLE
WiKi文档不见了，昨天还在的

### ISSUE THREAD

**Issue by shitongtong** [alibaba/dubbo#656]
WiKi文档不见了，昨天还在的。本来有四篇的。为什么删掉了呢，可以恢复吗？

**Comment by k5h9999** [comment]
https://dubbo.gitbooks.io/dubbo-dev-book/

**Comment by tianshuiyifang** [comment]
你们在干毛线那，文档都他妈的没了~

**Comment by chickenlj** [comment]
@tianshuiyifang   https://dubbo.gitbooks.io/dubbo-dev-book/
