### ISSUE TITLE
dubbo能否跟motan一样，提供服务优雅停机的方法，每次断开都要timeout后才能请求另外机器的请求

### ISSUE THREAD

**Issue by konglingjuanyi** [alibaba/dubbo#661]
https://github.com/weibocom/motan/wiki/zh_userguide#%E7%AE%A1%E7%90%86%E5%90%8E%E5%8F%B0
MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, false)

**Comment by chickenlj** [comment]
当前的shutdownhook机制不能总是确保优雅的停机，尤其是在应用容器环境下。当前在考虑优化优雅停机的触发机制，如提供接口支持停机脚本触发停机下线流程

**Comment by chickenlj** [comment]
#982
