### ISSUE TITLE
dubbo-admin中看不到消费者consumer

### ISSUE THREAD

**Issue by ggf55555** [alibaba/dubbo#663]
用的官方提供的demo，在 String hello = demoService.sayHello("world"); 处打上断点，admin中能看到消费者，代码跑完后admin中看不到消费者

**Comment by leavesgreen** [comment]
@ggf55555, me too, 而且consumer 启动之后,  也没有调用记录;

**Comment by chickenlj** [comment]
目前源码已增加启动日志输出。consumer启动后执行完成会立马exit

**Comment by ggf55555** [comment]
@chickenlj @leavesgreen 明白了，consumer执行后我加上和provider中一样的System.in.read()就能保持住了。

**Comment by dengjiexiao** [comment]
@chickenlj dubbo-admin中看不到消费者consumer 这个是不是正常的

**Comment by Colouful** [comment]
> 用的官方提供的demo，在 String hello = demoService.sayHello("world"); 处打上断点，admin中能看到消费者，代码跑完后admin中看不到消费者

你的代码跑完了，也就是消费这个状态结束了，肯定不显示啊，只要保持你的消费者项目一直启动就行
