### ISSUE TITLE
使用redis做注册中心时，如果redis有密码，怎么设置？

### ISSUE THREAD

**Issue by cralcui** [alibaba/dubbo#665]
请教使用redis做注册中心时，如果redis有密码，怎么设置？

**Comment by qixiaobo** [comment]
![image](https://user-images.githubusercontent.com/2881751/30572954-93b162d0-9cb6-11e7-9a37-371a5576684a.png)
代码写死的 配不了吧
要不就修改代码吧……或者提PR

**Comment by cralcui** [comment]
@qixiaobo 谢了

**Comment by limingwei** [comment]
别用 dubbo 自带的 redis 注册中心，问题真的不少

**Comment by snowy520** [comment]
zookeeper做注册中心最好吧

**Comment by eonezhang** [comment]
dubbo 的zk 可以提供密码认证服务的功能不

**Comment by wzlee** [comment]
![image](https://user-images.githubusercontent.com/4182865/30999561-8adadcd0-a49b-11e7-8ca1-8669fe0b02db.png)

**Comment by wzlee** [comment]
![image](https://user-images.githubusercontent.com/4182865/30999589-aefa5e1a-a49b-11e7-8dcd-1da4c6bb1a11.png)
