### ISSUE TITLE
AnnotationBean问题

### ISSUE THREAD

**Issue by wenlinguo** [alibaba/dubbo#666]
在使用springboot+dubbo，全注解，0xml配置
使用过程中发现了2个问题

1. 集成了高版本的spring，可能AnnotationBean在获取bean的class的问题
自己重写了 AnnotationBean，通过
`
AopUtils.getTargetClass(bean);
`
来获取class

2. 如果我配置了providerConfig，并且delay=0情况下，在执行AnnotationBean的postProcessAfterInitialization 时，调用ServiceBean的afterPropertiesSet方法，进行服务export的时候，checkRef()会报 ref not allow null! 
检查AnnotationBean发现先执行了 referenceConfig.afterPropertiesSet(); 里面去调用 export()
后面才 设置  serviceConfig.setRef(bean);

故自己将代码修改 serviceConfig.setRef(bean); 放在前面

以前使用xml配置 没遇到过此异常， 因为没用到 AnnotationBean

**Comment by chickenlj** [comment]
1. 赞同使用AopUtils.getTargetClass(bean); 能具体说一下你遇到的 _获取bean的class问题_ 的场景吗？

2. serviceConfig.setRef(bean);是可以前移的。delay=0是一个特殊的使用场景，本身和不配置delay是一个效果
