### ISSUE TITLE
dubbo服务部署在容器中，注册发现的问题

### ISSUE THREAD

**Issue by wuhy198607** [alibaba/dubbo#668]
dubbo服务部署在容器中，存在需求，既有容器集群内部的访问，又有集群外部的访问。

希望dubbo服务能够提供灵活的注册机制。

比如： 1、通过指定IP 端口注册，通过配置项或者命令行参数
2、与docker的集成方案，通过配置项灵活选择 采用docker的宿主机IP或容器IP注册。

**Comment by chickenlj** [comment]
@wuhy198607 你好，我们打算通过支持命令行参数配置要注册的ip、port，来支持类似docker bridage网络环境下的服务注册和访问问题，这样就要求使用者明确指定注册那些能够与外部通信的ip、port
如：docker run -it --name dubbo dubbo-sample

**Comment by chickenlj** [comment]
> 2、与docker的集成方案，通过配置项灵活选择 采用docker的宿主机IP或容器IP注册。
请问你提到的集成方案的思路是什么，能否描述一下？

**Comment by chickenlj** [comment]
1、通过指定IP 端口注册，通过配置项或者命令行参数 
 #778

**Comment by xuanzi200** [comment]
@chickenlj    

请问一下，在K8S里面，有没有什么比较好的方案？解决消费pod调用的随机IP的服务端pod？
