### ISSUE TITLE
服务调用重复问题

### ISSUE THREAD

**Issue by 121635629** [alibaba/dubbo#671]
我现在有一个服务，在A机器上有一份、B机器上也有一份，然后C现在调用这个服务的时候，发现在AB上都有请求记录，并且间隔只有1秒之内。而我超时的时间是默认3秒的。而且都没报超时的错误，这问题有遇到过没

**Comment by dchack** [comment]
@121635629 
可以提供具体的配置信息或代码吗？

**Comment by 121635629** [comment]
我的是服务调用服务的方式

消费端的配置文件：
<dubbo:registry  protocol="zookeeper"  address="${zookeeper.address}"  /> 
<dubbo:protocol name="dubbo" port="20950" />
<dubbo:reference id="accAccountService" interface="com.xxxx.export.service.AccAccountService" check="false"/>

服务端配置文件：
<dubbo:registry  protocol="zookeeper"  address="${zookeeper.address}"  />  
<dubbo:protocol name="dubbo" port="20888" /> 
<dubbo:service interface="com.xxxx.export.service.AccAccountService" ref="accAccountService" />  
	<bean id="accAccountService" class="com.xxxx.service.impl.AccAccountServiceImpl" />

消费端调用服务端就直接是调用服务端的一个insert方法

**Comment by qcxyzff** [comment]
你是不是设置了 forks

**Comment by 121635629** [comment]
从上面我贴的配置文件可以看到，我没有使用任何集群相关的配置，所以都是默认的

**Comment by chickenlj** [comment]
默认超时3s的设置在哪里配置的

**Comment by 121635629** [comment]
默认的超时3s还需要配置吗？

**Comment by hungki** [comment]
默认failfast会自动重试，新版本clust的话添加：servicecluster="failsafe"，一般使用添加：retries="0"

**Comment by yuyijq** [comment]
@hungki failfast是不会重试的吧

**Comment by chickenlj** [comment]
@121635629 默认超时是1s、failover策略

**Comment by tianxiao-zp** [comment]
请问你的这个问题是怎么解决的呢？

**Comment by anian1011** [comment]
分布式环境时常会有多次调用、重复调用，因此服务最好设计为幂等的。

**Comment by GiilianRose** [comment]
请问一下怎么解决的，我现在也遇到同样的问题了。用的是incubator-dubbo springboot的版本

**Comment by 121635629** [comment]
@GiilianRose 设置超时时间，或者retries设置为0,或者cluster=failfast，你都可以试试
