### ISSUE TITLE
struts2中spring注入dubbo service为null

### ISSUE THREAD

**Issue by xburning** [alibaba/dubbo#675]
和这个帖子问题相同：
https://groups.google.com/forum/#!msg/dubbo/Yrkcgw2rFBo/UVV_o9jfAvwJ
也是tomcat再重启一次就好了。

版本：
struts2 - 2.3.32
spring - 3.1.1
dubbo - 2.5.3

**Comment by chickenlj** [comment]
spring启动没有报错吗？
建议在代码中检查dubbo service bean、action bean是否在applicationcontext中可正常查找到

**Comment by xburning** [comment]
启动有报错，配置为 `<dubbo:consumer check="false" />` 解决。 @chickenlj
