### ISSUE TITLE
dubbo的节点在提供者已经停止的情况下没有动态删除

### ISSUE THREAD

**Issue by XFelinae** [alibaba/dubbo#679]
注册中心为zookeeper 版本3.4.6
dubbo版本为2.5.3
在项目停止后，zookeeper上的提供者的dubbo节点没有动态删除，消费者还能调用到，然后调用接口超时。
情况偶发，主要发生在项目所在服务器的本地时间不完全同步、服务器时间被修改这两种情况下。

是否与2.5.4版本修复的以下相关问题是同一个问题？
动态配置：设置指定的consumer不生效，provider端动态配置删除后仍起作用

**Comment by chickenlj** [comment]
> 在项目停止后，zookeeper上的提供者的dubbo节点没有动态删除，消费者还能调用到，然后调用接口超时。
1. 项目是正常停止的吗？强制停止会导致无法删除，无法触发正常停机流程

> 情况偶发，主要发生在项目所在服务器的本地时间不完全同步、服务器时间被修改这两种情况下
2. 与服务器时间能有什么关系那？

> 是否与2.5.4版本修复的以下相关问题是同一个问题？
2.5.4版本修复的 "优雅停机"和你这个问题相关
