### ISSUE TITLE
不知道我们提交的pull request 处理的最长周期是多久。

### ISSUE THREAD

**Issue by zhangyinyue** [alibaba/dubbo#682]
不知道我们提交的pull request 处理的最长周期是多久。我提交了#635，#673，#676，感觉好久了，都没什么反馈。能不能抽空review一下，谢谢

**Comment by chickenlj** [comment]
你好，你的PR我们其实已经有同学在review了，只是之前没确定是否放在近期版本中。现在确定优先级放低一些，请知悉
