### ISSUE TITLE
服务提供无法注册，

### ISSUE THREAD

**Issue by wxb2939** [alibaba/dubbo#684]
com.alibaba.dubbo.rpc.RpcException: Forbid consumer 10.4.7.64 access service com.asiainfo.rechargeplat.api.interfaces.user.IUserService from registry 10.1.253.238:2182 use dubbo version 2.5.3, Please check registry access list (whitelist/blacklist).
一直能正常使用，现在就只有这个服务注册不了，别的服务都能使用！

**Comment by chickenlj** [comment]
看来是provider下线了，检查一下注册中心是否还存在providers

**Comment by david1228** [comment]
@chickenlj 
我本机也遇到了类似的问题，

**Comment by david1228** [comment]
@chickenlj 
我的本地环境中也遇到类似的问题，
报错信息：
Forbid consumer 10.58.95.10 access service com.xxx.mms.api.service.IAlbumService from registry 36.110.219.106:2181 use dubbo version 2.5.3, Please check registry access list (whitelist/blacklist).
当provider启动后，在zk中的providers节点下面能够看到注册信息，当消费端consumer启动后，zk中providers下注册信息丢失了，而consumers节点中有2份注册信息。
