### ISSUE TITLE
集合序列化

### ISSUE THREAD

**Issue by hj819748949** [alibaba/dubbo#696]
如果对于需要序列化的对象是

public class MyClass extends ArrayList<String>
{
        private String tag;
}

这种情况时,  默认的序列化传递过来时tag会丢失, 序列化时, 仅仅把集合项循环出来进行序列化, 没考虑属性

**Comment by chickenlj** [comment]
到[gitter](https://gitter.im/alibaba/dubbo?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)或[google论坛](https://groups.google.com/forum/#!forum/dubbo)讨论吧

我关掉了
