### ISSUE TITLE
序列化加密

### ISSUE THREAD

**Issue by hj819748949** [alibaba/dubbo#697]
dubbo能否提供通信加密的功能

**Comment by chickenlj** [comment]
我想在用于组织内部通信的协议上做加密没什么意义，反而拖累性能。倒是想到压缩是可以考虑的

@hj819748949  需要讨论问题，最好到[gitter](https://gitter.im/alibaba/dubbo?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)或[google论坛](https://groups.google.com/forum/#!forum/dubbo)哦，issue处理

**Comment by chickenlj** [comment]
到gitter吧，我关掉了
