### ISSUE TITLE
URL中addParamster(Map<String, String>)方法建议修改部分代码

### ISSUE THREAD

**Issue by lycwukang** [alibaba/dubbo#704]
com.alibaba.dubbo.common.URL.addParamster(Map<String, String>)
<br>
修改前:
-----
```java
if (value == null && entry.getValue() != null || value.equals(entry.getValue())) {
    ...
}
```
修改后:
------
```java
if (value == null ? entry.getValue() != null : !value.equals(entry.getValue())) {
    ...
}
```
原来的方法当value==null，entry.getValue()==null的情况，会触发NullPointerException

**Comment by moxiaonian** [comment]
**修改后** 应该是这个吧
`if (value == null ? entry.getValue() != null : value.equals(entry.getValue())) {  
    ...  
}`

**Comment by lycwukang** [comment]
写错了，修改前的代码是
if (value == null && entry.getValue() != null || !value.equals(entry.getValue())) {
    ...
}
