### ISSUE TITLE
如何在启动.jar时指定dubbo.properties的路径？

### ISSUE THREAD

**Issue by yibin001** [alibaba/dubbo#706]
打包后，dubbo.properties在jar中已存在，但配置需要改，怎么在java -xxx -jar xxx.jar中指定dubbo.properties的路径？

**Comment by chickenlj** [comment]
可以通过  `-Ddubbo.properties.file=xxx` 指定配置配置文件路径

**Comment by chickenlj** [comment]
使用问题，请到[gitter](https://gitter.im/alibaba/dubbo?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)提问。这样减少issue噪音，更有小的跟踪问题
