### ISSUE TITLE
dubbo-admin无法加载applicationContext.xml

### ISSUE THREAD

**Issue by phym** [alibaba/dubbo#708]
如果使用Spring 4.3.10.RELEASE启动时出现找不到applicationContext.xml错误
但是将一部jar替换为3.2.16.RELEASE就能正常启动
![image](https://user-images.githubusercontent.com/9352452/31005641-2e2f565a-a52c-11e7-85b0-f992bcfc7d95.png)
请问这个是什么原因？？？

**Comment by liuwei88212** [comment]
怎么解决？

**Comment by chickenlj** [comment]
dubbo-admin请使用3.2.16版本的spring，当前webx没有发布兼容spring4.x的版本。我们正考虑替换掉webx，不过可能会是很长一段时间后才开始
