### ISSUE TITLE
idea+springboot,在provider加入@Transactional 注解,消费端还是无法获得bean.

### ISSUE THREAD

**Issue by Macgrady4Ever** [alibaba/dubbo#709]
以前的被spring代理冲掉的dubbo service 问题依然存在

**Comment by halober** [comment]
或者把依赖换成这个 https://gitee.com/reger/spring-boot-starter-dubbo，或者在@Service 加上 interfaceClass参数

**Comment by chickenlj** [comment]
这个issue可能是一样的问题 #700 #512
