### ISSUE TITLE
将@Reference注解关联的对象未放到Spring容器中

### ISSUE THREAD

**Issue by surpass1990** [alibaba/dubbo#711]
@Reference注入的属性未在Spring容器管理中，导致AOP无法切服务的接口

**Comment by halober** [comment]
用过滤器啊

**Comment by chickenlj** [comment]
@reference注入的属性本身是Spring容器管理的，麻烦描述一下你的使用场景？

**Comment by myfly150** [comment]
我们也遇到了这种情况，AnnotationBean中，处理Reference注解时，直接将生成的对象设置给了被注解的变量，简单地分析一下代码，确实没有注册到spring容器中

**Comment by surpass1990** [comment]
@chickenlj  切面织入服务的接口代理类，用@reference就没有办法织入，原因就如@myfly150说的原因

**Comment by zhangyinyue** [comment]
你用切面的话，需要把interfaceName的值加上，不然dubbo会找不到服务的。如果没加的话，你注册上去的消费者并不是你想要的名称，可以看一下。

**Comment by chickenlj** [comment]
surpass1990 是存在你说的问题，代理对象未被spring托管，可以在2.5.7版本中修复掉
