### ISSUE TITLE
"服务治理 > 提供者"页面显示大量警告

### ISSUE THREAD

**Issue by lastboy1228** [alibaba/dubbo#714]
两个不同应用的服务名（group+interface+version）并没有重复，依然显示大量警告。
#109 之前有人已经提出了，2.5.5版本还没解决这个问题

**Comment by lovepoem** [comment]
I fixed it in PR https://github.com/alibaba/dubbo/pull/780

**Comment by chickenlj** [comment]
@lovepoem thx, as long as we don't have enough time these days, i'll move this issue to 2.5.8

**Comment by lovepoem** [comment]
@chickenlj ok
