### ISSUE TITLE
容我做一次伸手党，Dubbo项目如何在Docker中运行而不用依赖web容器

### ISSUE THREAD

**Issue by hungki** [alibaba/dubbo#715]
环境：jdk1.7   docker：1.10.3
zookeeper是单独部署的

网上找的不用依赖web容器的教程已经照了弄了一天了愣是没启动成功。

求大神不吝解答或提供教学交接。

小弟谢过。

**Comment by halober** [comment]
你可以看这个示例项目，不依赖web容器启动，很简单 https://gitee.com/lei0719/spring-boot-starter-dubbo-example

**Comment by chickenlj** [comment]
@hungki  spring容器启动，请参见[文档](https://dubbo.gitbooks.io/dubbo-user-book/content/demos/service-container.html)
