### ISSUE TITLE
关于spring-boot与dubbo

### ISSUE THREAD

**Issue by halober** [alibaba/dubbo#716]
看的出来，官方无意维护spring-boot与dubbo的实现，所以我自荐项目https://gitee.com/reger/spring-boot-starter-dubbo，期望dubbo官方可以推荐一下。
使用这个相信可以极大降低dubbo的使用门槛，对dubbo的推广也是很有利的。

**Comment by chickenlj** [comment]
我们计划在2.5.7版本改进dubbo注解配置，在此基础上考虑增加spring-boot的支持。

 您提供的spring-boot实现确实能简化好多配置，是个很好的参考实现
