### ISSUE TITLE
dubbo-admin启动报错

### ISSUE THREAD

**Issue by liaozan** [alibaba/dubbo#717]
最近才看dubbo的新手，请问为什么dubbo-admin部署报错。。。
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
INFO: configuring "log4j" using jndi:/localhost/dubbo-admin-2.5.5/WEB-INF/log4j.xml
 - with property localAddress = 39.108.189.100
 - with property localHost = 39.108.189.100
 - with property loggingCharset = UTF-8
 - with property loggingLevel = INFO
 - with property loggingRoot = /root/logs

 INFO context.ContextLoader - Root WebApplicationContext: initialization started
 INFO support.XmlWebApplicationContext - Refreshing Root WebApplicationContext: startup date [Mon Oct 02 22:11:47 CST 2017]; root of context hierarchy
 INFO xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/applicationContext.xml]
ERROR context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from ServletContext resource [/WEB-INF/applicationContext.xml]; nested exception is java.io.FileNotFoundException: Could not open ServletContext resource [/WEB-INF/applicationContext.xml]

**Comment by EdwardLee03** [comment]
@liaozan 提问前建议搜索一下已有Issue，说不定有人已经遇到过了。😁

**Comment by chickenlj** [comment]
请使用3.X及以下版本的spring。具体参见 #708
