### ISSUE TITLE
请问支持Java8新时间类型的hessian的release版本，将在什么时候发布？

### ISSUE THREAD

**Issue by yonghualuo** [alibaba/dubbo#722]

**Comment by chickenlj** [comment]
将在2.5.6版本发布，本周发布。

答疑或使用疑问，请到[gitter](https://gitter.im/alibaba/dubbo?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)提问，实时聊天更方便

**Comment by chickenlj** [comment]
@yonghualuo  你关注java8时间类型的原因是？当前hessian序列化有什么问题吗，能否描述一下？

**Comment by YuanJiaYuan** [comment]
怎么退订




在2017年10月11日 20:54，ken.lj 写道：

@yonghualuo 你关注java8时间类型的原因是？当前hessian序列化有什么问题吗，能否描述一下？

**Comment by yonghualuo** [comment]
@chickenlj 原生hessian对java8的LocalDate等类型不支持，序列化时会报StackOverflowError

**Comment by takeseem** [comment]
fix see #906，我们主要用的是dubbo协议，hessian不知道能不能自动把：locale的字符串反序列化为Locale对象，我想应该是ok的，jackson支持
```
public static void main(String[] args) throws IOException {
	ObjectMapper mapper = new ObjectMapper();
	String json = mapper.writeValueAsString(Locale.US);
	System.out.println(json);
	System.out.println(mapper.readValue(json, Locale.class));
}
```
