### ISSUE TITLE
@Reference check 属性默认是false，而ReferenceConfig.java在读取不到check属性时默认true，两边逻辑相悖

### ISSUE THREAD

**Issue by gxthrj** [alibaba/dubbo#724]
https://github.com/alibaba/dubbo/blob/17619dfa974457b00fe27cf68ae3f9d266709666/dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ReferenceConfig.java#L403-L405

当consumerConfig不设置 并且 @Reference使用默认值时，会将check默认设置为true，进而consumer会校验provider是否启动，导致被@Reference标注对象注入为null。
之后再启动provider服务，consumer不会重连。

**Comment by halober** [comment]
provider的check设置为false不就可以了

**Comment by gxthrj** [comment]
@halober 一般设置consumer.check=false就可以了，但是consumer.check 默认配置项就是false，Reference.check默认也是false，所以，当我什么都不显示配置时，应该各路check都是false，可是ReferenceConfig.java 中，我指出的那段又默认设置为true（这前后逻辑相悖）。导致我在应用中遇到被@reference标注对象注入为null的问题。

**Comment by halober** [comment]
默认consumer.check=true是没问题，这样启动就检查，更安全。你可以在配置项里边把consumer.check=false; Reference.check默认继承consumer.check的值，也就是Reference.check默认是没有自己的值的。

**Comment by wuwen5** [comment]
@gxthrj 的问题是这里默认值设计上不一致. +1

**Comment by Jukewu** [comment]
提完了才发现你已经提过了。。。。。。
