### ISSUE TITLE
FailbackRegistry retry时重新订阅问题

### ISSUE THREAD

**Issue by kuangdao** [alibaba/dubbo#727]
1，set移除Listener存在问题，for循环里使用listeners.remove(listener);异常
```
for (NotifyListener listener : listeners) {
    try {
        doUnsubscribe(url, listener);
        listeners.remove(listener);
    } catch (Throwable t) { // 忽略所有异常，等待下次重试
        logger.warn("Failed to retry unsubscribe " + failed + ", waiting for again, cause: " + t.getMessage(), t);
    }                        
}
```
2，failedSubscribed这个在订阅成功后，没有移除？

**Comment by zhangyinyue** [comment]
执行 listeners.remove(listener);这个时，就是相当于把failedSubscribed的value  Set<NotifyListener> 集合里面的元素给删除了。对同一个url再次subscribe或者unsubscribe时，会调用removeFailedSubscribed删除failedSubscribed，failedUnsubscribed里面的监听

**Comment by zhangyinyue** [comment]
至于1，set移除Listener存在问题，for循环里使用listeners.remove(listener);异常 这个你应该是要说快速失败的问题，你可以试一下，这里不会报错的。

**Comment by kuangdao** [comment]
我理解一下这段逻辑哈，是不是取到所有failedUnsubscribed里面的Listener，然后重新订阅，订阅成功的话，删除failedUnsubscribed这个，不知道我理解的是不是对的？还请解答一下哈

**Comment by kuangdao** [comment]
看明白了，这个快速失败的使用方式不认真看确实容易误解，抱歉哈，误认为是问题。
