### ISSUE TITLE
dubbo有没有考虑接入zipkin 或者eagleye这样的rpc跟踪系统？

### ISSUE THREAD

**Issue by lovepoem** [alibaba/dubbo#728]
dubbo的有没有考虑接入zipkin 或者eagleye这样的rpc跟踪系统？

目前我所知道https://github.com/openzipkin/zipkin
只有zipkin 是开源的。以前用scala写的，现在换成java了

阿里eagleye目前并不开源

**Comment by lovepoem** [comment]
@chickenlj

**Comment by maodie007** [comment]
@lovepoem  我们集成的pinpoint，效果还可以

**Comment by lovepoem** [comment]
@maodie007 pinpoint是韩国的一个项目吧？ 集成这个，对dubbo源码的修改多吗？

**Comment by maodie007** [comment]
不需要修改任何代码，无侵入式集成，你可以先去了解这个项目

**Comment by lihengming** [comment]
pinpoint 是JVM探针的方式，市面上很多收费的产品如 听云APM等

**Comment by lovepoem** [comment]
ken.lj @chickenlj 11:11
@lovepoem 鹰眼、zipkin这种都是独立的数据采集/分析系统，我们正调研接入OpenTracing的可能性

@chickenlj 提到的

**Comment by chickenlj** [comment]
自己扩展filter也可以事先接入这些开源跟踪系统

**Comment by lovepoem** [comment]
https://github.com/alibaba/dubbo/pull/462
