### ISSUE TITLE
Dubbo启动时 可否在 start.sh 中指定进程名称

### ISSUE THREAD

**Issue by DayuZhu** [alibaba/dubbo#733]
![default](https://user-images.githubusercontent.com/18682988/31485866-ed3c2c90-af67-11e7-80ee-147537908fcb.png)

比如：simple-monitor启动后的进程名称为 Main，我想把我自己的服务进程名称改为xxxService，那么怎么指定服务的进程名称呢？

**Comment by chickenlj** [comment]
这个我也不清楚唉.. 不过和dubbo本身倒是没啥关系，搞定了在这贴一下呗
