### ISSUE TITLE
XML配置项重新梳理

### ISSUE THREAD

**Issue by chickenlj** [alibaba/dubbo#738]
目前有一些配置项存在暴露的位置不正确、暴露不全面、文档和含义不匹配等问题，期望在2.5.7版本将已知问题予以整理修复

**如果使用中有遇到的配置问题，请在评论中列出以便改进**

**Comment by chickenlj** [comment]
tcp通信方式相关的配置项存在问题  
1. 涉及的配置项
```xml
<dubbo:registry transporter="" />
<dubbo:protocol transporter="" client="" server="" />
<dubbo:service 无/>
<dubbo:reference client="" />
```

2. 存在的问题
* reference中的client配置应删除，统一在protocol层级做配置
* 提供端配置的transporter不应该传递到消费端，影响消费端的默认通信协议
* registry中的transporter确定是不是无意义的，是否要删除
* client/server配置、transporter配置是同等效果，如果都保留应该文档予以说明推荐配置形式

**Comment by chickenlj** [comment]
```xml
<dubbo:protocol />
<dubbo:provider />
```
两个中的线程池相关配置项是否有同等作用，文档说明一下避免混淆

**Comment by chickenlj** [comment]
shutdown.timeout  warmup dump.directory等这些参数应该在properties级别支持配置

**Comment by zhangyinyue** [comment]
在发布服务时，有个scope的配置，这个配置有点奇怪，文档里好像没看到在哪里配置，是不是应该在service端配置呢 String scope = url.getParameter(Constants.SCOPE_KEY);

**Comment by chickenlj** [comment]
<dubbo:application />增加对<dubbo:parameter/>子元素的配置支持
<dubbo:consumer/>增加对<dubbo:reference/>子元素的配置支持

**Comment by chickenlj** [comment]
<dubbo:provider monitor="group:version" />
是为了兼容老版本配置，可以删掉

**Comment by chickenlj** [comment]
@zhangyinyue  在<dubbo:service scope="" />配置

**Comment by mercyblitz** [comment]
@chickenlj 确实太多重复配置了，这块可以讨论一下
