### ISSUE TITLE
目前想升级server端版本为2.5.6，client端版本还保持2.5.4会有不兼容的问题吗

### ISSUE THREAD

**Issue by ybqiang** [alibaba/dubbo#739]
目前想升级server端版本为2.5.6，client端版本还保持2.5.4会有不兼容的问题吗

**Comment by chickenlj** [comment]
不会存在兼容问题。如果使用netty4模块，请注意阅读[配置说明](https://dubbo.gitbooks.io/dubbo-user-book/content/demos/netty4.html)
