### ISSUE TITLE
绑定阿里云弹性外网IP失败

### ISSUE THREAD

**Issue by nice2mu** [alibaba/dubbo#742]
RT
我的服务是通过外网调用的.   

在服务注册的时候 没有指定host 那么获取是的内网的地址  注册到ZK 就是内网地址   但是我的服务调用方和提供方不是在一个内网.

但是我配置成外网地址的话netty绑定不上, 因为压根没这个外网网卡.

-----------------------------

所以能不能像类似Kafka一样 有一个
listeners=PLAINTEXT://0.0.0.0:9092
advertised.listeners=PLAINTEXT://124.222.122.17:9092

一个是监听的地址  一个是注册到ZK的地址

**Comment by nice2mu** [comment]
看了下隔壁motan的   是直接绑定0.0.0.0的
serverChannel = bootstrap.bind(new InetSocketAddress(url.getPort()));

在netty绑定的时候 配置的 host 完全没用  host配置是注册用的. 


感觉这个需求还是合理的.

**Comment by chickenlj** [comment]
[dubbo-docker-sample](https://github.com/alibaba/dubbo/wiki/dubbo-docker-sample)
提供示例使用方式，是否能满足你的场景？

**Comment by nice2mu** [comment]
满足!!!

dubbo.properties也能支持下不   然后 JAVA_OPTS也支持这个参数   定个优先级.

**Comment by chickenlj** [comment]
xml通过<dubbo:protocol host="" port="" />配置
properties通过dubbo.protocol.host="" dubbo.protocol.port=""

**Comment by chickenlj** [comment]
经过讨论，我们觉得通过系统环境变量传递配置要比jdk系统变量更合理一些，我会在这里再修改一下 #763
