### ISSUE TITLE
管控台出现”警告: 多个不同应用注册了相同服务”

### ISSUE THREAD

**Issue by devcooperation** [alibaba/dubbo#746]
在
![qq 20171017175519](https://user-images.githubusercontent.com/9998177/31658724-665098dc-b364-11e7-9c6a-0c3289c8d15d.png)
![qq 20171017175525](https://user-images.githubusercontent.com/9998177/31658725-6697b3fc-b364-11e7-8a1b-21e2fcc99806.png)
但是是不同的应用（应用名称也是不一样的，其中也没有相同的服务）注册到一个zk集群中出现的，这个是什么问题呢？是管控台的bug么？ 谢谢~

**Comment by boylong12** [comment]
[这是管控台的一个bug，貌似现在已经改了，应该是会下个版本中放出去。可以参考](https://github.com/alibaba/dubbo/issues/714)

**Comment by chickenlj** [comment]
是ops bug，重复问题关闭掉了
