### ISSUE TITLE
rest支持以及一个路由问题

### ISSUE THREAD

**Issue by Just-CJ** [alibaba/dubbo#747]
首先是rest支持，我们之前一直使用dubbox，rest的功能对我们来说比较重要，不知道什么时候能够正式支持。
然后我们之前基于dubbox开发了一个api网关，支持服务发现，但是本质上是使用httpclient做的代理转发请求，dubbo本身提供的路由功能无法使用，想问问这块有没有什么好的建议？

**Comment by chickenlj** [comment]
rest预计会在2.5.8版本支持，大概在11月底吧

如果网关本身也是java语言的，用dubbo来做后端请求的调用是可以利用dubbo提供的路由功能的；如果用httpclient来做请求转发的话，只能用Nginx等LB 代理提供的路由等功能了

**Comment by Just-CJ** [comment]
@chickenlj 不用httpClient做的话，能想到的方案只有把网关做成一个rest provider+consumer，异构客户端调用网关的rest接口，网关内部作为consumer调用其他服务，但是感觉这样的实现太重了，没有httpClient代理的实现轻便。
另，不知道在rest正式支持以后会不会提供一个官方的网关实现，支持服务发现、负载均衡、路由等等功能？

**Comment by Just-CJ** [comment]
@chickenlj 补充一下，我们希望的是使用基于httpclient实现的网关，但是可以直接支持dubbo自带的路由功能

**Comment by chickenlj** [comment]
@Just-CJ  网关不依赖dubbo的话，只能用其他类似第三方代理方案了，http的跨语言方案目前在服务治理层面比较弱，spring cloud有一整套的方案但是dubbo并没有适配

**Comment by chickenlj** [comment]
REST has been released in [2.6.0](https://github.com/alibaba/dubbo/releases).
