### ISSUE TITLE
当前AnnotationBean注解配置方式的问题

### ISSUE THREAD

**Issue by chickenlj** [alibaba/dubbo#750]
当前收集到的问题如下：
1. dubbo service与transactional同时使用，服务无法正常暴露。  
 @Service注解增加@Inherited；
 使用AopUtil.getTargetClass()方法  

2. 消费端代理对象未被spring托管，无法aop

3. AnnotationBean postprocessor如在transaction postprocessor之前执行，导致provider代理不能调用aop后的对象

4. @Reference用在父类属性，无法正常注入

5. 目前@Service的配置支持不完善（未读取），可在后续版本完善

6. @Service传递@Component，可删除原scanpackage配置处理的代码

**Comment by chickenlj** [comment]
也可考虑改用BeanFactoryPostProcessor注册BeanDefinition的方式重构

**Comment by mercyblitz** [comment]
我把这个 Annotation 的问题，单独罗列出来！
