### ISSUE TITLE
dubboAdmin服务列表与应用注册服务出现不统一现象

### ISSUE THREAD

**Issue by liguoxijob** [alibaba/dubbo#751]
比如当一个应用启动后，zookeeper配置中心中会注册一些服务，但是当该应用停止后，dubboAdmin中服务提供者列表仍然会显示这些服务，请问这是什么原因？是延迟吗？

**Comment by chickenlj** [comment]
是dubbo-admin同步注册中心存在bug，导致未及时更新，当前需重启dubbo-admin解决

**Comment by liguoxijob** [comment]
你好，dubbo-admin同步注册中心的bug已经修复了没？

**Comment by imxig** [comment]
@chickenlj 你好，dubbo-admin同步注册中心的bug已经修复了没？
