### ISSUE TITLE
dubbo-admin的旧版能兼容新版本的dubbbo么

### ISSUE THREAD

**Issue by DayuZhu** [alibaba/dubbo#754]
dubbo-admin的2.5.3 版本能兼容 dubbo-2.5.5不？

**Comment by chickenlj** [comment]
可以兼容

**Comment by jxw1989** [comment]
dubbo2.6.5 不兼容 dubbo2.4.9   
接口调用抛 Decode rpc result failed: invalid stream header: 77020101异常
