### ISSUE TITLE
请问这个版本的序列化支持kryo吗

### ISSUE THREAD

**Issue by zijianlee** [alibaba/dubbo#764]
你好，想问下请问2.5.6这个版本的dubbo序列化支持kryo吗?还是说未改变，还是默认的hessian2

**Comment by chickenlj** [comment]
2.5.6版本序列化协议类型未变更，只是对hessian2做了jdk8类型的支持。

新的序列化协议本身是容易扩展的，包括使用者自行通过SPI扩展也可以，所以我们在想官方提供更多种序列化协议支持的必要性。很多遗留系统从hessian2迁移到新的序列化协议会有较大回归测试成本（如不同协议对字段不匹配的处理不同），你们应该也是一些全新的系统或接口会有使用新序列化协议的诉求吧？

**Comment by zijianlee** [comment]
有这方面的诉求，kryo比hessian2更高效一些。但是框架本身要兼顾很多，理解你们的选择.

**Comment by bwzhang2011** [comment]
@chickenlj ， 希望增加这方面支持，dubbox在这边做一些增强，dubbo可以整合官方的版本，供大家扩展

**Comment by kimmking** [comment]
用这个版本吧 https://github.com/kimmking/dubbo
@zijianlee

**Comment by superleo-cn** [comment]
希望能够尽快支持Kryo或者FST，现在我们是重度使用Scala+Dubbo。默认的Java序列化和Hessian2都支持的不好。

**Comment by Authorlove** [comment]
@kimmking 您可以提相关PR吗，非常期待

**Comment by kirbylynx** [comment]
自己参考dubbox的实现，自己扩展一个kryo的序列化支持并不麻烦，不过当然官方支持了更好。

**Comment by chickenlj** [comment]
The core features of this PR have been published in [2.6.0](https://github.com/alibaba/dubbo/releases/tag/dubbo-2.6.0)
