### ISSUE TITLE
http://code.alibabatech.com无法访问

### ISSUE THREAD

**Issue by magicsilence** [alibaba/dubbo#77]
xml报错， 是否有其他地址？

**Comment by zhangyijun** [comment]
请问这个问题是否能解决一下？或把关联jar更新到mavenrepository去？几乎所有人在第一步就Fail，而且目前基本上没有解决办法。

**Comment by stopme** [comment]
又开始更新了哦

**Comment by beiwei30** [comment]
not an issue any longer
