### ISSUE TITLE
有人遇到过在servlet中调用dubbo服务，使用注解报空吗？？？

### ISSUE THREAD

**Issue by Lhs9323** [alibaba/dubbo#770]
//servlet代码如下
public class WorkServlet extends HttpServlet {
@Reference(interfaceName = "com.hlink.base.service.CacheService")
private CacheService cacheService;
@Reference(interfaceName = "com.hlink.userFile.Service.UserFileService")
private UserFileService userFileService;
private static final Logger logger = Logger.getLogger(WorkServlet .class);
@Override
public void service(ServletRequest request, ServletResponse response) throws ServletException,   IOException {
logger .info(cacheService);
cacheService.setStringValue("key","value");
   }
}

spring-bean.xml配置：
      
	<dubbo:application name="dubbo-gateway-http-front" />
	
	<dubbo:registry id="dubbo_registry" address="${dubbo.registry.address}" />
	
	<dubbo:protocol name="dubbo" port="18086" dispatcher="all"
		threadpool="fixed" threads="100" />
<dubbo:annotation package="com.XXX.gate.http.servlet"></dubbo:annotation>//在配置文件中直接扫描servlet包路径

web.xml配置

  
      <servlet>
    <servlet-name>headHandlerServlet</servlet-name>
   <servlet-class>com.XXX.gate.http.servlet.WorkServlet</servlet-class>
  </servlet>
  <servlet-mapping>
    <servlet-name>headHandlerServlet</servlet-name>
    <url-pattern>/uploadFile</url-pattern>
  </servlet-mapping>

  <context-param>
    <param-name>contextConfigLocation</param-name>
    <param-value>classpath:applicationContext.xml</param-value>
  </context-param>
不知道为什么引用失败
因为服务提供方的配置是确认没问题的，在非servlet中调用都没有问题

**Comment by mercyblitz** [comment]
可以尝试扩展 HttpServletBean

**Comment by Gonzo-Tan** [comment]
如果没记错的话，servlet默认不属于spring容器的bean， 所以你这个注解是不被扫描的。
可以将这个servlet使用spring的方式 ServletRegistrationBean 来把这个servlet注册到spring容器里...

**Comment by chickenlj** [comment]
参考 @mercyblitz  @Gonzo-Tan 的回复，要使用spring作用域内的实现才可以
