### ISSUE TITLE
monitor没有收集到version和group参数

### ISSUE THREAD

**Issue by linhaolin1** [alibaba/dubbo#774]
要如何配置才能让monitor收集到相应调用的version和group信息
是否只能为每个版本增加一个monitor配置？
dubbo版本2.5.5

**Comment by chickenlj** [comment]
可以考虑MonitorService也做version、version区分，monitor数据由匹配的MonitorService接收
```xml
<dubbo:monitor group="" version="" />
```

**Comment by linhaolin1** [comment]
好像一个Monitor项目多挂几个带version的Monitor实例也能接受的感觉。。
谢谢。
