### ISSUE TITLE
客户端发起请求时的超时时间,是否可以做成可刷新的？

### ISSUE THREAD

**Issue by linghushaoxia** [alibaba/dubbo#785]
客户端调用服务的timeout配置，是写死在xml配置文件中的，在实际应用中，存在一些情况，需要对超时控制进行调整的情况，比如系统压力大的时候，可能会考虑超时时间短一些。实际上，究竟超时时间多长合适，这是需要动态计算的，而不是一个固定不变的值。
为此，我想对这一块提出一些改进
## 1、 timeout超时时长，可以手动刷新
可配置，timeout=package.class@field这种格式的配置，发起调用时，取用户指定的值，这样配置刷新后超时值跟着变化。
## 2、timeout有系统单独的模块进行动态计算
可以对某一段时间内的超时时间，通过一定的算法计算得到值Tx，Tmin<=Tx <=Tmax
第一点，我实验了一下，是可以的。具体代码在[https://github.com/linghushaoxia/dubbo](https://github.com/linghushaoxia/dubbo)
在dubbo-demo中包含测试用例。
请问，是否可以考虑该提议？

**Comment by chickenlj** [comment]
dubbo支持一些参数的动态调整，timeout是一个典型场景，具体使用请查阅文档，dubbo-admin的ops页面也提供了基本的操作入口

另，我们正计划对动态参数配置部分进行优化与重构，做到配置和注册中心分离，接入更通用的开源分布式配置框架

**Comment by linghushaoxia** [comment]
@chickenlj 谢谢您在百忙之中，对问题进行回复。请问，计划使用什么配置框架，我对着快挺感兴趣的，能否透露一点点，我也研究下。

**Comment by chickenlj** [comment]
@linghushaoxia  比如开源的有diamond disconf archaius这些，还有spring cloud config的方案
