### ISSUE TITLE
异步调用传递bug

### ISSUE THREAD

**Issue by holygost** [alibaba/dubbo#789]
看到一篇说异步调用有坑，请问这个问题官方解决了吗？

场景描述：客户端远程异步调用ServiceA，ServiceA在处理客户端请求的过程中需要远程同步调用ServiceB，ServiceA从ServiceB的响应中取数据时，得到的是null，对就是这个坑。

文章如下：
http://www.jianshu.com/p/abe04c8e4549

dubbox里面提交的方案：
https://github.com/dangdangdotcom/dubbox/pull/349/commits

**Comment by chickenlj** [comment]
此问题已经修复，请升级到最新版本dubbo。
另，我们计划在下面1-2个维护版本中优化dubbo的异步调用实现方案

**Comment by AngryApe** [comment]
@chickenlj 请问下具体是那个版本里修复的，我看了releaselog ，说是2.5.4就解决了，用2.6.0还是有bug

**Comment by jianpeng957** [comment]
问题修复了吗？好像还没把，version:2.7.6
