### ISSUE TITLE
Exception when scan the timeout invocation of remoting.

### ISSUE THREAD

**Issue by yxxstar** [alibaba/dubbo#797]
当dubbo超时请求，一直会刷那个日志不停。。报空指针异常
private static class RemotingInvocationTimeoutScan implements Runnable {

        public void run() {
            while (true) {
                try {
                    for (DefaultFuture future : FUTURES.values()) {
                        if (future == null || future.isDone()) {
                            continue;
                        }
                        if (System.currentTimeMillis() - future.getStartTimestamp() > future.getTimeout()) {
                            // create exception response.
                            Response timeoutResponse = new Response(future.getId());
                            // set timeout status.
                            timeoutResponse.setStatus(future.isSent() ? Response.SERVER_TIMEOUT : Response.CLIENT_TIMEOUT);
                            timeoutResponse.setErrorMessage(future.getTimeoutMessage(true));
                            // handle response.
                            DefaultFuture.received(future.getChannel(), timeoutResponse);
                        }
                    }
                    Thread.sleep(30);
                } catch (Throwable e) {
                    logger.error("Exception when scan the timeout invocation of remoting.", e);
                }
            }
        }
    }

**Comment by chickenlj** [comment]
详细异常堆栈能贴一下吗

**Comment by chickenlj** [comment]
用的什么版本的dubbo？如果你这找到了详细的堆栈，可以再打开issue
#459 参考下和这个issue有没有关联
