### ISSUE TITLE
dubbo能不能支持restful协议

### ISSUE THREAD

**Issue by egemmer** [alibaba/dubbo#801]
restful作web服务实现简单，没有代码侵入，不需要接口包的依赖，只要约定好服务参数格式。

**Comment by chickenlj** [comment]
restful相关的调研和支持，我们已经安排在2.5.8版本计划中

**Comment by kimmking** [comment]
good news

**Comment by wu191287278** [comment]
可以考虑把springmvc 添加进去，https://github.com/wu191287278/dubbo/tree/master/dubbo-rpc/dubbo-rpc-springmvc

**Comment by chickenlj** [comment]
@wu191287278  Excellent job，我们会做为重点参考

**Comment by devenfan** [comment]
@chickenlj 不建议参考 @wu191287278 的实现， 该REST实现让Dubbo耦合SpringMVC和SpringBoot，会让dubbo 框架本身变得沉重不堪，并丧失与SpringCloud的竞争力。仅仅实现REST协议，还是推荐使用Dubbox的方式，采用符合JAX-RS标准的RESTEasy。
