### ISSUE TITLE
dubboAdmin屏蔽服务后，不能恢复吗？？？

### ISSUE THREAD

**Issue by liguoxijob** [alibaba/dubbo#807]
dubboAdmin存在这样一个问题：屏蔽服务后，不能恢复。请问这个问题有做修复吗？

**Comment by chickenlj** [comment]
用的是哪个版本的dubbo-admin?

**Comment by chickenlj** [comment]
2.5.7版本会修复掉。dubbo-admin模块我们准备进行重构，但目前还没有具体的时间计划

**Comment by cgf120** [comment]
直接修改根目录下的pom.xml 中的url为https://github.com/alibaba/dubbo就好了

**Comment by liguoxijob** [comment]
用的版本是2.5.3
好的，期待2.5.7和支持restful的dubbo版本，赞

**Comment by liguoxijob** [comment]
@cgf120 是这个地址：http://code.alibabatech.com/wiki/display/dubbo 改为：https://github.com/alibaba/dubbo吗？

**Comment by chickenlj** [comment]
@liguoxijob  你这个问题应该在2.5.6版本已经修复掉了
