### ISSUE TITLE
createPersistent方法未实现ACL

### ISSUE THREAD

**Issue by deo-prime** [alibaba/dubbo#811]
com.alibaba.dubbo.remoting.zookeeper.zkclient.ZkclientZookeeperClient.createPersistent(String path)方法的实现中忽略的ACL的信息, 导致在dubbo.xml中配置的registry设置的zookeeper连接用户名和密码不起作用, 进而无法访问ACL管理的zookeeper.

**Comment by deo-prime** [comment]
@chickenlj

**Comment by deo-prime** [comment]
设置客户端为curator时问题解决.

**Comment by chickenlj** [comment]
你是说zkclient未读取url中的认证信息吗？
有一些使用者已经反映过注册中心认证的问题，我们在2.5.8版本安排集中处理下

**Comment by deo-prime** [comment]
在使用默认的zookeeper客户端（101tec）时，以下的用户名和密码配置未被提交到zookeeper
```
<dubbo:registry address="zookeeper://localhost:2181" check="false" username="xxx" password="xxx"></dubbo:registry>
```

**Comment by chickenlj** [comment]
Finally, it turns out zkclient don't support authority. 
If your ZK opened ACL, please use curator instead.
