### ISSUE TITLE
admin支持java8了吗？

### ISSUE THREAD

**Issue by zxj19951029** [alibaba/dubbo#812]
之前你们的语法不规范，导致tomcat启动不起来的问题解决了吗

**Comment by chickenlj** [comment]
能说下之前在jdk1.8下具体哪里有问题吗？
2.5.7版本修复了一个jdk1.8下部署的问题:  #202 ，不知和你所说是否同一问题

**Comment by zxj19951029** [comment]
试过了，已经支持了
