### ISSUE TITLE
[version-2.5.7]切换spring版本为3.2.18.RELEASE版本编译不过

### ISSUE THREAD

**Issue by crazyhuntsman** [alibaba/dubbo#813]
dubbo-config-spring编译失败

DubboComponentScan.java[6,42]错误：找不到符号
DubboComponentScan.java[32,5]错误：找不到符号
DubboComponentScan.java[44,5]错误：找不到符号
ReferenceAnnotationBeanPostProcessor.java[35,49]错误：找不到符号
ReferenceAnnotationBeanPostProcessor.java[35,0]错误：仅从类和接口静态导入

**Comment by mercyblitz** [comment]
`@DubboComponentScan` 使 Spring Framework 4.2 的 `AliasFor`

**Comment by mercyblitz** [comment]
Spring 官方已经不再维护 3.2.x 版本，建议升级 Spring 到 4.2.x

**Comment by crazyhuntsman** [comment]
主要是我们的服务不是我们一个团队使用，涉及公司内部其它产品线，目前大家所使用的版本基本还在SPRING3，如果要升级就要协调所有产品线，这个工作量有点，而且能不能成还是个问题

**Comment by Leviathans** [comment]
都啥年代了

**Comment by halober** [comment]
可以换回dubbox了，bug少并且稳定，依赖是SPRING3

**Comment by mercyblitz** [comment]
@crazyhuntsman 这个问题会在 2.5.8 中兼容，参考 #17

**Comment by 663534597** [comment]
@mercyblitz   这个问题貌似在   Spring 4.3.10  版本下也会存在，我今天遇到了
#850

**Comment by crazyhuntsman** [comment]
@mercyblitz 能哭吗。我已经切成4.3.12版本，编译通过，已更新至项目。

**Comment by mercyblitz** [comment]
@crazyhuntsman 挺好的，毕竟官方也不维护了，高版本自然有更多好的特性
