### ISSUE TITLE
关于REST的支持、异常国际化（参数验证、自定义异常等）需求

### ISSUE THREAD

**Issue by crazyhuntsman** [alibaba/dubbo#814]
目前，我是参考dubbox的REST实现，在2.5.6上去实现了REST的服务发布，并集成了HTTPS功能（给IOS设备调的）。
必竟是我自己集成的，总感觉水平不够，希望专家们能够实现一套。

另外希望能够实现DUBBO框架对一些国际化的支持。

**Comment by mercyblitz** [comment]
目前正在调研
