### ISSUE TITLE
通过API编程方式注册服务

### ISSUE THREAD

**Issue by 663534597** [alibaba/dubbo#821]
通过API编程方式注册/消费服务，服务提供者/消费者下线后，在dubbo-admin上还能看到。且服务状态显示正常。

**Comment by chickenlj** [comment]
这可能是dubbo-admin自身的问题，未能及时更新自身缓存。
我们在2.5.8版本会集中修复一下dubbo-admin存在的问题

**Comment by willlau0524** [comment]
赞效率
