### ISSUE TITLE
关于多网卡环境的服务地址注册

### ISSUE THREAD

**Issue by crazyhuntsman** [alibaba/dubbo#823]
我的环境：
网卡1：172.21.2109（内网，连通状态）
网卡2：60.12.11.50（外网，未接通状态）
使用DUBBO协议发布服务时，Netty开启服务时选用了外网的IP，所以注册到zookeeper时显示外网IP。根据“主机绑定”设置host=内网，发现其实Netty还是选用的外网的IP，只是发布到zookeeper时使用了host配置的内网IP。这样消息端通过zookeeper调用服务时，报错无法访问。

我想问下，有没有什么好的办法能够内外网都可以访问。用C++写服务时，一般都是以0.0.0.0这样的IP绑定TCP或UDP端口的，当然是在IPV4环境下。

**Comment by chickenlj** [comment]
可以考虑修改主机`/etc/hosts`配置，通过 `hostname-外网ip` 指定注册用地址为外网地址，此时dubbo监听0.0.0.0的所有可用ip；

目前也支持启动参数明确指定注册、绑定ip地址与端口，参考[这里](https://github.com/dubbo/dubbo-docker-sample)。对于你的场景，可以只指定注册地址为外网ip，dubbo会自动监听听0.0.0.0的所有可用ip
