### ISSUE TITLE
2.5.7版本不使用spring boot时注解方式如何配置？？？

### ISSUE THREAD

**Issue by li362692680** [alibaba/dubbo#824]
官方样例中的注解方式样例是使用spring boot方式启动，配置的@DubboComponentScan扫描包，不使用spring boot的时候应该把这个注解写在什么地方？每个提供者和每个消费者类名上都要配置这个注解么？？

**Comment by 663534597** [comment]
第一步：
@Configuration
@ComponentScan( basePackages = { "/com.xxxx.**.provider" }, useDefaultFilters = false, includeFilters = {
        @ComponentScan.Filter( type = FilterType.ANNOTATION, value = Service.class )
} )
public class DubboSOAConfig {
    @Bean
    public AnnotationBean AnnotationBean() {
//		AnnotationBean annotationBean = new AnnotationBean();
//		annotationBean.setPackage(DEFAULT_SCAN_PACKAGE);
//		return annotationBean;
        return new AnnotationBean();
    }
}

第二步：服务暴露
package com.xxx.fusion.route.submerc.provider;

import com.alibaba.dubbo.config.annotation.Service;
import com.xxx.fusion.route.submerc.api.IRouteSubmercService;
import com.icitic.fusion.route.submerc.service.RouteSubMercImpl;
import org.springframework.beans.factory.annotation.Autowired;

@Service(version = "1.0.0", group="WX")
public class RouteSubMercServiceProvider implements IRouteSubmercService {

    @Autowired
    private RouteSubMercImpl routeSubmerc;

    @Override
    public AvailableResult<RTMercAddResVO> addMerc(RTMercAddReqVO rtMercAddReqVO) {
        return routeSubmerc.addMerc(rtMercAddReqVO);
    }
}

第三步：服务引用
package com.xxx.fusion.route.submerc.service;

import com.alibaba.dubbo.config.annotation.Reference;
import com.xxx.fusion.route.submerc.api.IRouteSubmercService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * 路由通道服务商户进谏模块
 * Created by sunny on 2017-08-16.
 */
@Component
public class RouteSubMercImpl {

    private static Logger logger = LoggerFactory.getLogger(RouteSubMercImpl.class);

    @Reference(version = "1.0.0", group="WX")
    private IRouteSubmercService routeSubmercService;

    public AvailableResult<RTMercAddResVO> addMerc(RTMercAddReqVO rtMercAddReqVO) {
		...
		routeSubmercService.xxxx();
		...
	}
}

**Comment by mercyblitz** [comment]
参考这个实现：

https://github.com/alibaba/dubbo/blob/master/dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/context/annotation/provider/ProviderConfiguration.java

**Comment by mercyblitz** [comment]
或者：
```java

@DubboComponentScan(basePackages = "com.alibaba.dubbo.config.spring.context.annotation")
@ImportResource("META-INF/spring/dubbo-annotation-provider.xml")
public class ProviderConfiguration {


}
```

**Comment by li362692680** [comment]
@mercyblitz 

你好，我的提供者这端是这么写的

package com.fominfo.custsrv.system.provider.user.service;

import org.springframework.stereotype.Component;
import com.alibaba.dubbo.config.annotation.Service;
import com.fominfo.custsrv.system.api.user.entity.UserEntity;
import com.fominfo.custsrv.system.api.user.service.UserServiceI;
import com.fominfo.custsrv.system.provider.user.dao.UserDao;
import com.fominfo.frame.provider.common.service.BaseService;

@Service(version="2.5.7",application="custrv-provider",protocol="dubbo",registry="my-registry")
@Component("userService")
public class UserService extends BaseService<UserDao,UserEntity> implements UserServiceI{
}

配置类是这么写的：

package com.fominfo.frame.provider.common.config;

import org.springframework.context.annotation.ImportResource;
import com.alibaba.dubbo.config.spring.context.annotation.DubboComponentScan;

@DubboComponentScan(basePackages="com.fominfo.custsrv.system.provider.user.service")
@ImportResource("classpath*:META-INF/spring/visit-dubbo.xml")
public class ProviderConfiguration{
}

visit-dubbo.xml  这个文件是这么写的：

<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:dubbo="http://code.alibabatech.com/schema/dubbo"
    xsi:schemaLocation="http://www.springframework.org/schema/beans          
    http://www.springframework.org/schema/beans/spring-beans.xsd          
    http://code.alibabatech.com/schema/dubbo          
    http://code.alibabatech.com/schema/dubbo/dubbo.xsd">

    
    <dubbo:application name="custsrv-provider" />

    
    <dubbo:registry id="my-registry" address="zookeeper://127.0.0.1:2181" />

	 
	
    <dubbo:protocol name="dubbo" port="20880" />
    
    <dubbo:provider filter="dubboFilter"/>

</beans>  

tomcat 启动的时候日志显示没有扫描到@service注解

DubboComponentScanRegistrar-85]-[main]-[INFO] 0 annotated @Service Components { [] } were scanned under package[com.neusoft.custsrv.system.provider.user.service]

**Comment by li362692680** [comment]
@mercyblitz  

找到问题了，是default-lazy-init="true" 的原因

**Comment by chickenlj** [comment]
```java
@dubbocomponentscan(basePackages="com.fominfo.custsrv.system.provider.user.service")
@importresource("classpath*:META-INF/spring/visit-dubbo.xml")
public class ProviderConfiguration{
}
```

这里是不是少一个`@Configuration`配置
