### ISSUE TITLE
No such extension com.alibaba.dubbo.common.serialize.Serialization by name json

### ISSUE THREAD

**Issue by william8188** [alibaba/dubbo#826]
There is an error show up while I upgrade my dubbo from v2.5.3 to v2.5.7.

`com.alibaba.dubbo.remoting.RemotingException: Failed to send message Request [id=407, version=2.0.0, twoway=true, event=true, broken=false, data=null] to /10.170.116.237:55161, cause: No such extension com.alibaba.dubbo.common.serialize.Serialization by name json`

I use protocol setting below:
` <dubbo:protocol name="dubbo" port="20400" serialization="json"/>`

Before upgrading version, every things run very well.
But After that, this error I mention above is almost killing me.
Please, help me to resolve this issue. thank you.

**Comment by chickenlj** [comment]
'json' extension has been removed in v2.5.7, because this inner implementation turns out to have some bugs, and also we won't have some resources maintaining.

It is recommend that you use fastjson instead:
<dubbo:protocol name="dubbo" port="20400" serialization="fastjson"/>

**Comment by chickenlj** [comment]
If you have to use this `json` extension, you can add a `com.alibaba.dubbo.common.serialize.Serialization` file with this content under you classpath:
```properties
json=com.alibaba.dubbo.common.serialize.support.dubbo.JsonSerialization
```

**Comment by william8188** [comment]
Well, it works for me. 
Thank you bro @chickenlj
