### ISSUE TITLE
DUBBO_IP_TO_BIND建议不要限制绑定localhost、127.0.0.1

### ISSUE THREAD

**Issue by lizhiling12345** [alibaba/dubbo#836]
建议不要限制绑定localhost、127.0.0.1，我们现在有一种场景是连VPN开发的，自动获取的ip经常造成调用不了，所以只能改源码，直接用127.0.0.1发布服务

**Comment by chickenlj** [comment]
DUBBO_IP_TO_BIND目前是做了127.0.0.1的限制。如果你不配置DUBBO_IP_TO_BIND，是会自动绑定0.0.0.0的，也就能解决127.0.0.1的问题
