### ISSUE TITLE
dubbo2.5.6版本集成spring-boot服务提供者下线，服务消费者监听不到问题

### ISSUE THREAD

**Issue by onebyte0755** [alibaba/dubbo#837]
之前用dubbo2.5.3版本集成springboot发现服务提供者下线停掉之后，服务消费者使用的Reference注解用到的Service会报空指针异常，以为2.5.4版本解决了优雅停机应该在服务提供者停掉后会通知到zk，服务消费者可以获取到该服务提供者已经下线了，就不会调用该服务的问题，哪怕升级到2.5.6版本还是依然存在

**Comment by chickenlj** [comment]
是所有provider服务都下线了吗？是`Reference注解的属性为空` 还是 `调用到了已经下线的provider`，能否贴一下详细的异常栈

**Comment by onebyte0755** [comment]
首先如果先启动服务提供者，在启动服务消费者，服务消费者使用的reference注解的service是可以正常调用的，如果服务提供者突然停掉，服务消费者就会报空指针异常，之前reference注解的service那里报的，被reference注解的service是空

**Comment by genghaizhou** [comment]
我碰到和 onebyte0755 相同的问题, 这个问题和启动顺序有关
sping-boot后启动provider, consumer可以收到zk通知, 但是并没有更新上下文中的service

**Comment by chickenlj** [comment]
@onebyte0755 @genghaizhou
我验证过并未发现两位提到的问题，能发一下具体的异常堆栈吗？有没有配置check="false"

**Comment by onebyte0755** [comment]
我的boot对dubbo初始化代码里注册中心的setCheck设置成了false，consume的是没有设置setCheck为false，有可能是这里导致的，我试试;平时大家都喜欢咋玩？都用默认的还是都设置成false?

**Comment by chickenlj** [comment]
没设置check=false，无provider会在启动阶段被终止。我先关闭此问题了
