### ISSUE TITLE
dubbo 能否提供一些比较好的分布式事务模块支持？

### ISSUE THREAD

**Issue by onebyte0755** [alibaba/dubbo#839]
目前有一些开源的分布式事务支持的框架，不敢用，官方用户手册也只是一笔带过没啥详尽的描述如果有分布式事务场景如何实现

**Comment by lovepoem** [comment]
dubbo专注于rpc，可以不用考虑这个事情。分布式事务是一个独立的需求，可以用专门的组件来做。一般如:消息事务加一致性,TCC等

**Comment by chickenlj** [comment]
如lovepoem所说，dubbo还没规划提供一致性方面的支持

**Comment by 1991wangliang** [comment]
那我就自己推荐一个吧，https://github.com/codingapi/tx-lcn 开源的分布式事务框架
