### ISSUE TITLE
关于负载均衡的问题

### ISSUE THREAD

**Issue by wangxiaobai83** [alibaba/dubbo#841]
这个负载均衡加载服务端和客户端有什么区别么？

**Comment by wangxiaobai83** [comment]
文档上说在服务端和客户端 配置都可以。如果在服务端配置，有些不太能够理解

**Comment by chickenlj** [comment]
两端没有什么区别，consumer端优先级更高，如你所说确实是在consumer端配置更容易理解一些；
provider如果做了配置，配置会通过注册中心同步到consumer

**Comment by wangxiaobai83** [comment]
@chickenlj 非常感谢你的回答，假设有三台能够提供一样服务的服务端，这时consumer会采用那种配置呢？

**Comment by chickenlj** [comment]
@wangxiaobai83  实践上我们是预期三台provider都有同样的loadbalance配置的，所以依旧会按照consumer->provider的优先级执行
