### ISSUE TITLE
发现一个注册服务的BUG

### ISSUE THREAD

**Issue by zxj19951029** [alibaba/dubbo#843]
![bug](https://user-images.githubusercontent.com/18377791/32688699-cb4f6bae-c710-11e7-9818-b54dea105bb8.png)
如上图所示，上图的代码，是无法注册成为dubbo的服务的，搞了好久。最后发现，是命名出了问题，我把它改为如下的命名就好了
![real](https://user-images.githubusercontent.com/18377791/32688708-f8fdae8a-c710-11e7-8b1b-89cc980d78f6.png)

我不知道你们的有没有问题，我是从git上面clone的代码install的。命令中带有Java的，都无法扫描成为服务

**Comment by chickenlj** [comment]
这是个蹊跷的问题，你用的是dubbo什么版本？

**Comment by 663534597** [comment]
这应该是用法有问题

**Comment by zxj19951029** [comment]
就是当前版本，刚从github上面glone下来的

**Comment by foreveryang321** [comment]
@chickenlj  dubbo 2.5.7版本
我在使用过程中也发现，当一个类同时使用dubbo的@service，和spring的@compent、@service等时，无法注册dubbo服务

**Comment by crazyhuntsman** [comment]
@foreveryang321 我可以用呢2.5.7。

**Comment by mercyblitz** [comment]
@crazyhuntsman  这个问题会在 2.5.8 版本里面修复掉

**Comment by chickenlj** [comment]
@foreveryang321 2.5.7版本目前不支持同时使用Spring Service注解和dubbo service注解，你的这种场景，再定义一个外层Facade的包装类型，在只上做dubbo service注解是否更合理一些

**Comment by mercyblitz** [comment]
@zxj19951029 你这个问题我本地没有发现，能不能上传一段 demo code

**Comment by chickenlj** [comment]
This seems to be a problem, we should fix it in 2.5.8. When i add `ComponentScan` to your test, this happens
![default](https://user-images.githubusercontent.com/18097545/33834637-8aa43268-debe-11e7-9b83-58d53990b940.png)

**Comment by chickenlj** [comment]
`ServiceAnnotationBeanPostProcessor` should always execute behind `Transactional PostProcessor`, should we give `ServiceAnnotationBeanPostProcessor` the lowest order explicitly?

**Comment by chickenlj** [comment]
#1029
