### ISSUE TITLE
2.5.7 telnet 调用接口，json格式转换出错。（2.5.3正常）

### ISSUE THREAD

**Issue by foamfish** [alibaba/dubbo#844]
Invalid json argument, cause: com/alibaba/fastjson/JSON

**Comment by chickenlj** [comment]
cause：部分能否补全？
2.5.7的telnet功能需要fastjson依赖，请先检查工程是否有fastjson依赖？

**Comment by chickenlj** [comment]
请优先检查fastjson依赖，我先close了，有问题再打开
