### ISSUE TITLE
关于协议注册问题

### ISSUE THREAD

**Issue by 663534597** [alibaba/dubbo#845]
请教下，能否通过 dubbo  把应用容器的 IP地址和端口注册到 zookeeper 上呢？

**Comment by chickenlj** [comment]
应用容器是指？
dubbo默认会读取/etc/hosts中的ip注册到zookeeper，2.5.7版本的支持通过环境变量指定注册的ip、port
[参见这里](https://github.com/dubbo/dubbo-docker-sample)

**Comment by 663534597** [comment]
@chickenlj 
我说的应用容器是指Dubbo 通过startup.sh 启动的哪个，也可以理解为 dubbo-container-jetty 这个dubbo服务的main容器，不是docker

**Comment by chickenlj** [comment]
其实指定注册的ip、port本身和是docker或什么容器并没有关系，任何场景都可以手动指定注册用的ip port；
你想注册jetty的地址，应该是想利用jetty的servlet能力了？可以参考文档：dubbo如何以Hessian或http协议暴露服务

**Comment by chickenlj** [comment]
请参考以上回答，我先关闭问题了，有疑问再打开
