### ISSUE TITLE
直接调用出现空指针异常

### ISSUE THREAD

**Issue by dracenliu** [alibaba/dubbo#847]
https://github.com/alibaba/dubbo/blob/6cc5dc189a88c1f266002de763d8eabeae210572/dubbo-simple/dubbo-monitor-simple/src/main/java/com/alibaba/dubbo/monitor/simple/SimpleMonitorService.java#L113

**Comment by chickenlj** [comment]
用的什么dubbo版本？具体堆栈能贴一下吗，这一句怎么会抛异常

**Comment by dracenliu** [comment]
该方法声明为静态公开，但是赋值是在构造方法里面，这里算不算是一个bug

**Comment by chickenlj** [comment]
我也觉得这样是不合理的，我已经修正了。
其实在使用上SimpleMonitorService应该是必须要先实例化的，但是其实例本身并没有好的途径传递出去，好像也不是必须要传递出去。
