### ISSUE TITLE
关于2.5.7版本注解扫描问题

### ISSUE THREAD

**Issue by 663534597** [alibaba/dubbo#850]
使用dubbo2.5.7推荐的注解配置方式后项目打包报错
Spring 4.3.10

@DubboComponentScan(basePackages = { "/com.icitic.**.provider" })

mvn:package   错误信息：
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project fusion-cluster-dubbo: Compilation failure: Compilation failure:
[ERROR] /D:/WORK/icitic/workspace/icitic-microservice-platform-project/fusion-cluster/fusion-cluster-dubbo/src/main/java/com/icitic/fusion/cluster/dubbo/config/DubboSOAConfig.java:[7,58] 程序包com.alibaba.dubbo.config.spring.context.annotation不存在
[ERROR] /D:/WORK/icitic/workspace/icitic-microservice-platform-project/fusion-cluster/fusion-cluster-dubbo/src/main/java/com/icitic/fusion/cluster/dubbo/config/DubboSOAConfig.java:[10,2] 找不到符号
[ERROR] 符号: 类 DubboComponentScan

**Comment by mercyblitz** [comment]
@663534597 这个问题会在 2.5.8 中兼容，请参考 https://github.com/mercyblitz/dubbo/issues/17
