### ISSUE TITLE
dubbo依赖Spring两个版本

### ISSUE THREAD

**Issue by bee06** [alibaba/dubbo#857]
dubbo 依赖Spring两个版本
Maven: org.springframework:spring-aop:3.2.16.RELEASE
Maven: org.springframework:spring-aop:4.3.10.RELEASE
Maven: org.springframework:spring-beans:3.2.16.RELEASE
Maven: org.springframework:spring-beans:4.3.10.RELEASE
Maven: org.springframework:spring-context:3.2.16.RELEASE
Maven: org.springframework:spring-context:4.3.10.RELEASE
Maven: org.springframework:spring-context-support:4.3.10.RELEASE
Maven: org.springframework:spring-core:3.2.16.RELEASE
Maven: org.springframework:spring-core:4.3.10.RELEASE
Maven: org.springframework:spring-expression:4.3.10.RELEASE
Maven: org.springframework:spring-jdbc:4.3.10.RELEASE
Maven: org.springframework:spring-orm:4.3.10.RELEASE
Maven: org.springframework:spring-test:4.3.10.RELEASE
Maven: org.springframework:spring-tx:4.3.10.RELEASE
Maven: org.springframework:spring-web:3.2.16.RELEASE
Maven: org.springframework:spring-web:4.3.10.RELEASE
Maven: org.springframework:spring-webmvc:4.3.10.RELEASE

**Comment by mercyblitz** [comment]
3.2.16 是给 admin 使用，core 依赖了4.3.10.RELEASE

**Comment by chickenlj** [comment]
如mercyblitz所说，admin目前依赖的webx无法兼容spring  4.x版本
