### ISSUE TITLE
springboot消费者  用@configuration注解 配置dubbo <dubbo:reference>，提供者变为null无法注入

### ISSUE THREAD

**Issue by zhuxiujia** [alibaba/dubbo#861]
复现流程=============================
1 springboot消费方  用@configuration注解 配置代替dubbo <dubbo:reference> 内容是
{
  @Bean("demoService")
  @reference
  public DemoService(){
    return demoService;
  }
}
2 先启动消费方，后  启动服务提供方
3调用消费者的时候，服务提供方 demoService 为null,抛出空指针异常。

注=============================
如果是上面的流程中，先启动服务提供方，后  启动消费方，则不会为null

**Comment by chickenlj** [comment]
```java
{
@bean("demoService")
@reference
public DemoService(){
return demoService;
}
}
```
你的这段配置代码看着有些奇怪，怀疑是你使用上有问题，可以把更详细的java文件贴一下

**Comment by zhuxiujia** [comment]
后来检查了下配置，是可以的，这样配置又可以了的。


`
@Configuration
@ImportResource(locations = {"classpath:*.xml"})
public class DubboConfiguration {


    @Reference
    private DemoService demoService;


    @Bean
    public DemoService demoService(){
        return demoService;
    }
}
`
