### ISSUE TITLE
关于Path cannot be null的报错

### ISSUE THREAD

**Issue by tongmintsai** [alibaba/dubbo#870]
在使用zookeeper作为注册中心时，
出现zookeeper事件为NONE时，会报
![image](https://user-images.githubusercontent.com/13182082/32884976-0961161a-caf7-11e7-8f17-90d0273f5e23.png)
错误，我们系统监控时经常发送短信提醒，各位大神有没有好的办法支招啊？

**Comment by tongmintsai** [comment]
![image](https://user-images.githubusercontent.com/13182082/32885101-788a8fda-caf7-11e7-8523-f097e8a87ae5.png)
![image](https://user-images.githubusercontent.com/13182082/32885122-7f78e436-caf7-11e7-8ae7-17dffe8d76f7.png)

**Comment by tongmintsai** [comment]
在event.getPath()时，就会抛出异常

**Comment by RayDuHarry** [comment]
这个我也碰到了。在event类型为close之类的情况下，会出现这个bug。
感觉应该判断一下event类型，在进行通知。’

**Comment by zonghaishang** [comment]
这个是个bug， 以前维护中出现这个问题， @chickenlj  标记待修复吧

**Comment by chickenlj** [comment]
@zonghaishang 收到，具体是什么原因方便文字描述不？这个版本你有时间处理掉吗？

**Comment by zonghaishang** [comment]
CuratorWatcherImpl 中调用 client.getChildren().usingWatcher(this).forPath(event.getPath())， 获取子节点传递的path 为null 导致的，具体为什么会传递null， 需要调试一下代码，应该是zookeeper客户端curator的问题

**Comment by 54hechuan** [comment]
> 
> 
> 这个是个bug， 以前维护中出现这个问题， @chickenlj 标记待修复吧

这个 bug，很可能 引起了一个新的警告，请帮忙处理，相关 issue如下：
https://github.com/apache/incubator-dubbo/issues/4113
