### ISSUE TITLE
ServiceImpl指定使用hessian协议时，通过@Reference发布服务，协议仍为默认协议（dubbo）

### ISSUE THREAD

**Issue by zndo** [alibaba/dubbo#877]
请确认是否存在此问题，谢

**Comment by mercyblitz** [comment]
这应该不是问题，一般而言，@Reference 不应该去感知服务端的实现协议，如果服务端实现了多种协议，反而有点矫枉过正的感觉，因此由客户端自行决定

**Comment by chickenlj** [comment]
如何确定的consumer端仍然为dubbo协议；
如果provider端多协议暴露服务，consumer又没有显示指定要消费的具体协议的情况下，consumer默认是会调用所有协议的provider，如存在多协议的这种场景还是要在consuer端明确指定。
