### ISSUE TITLE
 请问dubbo 里面遇到 hibernate的懒加载 的异常 怎么处理?

### ISSUE THREAD

**Issue by teemoer** [alibaba/dubbo#881]
## 1.如果是把 Hibernate lazy=ture  

这样做在我只需要查单表时，会把所有关联的结果都查到。所以我不希望这样做

请问dubbo有解决方案吗?  我想要的是 可以实现hibernate的 懒加载机制,只有当  我 getSubClass 的时候才会去查询子表,而不是在序列化的时候  getSubClass  返回null之类的

**Comment by yanmushi** [comment]
hibernate的懒加载，是建立在session生命周期中的。

spring为解决在view中使用hibernate懒加载对象，添加了OpenSessionInView的类，来延长session声明周期。这种方案的可行性在于，spring+hibernate是在同一个应用，同一个jvm中。

而，dubbo是通过网络来解决服务通信的。那么延长session并不可行了。
如果在客户端懒加载对象，那么就需要懒加载property的时候，通知服务器端进行查询。如此，可以考虑对客户端程序对model对象进行封装。

**Comment by teemoer** [comment]
十分感谢, 明白了

**Comment by limingwei** [comment]
`java`

public class BudoHessianSerializerFactory extends SerializerFactory {

    public Serializer getSerializer(Class type) throws HessianProtocolException {

        if (PersistentSortedSet.class.isAssignableFrom(type)) {
            return PersistentSortedSetSerializer.INSTANCE;
        }

        if (PersistentSet.class.isAssignableFrom(type)) {
            return PersistentSetSerializer.INSTANCE;
        }

        if (PersistentBag.class.equals(type)) {
            return PersistentBagSerializer.INSTANCE;
        }

        if (PersistentCollection.class.isAssignableFrom(type)) { // PersistentCollection 包含 List Set Map
            return PersistentCollectionSerializer.INSTANCE;
        }

        if (HibernateProxy.class.isAssignableFrom(type)) {
            return HibernateProxySerializer.INSTANCE;
        }

        return super.getSerializer(type);
    }
}
