### ISSUE TITLE
当有多个注册中心，@Reference(registry="test")来指定使用某一个时报错

### ISSUE THREAD

**Issue by halober** [alibaba/dubbo#883]
问题定位，
类com.alibaba.dubbo.config.spring.util.BeanFactoryUtils的67行，方法使用错误。

希望在2.5.8版本发布后可以解决

**Comment by chickenlj** [comment]
是默认使用了第一个registry bean，实际指定的registry不管用？如果是这样的话，我们会尽快在下个版本予以修复

**Comment by mercyblitz** [comment]
谢谢小伙伴定位，该问题会在下个版本中修复

**Comment by halober** [comment]
实际上会直接报错，因为那个方法里边最后有个判断唯一的操作，多个时不唯一了，自然直接报错
