### ISSUE TITLE
希望DUBBO能够支持隐式参数的回传，急需要这个功能

### ISSUE THREAD

**Issue by hsrong** [alibaba/dubbo#895]

**Comment by mercyblitz** [comment]
@hsrong 能否更具体一点？

**Comment by hsrong** [comment]
服务A调用服务B，现在希望服务B通过上下文而不是通过返回值的方式，给服务返回某一个值，如：
public void methodA() {
    methodB();//通过DUBBO调用服务B
    value = 上下文.getXXX();
}
public void methodB(){
     上下文.setXXX(value);
}
以上代码只是示例，实际编码过程中我们不会写侵入性这么强的代码，上下文值的设置和获取会被写在拦截器当中

**Comment by mercyblitz** [comment]
我直觉地认为自定义 ThreadLocal是否可以满足?

**Comment by chickenlj** [comment]
@hsrong  你的需求是否同这个相同 #889，你们目前期待使用这种方式的典型业务场景是？

**Comment by hsrong** [comment]
@chickenlj 是相同的，我是做架构的，我希望通过这种使用方式实现对业务方法做一些控制，对业务方法来说，这些控制是透明的。
实际上我已经实现了，如下：
![image](https://user-images.githubusercontent.com/13184705/33114475-01f797dc-cf98-11e7-9d15-911469f63002.png)
![image](https://user-images.githubusercontent.com/13184705/33114544-3f9690ac-cf98-11e7-89b5-1fcb645d888c.png)
![image](https://user-images.githubusercontent.com/13184705/33114614-88095766-cf98-11e7-9fd7-0b4b22e2217a.png)
实现得有问题希望指正，既然你们重启维护，希望还是由你们来实现

**Comment by devenfan** [comment]
@hsrong 其实你提交一个Pull Request可能来得更快…… 哦，你不会是在dubbox上修改的吧？

**Comment by chickenlj** [comment]
@hsrong You can create a Pull Request

**Comment by chickenlj** [comment]
#889

**Comment by Authorlove** [comment]
consider adding new protocol version for the comparability

**Comment by iorilchen** [comment]
泛型调用时consumer端获取服务端传过来的attachment，获取不到
