### ISSUE TITLE
dubbo:consumer的filter属性能否取消长度限制

### ISSUE THREAD

**Issue by hsrong** [alibaba/dubbo#907]
<dubbo:consumer check="false" filter="default,-exception,ConsumerDubboFilterChain"></dubbo:consumer>，<dubbo:provider filter="default,-exception,ProviderDubboFilterChain"></dubbo:provider>
filter属性能否取消长度限制，因为我们会有很多过滤器，很容易超长，目前好像是限制100个字符，超长了启动就会报错

**Comment by manzhizhen** [comment]
最新版本已经改成了200

**Comment by hsrong** [comment]
@manzhizhen 200恐怕也不够吧，我特别喜欢用长名字来实现自注释

**Comment by Knight-Wu** [comment]
对的, 我这边的环境也碰到了这个问题, 是为了性能考虑吗, 而且貌似不支持自定义配置
