### ISSUE TITLE
dubbo:protocol codec不可用，不能配置，也不能扩展

### ISSUE THREAD

**Issue by loushi135** [alibaba/dubbo#913]
<dubbo:protocol name="dubbo" port="${dubbo.port}" codec="xxx"/>
目前codec配置还是使用的@Deprecated Codec接口，
而DubboProtocol 使用的是Codec2接口，#272行写死的 dubbo 希望将codec实现配置化

用处： 目前项目使用的dubbox，dubbox改动了通信协议，希望使用插件化codec兼容处理

**Comment by chickenlj** [comment]
The core features of dubbox have been merged into dubbo in 2.6.0, we recommend you upgrade to 2.6.0.

We don't recommend you use the deprecated Codec interface, and also don't recommend extend of core RPC protocol.
