### ISSUE TITLE
建议合并Dubbox，版本升级至2.9.0

### ISSUE THREAD

**Issue by devenfan** [alibaba/dubbo#918]
社区广泛采用了Dubbox，建议合并Dubbox的代码，由于dubbox版本号使用了2.8.x，版本可考虑升级至2.9.0

**Comment by devenfan** [comment]
#801 #667 #747 #701 #491

**Comment by devenfan** [comment]
这里面除了代码的合并，关键还有社区的合并。

**Comment by takeseem** [comment]
加油！建议兼容性上一定要考虑下，线上在升级过程中会出现新老版本相互调用情形，甚至哪怕通过判断dubbo版本来做兼容处理也ok。比如 #911 

体会飞行中换引擎。。。

**Comment by qinliujie** [comment]
已经考虑合并部分PR

**Comment by chickenlj** [comment]
REST has been released in [2.6.0](https://github.com/alibaba/dubbo/releases).
