### ISSUE TITLE
多IP环境下，consumer不能匹配到providers

### ISSUE THREAD

**Issue by YoKv** [alibaba/dubbo#921]
win10环境，安装docker后，本地有多个ip，非docker容器启动项目，dubbo自动选择了docker的ip，导致服务调用不到，有什么解决办法

**Comment by devenfan** [comment]
这是docker的网络问题，需要让服务注册器所在节点可以访问你docker的网络，目前Linux上可以有docker网络组件解决这个问题

**Comment by xuanzi200** [comment]
@devenfan

请问一下，这个组件什么啊？  K8S里面有没有类似的组件？

**Comment by Coneboy-k** [comment]
@ThorinChen 使用calico 组件就可以 。
