### ISSUE TITLE
'Multi connections' configuration problem in <dubbo-user-book>

### ISSUE THREAD

**Issue by manzhizhen** [alibaba/dubbo#927]
dubbo-user-book.pdf中关于多连接配置有如下一段描述：

多连接配置:
Dubbo 协议缺省每服务每提供者每消费者使用单一长连接,如果数据量较大,可以使用多个 连接。
 <dubbo:protocol name="dubbo" connections="2" />

但其实dubbo:protocol应该没有connections属性可以配置，dubbo:service和dubbo:reference才有，是笔误吗？

**Comment by chickenlj** [comment]
I think `<dubbo:protocol />` should support `connections` configuration.
