### ISSUE TITLE
管理、监控UI改进

### ISSUE THREAD

**Issue by oohusl** [alibaba/dubbo#930]
是否有计划改善管理、监控的UI？比如采用前后端分离、类似[ant-design-pro](https://pro.ant.design)的前端模版重新实现UI。如该建议符合项目的路径，我可以组织人力实施

**Comment by qinliujie** [comment]
非常赞！！！我们后续会单独私聊你！！！

**Comment by oohusl** [comment]
OK 可能还涉及到一些后台接口的修改

**Comment by 251795891** [comment]
若需要人手并对外，我报个名....

**Comment by mercyblitz** [comment]
你这个确认有没有版权问题？

**Comment by 356082462** [comment]
@qinliujie 管理、监控、服务治理可以私聊下，我们也可以提供相关人员的支持。

**Comment by 356082462** [comment]
@qinliujie https://github.com/dubboclub/dubbokeeper 这个项目主要做的是dubbo的管理和监控，是否已经考量过了？

**Comment by chickenlj** [comment]
dubbo/dubbo-ops#11

**Comment by kimmking** [comment]
可以联系dubbokeeper的作者，一起参与
