### ISSUE TITLE
客户端dubbo:protocol 中配置了client，但在ReferenceBean中没生效

### ISSUE THREAD

**Issue by 251795891** [alibaba/dubbo#931]
dubbo:protocol 中配置了client如下：
    <dubbo:protocol name="dubbo"  client="netty4" host="${dubbo.host}" port="${dubbo.port}"/>
发现启动时，ReferenceBean还是使用默认的netty（服务提供端已经通过server="netty4"）。

查看源码发现ReferenceBean继承自ReferenceConfig，ReferenceConfig和ReferenceBean2者都没有设置过ProtocolConfig，无法获取到dubbo:protocol 中配置的client值。
且在ReferenceConfig.init中构建url需要的map也没办法获取到dubbo:protocol中的配置项。

客户端只有通过2种来进行设置：1 ReferenceBean单个设置client；2 consumer中设置client。

dubbo:protocol 中client对于ReferenceBean无效。或者dubbo:protocol中的client有其他作用？
查看文档发现dubbo:protocol是服务提供者协议配置。如果只是对服务者有效，dubbo:protocol中的client具体作用是什么呢？

**Comment by qinliujie** [comment]
是这样的，protocol  的 server 是对自身的设置，client 是期望消费端使用的。。。。如果你想消费者 ReferenceBean 不配置 client,你可以在服务端设置这个client 值。。。。。但是这样会有一个风险，就是你的客户端没有如果没有 netty4 的 Transporter，客户端将会报错，所以，建议谨慎在服务端设置这个值
