### ISSUE TITLE
Compatibility concerns: deploy dubbo on K8S(Kubernetes)

### ISSUE THREAD

**Issue by ThorinChen** [alibaba/dubbo#937]
由于dubbo运行在docker容器中，会注册docker的私有地址(docker容器的IP是自动随机分配的)，消费端pod调用服务端pod会跨网段，导致无法调用，现在遇到这样一个问题。请问一下,怎样处理能够解决这个问题？

现在容器构建越来越火，麻烦详细解答，这样对推广dubbo有重大意义？

@ludvik 
@zhuzhaoyuan 
@wangchangbing 
@JacksonTian 
@kiminotes

**Comment by everhopingandwaiting** [comment]
用域名不行吗？ Docker -h 指定  hostname

**Comment by yefengyueyuan** [comment]
我们目前也是将dubbo运行容器中，你说的这个是由于消费者和服务提供者没有在一个k8s里面导致的,只有当消费者和服务者全部是docker化，如果消费端是在docker之外，那么服务端必须是主机模式

**Comment by Authorlove** [comment]
@chickenlj 可以给个文档

**Comment by chickenlj** [comment]
@xuanzi200 You can specify the specific ip/port: https://github.com/dubbo/dubbo-docker-sample

**Comment by AlexFinder** [comment]
可以采用路由表的方案，是可以解决访问容器内dubbo服务的
http://www.jianshu.com/p/3abf44ad77e6
