### ISSUE TITLE
dubbo 2.5.7 monitor-simple有个bug

### ISSUE THREAD

**Issue by Zxnui** [alibaba/dubbo#938]
dubbo-simple/dubbo-monitor-simple/src/main/resources/META-INF/spring/dubbo-monitor-simple.xml中，有以下配置：
`<bean id="monitorService" class="com.alibaba.dubbo.monitor.simple.SimpleMonitorService">`
`    <property name="statisticsDirectory" value="${dubbo.statistics.directory}"/>`
`    <property name="chartsDirectory" value="${dubbo.charts.directory}"/>`
`</bean>`
 
而com.alibaba.dubbo.monitor.simple.SimpleMonitorService这个类中的statisticsDirectory和chartsDirectory只是单纯的string,无get和set方法。无法通过配置文件写入属性

运行的时候报错，增加了对应的get和set方法，重新打包，可以运行

**Comment by ayhero** [comment]
以上问题也遇到了+1
