### ISSUE TITLE
dubbo官网路由规则介绍错误

### ISSUE THREAD

**Issue by tuser4198** [alibaba/dubbo#946]

**Comment by tuser4198** [comment]
public List<Invoker<T>> list(Invocation invocation) throws RpcException {    if (destroyed) {        throw new RpcException("Directory already destroyed .url: " + getUrl());    }    List<Invoker<T>> invokers = doList(invocation);    List<Router> localRouters = this.routers; // local reference    if (localRouters != null && localRouters.size() > 0) {        for (Router router : localRouters) {            try {                if (router.getUrl() == null \|\| router.getUrl().getParameter(Constants.RUNTIME_KEY, true)) {                    invokers = router.route(invokers, getConsumerUrl(), invocation);                }            } catch (Throwable t) {                logger.error("Failed to execute router: " + getUrl() + ", cause: " + t.getMessage(), t);            }        }    }    return invokers;}
--

**Comment by tuser4198** [comment]
错误1
错误所在页面地址：https://dubbo.gitbooks.io/dubbo-user-book/demos/routing-rule.html
错误点：runtime的缺省值是false。
纠错：经源码分析缺省值为true
源码如下：
`public List<Invoker<T>> list(Invocation invocation) throws RpcException {
    if (destroyed) {
        throw new RpcException("Directory already destroyed .url: " + getUrl());
    }
    List<Invoker<T>> invokers = doList(invocation);
    List<Router> localRouters = this.routers; // local reference
    if (localRouters != null && localRouters.size() > 0) {
        for (Router router : localRouters) {
            try {
                if (router.getUrl() == null || router.getUrl().getParameter(Constants.RUNTIME_KEY, true)) {
                    invokers = router.route(invokers, getConsumerUrl(), invocation);
                }
            } catch (Throwable t) {
                logger.error("Failed to execute router: " + getUrl() + ", cause: " + t.getMessage(), t);
            }
        }
    }
    return invokers;
}`

**Comment by tuser4198** [comment]
错误2
错误所在页面地址：https://dubbo.gitbooks.io/dubbo-dev-book/content/impls/router.html
错误点：官网显示 dubbo路由扩展支持protocol和provider级别的扩展
纠错：无论是从官网的路由规则配置页，dubbo admin的路由配置，zk注册中心的router url还是debug分析router匹配过程都是最多到服务级别，另外ProtocolConfig和DubboConfig也没有router属性，所以目前是不可能配置到protocol和provider级别的。

**Comment by chickenlj** [comment]
@tuser4198  

> 错误1
错误所在页面地址：https://dubbo.gitbooks.io/dubbo-user-book/demos/routing-rule.html
错误点：runtime的缺省值是false。
纠错：经源码分析缺省值为true
源码如下：

`if (!router.getUrl().getParameter(Constants.RUNTIME_KEY, true))`
The document and If condf. is inconsistent, i will keep the doc unchanged and fix the problem by change the code.

> 错误2错误所在页面地址：https://dubbo.gitbooks.io/dubbo-dev-book/content/impls/router.html
错误点：官网显示 dubbo路由扩展支持protocol和provider级别的扩展

I can't find any info about _dubbo support 'protocol' and 'provider' level extension_ in the dubbo-dev-book. The doc of [extension introduction](http://dubbo.io/books/dubbo-dev-book/impls/router.html) shows the way of extending route policies .

**Comment by tuser4198** [comment]
The doc of extension introduction really confuse me . So what does the following sentence mean?
<dubbo:protocol router="xxx" />

<dubbo:provider router="xxx" />

**Comment by chickenlj** [comment]
Sorry, i didn't notice that part. 
Currently, dubbo only support dynamic route config, that is the way you mentioned in http://dubbo.io/books/dubbo-user-book/demos/routing-rule.html. 
`<dubbo:protocol router="xxx" /> and <dubbo:provider router="xxx" />` is not supported, and i'll remove this from the document.

In addition, we are planning to enhance the route functionality.

**Comment by tuser4198** [comment]
OK.I  am really looking forward to the enhanced route functionality. By the way, Can I join Dubbo translation group?  And If OK, I want to know the schedule , in order to arrange mine ahead of time.

**Comment by tuser4198** [comment]
I have got task，ignore this comment pls.
