### ISSUE TITLE
Document Translation

### ISSUE THREAD

**Issue by chickenlj** [alibaba/dubbo#948]
# dubbo-user-book
How to contribute?  
Create pull request or push directly to the main repository [dubbo-user-book-en](https://github.com/dubbo/dubbo-user-book-en). Keep the directory structure and file name same with the Chinese Edition. 

## part1 - **light**
#950  zhjwpku. done
## part2 - **moderate**
#951 banyeliangzhong done
## part3 - **moderate**
#952 weipeng2k  hengyunabc done
## part4 - **moderate**
#953 Hanson1129 cvictory done
## part5 - **moderate**
#954 qinliujie chickenlj done
## part6 - **moderate**
#955 uglycow diecui1202 half
## part7 - **moderate**
#956 beiwei30 done
## part8 - **bit heavy**
#957  lovepoem done
## part9 - 
#1047  chickenlj

**Comment by chickenlj** [comment]
# dubbo-dev-book
## task1
[dubbo-dev-book/impls](https://github.com/dubbo/dubbo-dev-book/tree/master/impls)

## task2
[dubbo-dev-book/principals](https://github.com/dubbo/dubbo-dev-book/principals)

## task3
[dubbo-user-book](https://github.com/dubbo/dubbo-dev-book) 下的所有markdown文件，不包含子文件夹

**Comment by chickenlj** [comment]
# dubbo-admin-book

[All by one](https://github.com/dubbo/dubbo-admin-book)

**Comment by lovepoem** [comment]
分给我一章吧

**Comment by chickenlj** [comment]
@lovepoem Please pick one sub-issue yourself, remember comment under the issue you pick

**Comment by zhjwpku** [comment]
I think I can help~
But is there any conventions like should we create a separate file with a '-en' suffix or something like that?

**Comment by chickenlj** [comment]
> How to contribute?
> Create pull request or push directly to the main repository dubbo-admin-book-en. Keep the directory structure and file name same with the Chinese Edition.

We can cooperate this way. You can first pick one part and create pull request to the corresponding repository

**Comment by mercyblitz** [comment]
Haha, Great first step!

**Comment by lovepoem** [comment]
Which  markdown desktop tool do you use？ I user [Typora](http://typora.io) on the mac deskop，It feels nice

**Comment by stoneapple** [comment]
Good project！I want to join, is there any chapter that i can help @chickenlj

**Comment by luffyke** [comment]
I think i could help.

**Comment by chickenlj** [comment]
@stoneapple @luffyke  Welcome to join us, i've give both of you some pages for translation. Please  check [here](https://github.com/alibaba/dubbo/issues/960) for details. 
Thank you.

**Comment by dongxuwang** [comment]
I'd like to join.

**Comment by sujiujun** [comment]
I'd like to ...
