### ISSUE TITLE
Could not access dubbo user guide

### ISSUE THREAD

**Issue by ralf0131** [alibaba/dubbo#962]
Hi,

I have some trouble accessing the dubbo user guide: 

https://dubbo.gitbooks.io/dubbo-user-book/

the network seems to be unstable.

Does anyone have the same issue here?

**Comment by yuki-lau** [comment]
For some special reasons, the avalibility of gitbook site is not stable recently in China.

Dubbo team is moving the dubbo-user-book from gitbook to a stable server :)

Thanks

**Comment by chickenlj** [comment]
New address published, try it here: http://dubbo.io/books/dubbo-user-book/
