### ISSUE TITLE
Malformed documentation format

### ISSUE THREAD

**Issue by ralf0131** [alibaba/dubbo#963]
Hi,

It looks like something goes wrong with the following documentation:

https://dubbo.gitbooks.io/dubbo-user-book/references/xml/dubbo-service.html

please refer to the attached pic for more details.

![image](https://user-images.githubusercontent.com/4397305/33360138-56ae6f92-d50d-11e7-8e32-05d2b97cab98.png)

**Comment by chickenlj** [comment]
It's been fixed, thx.
