### ISSUE TITLE
How to config dubbo:monitor

### ISSUE THREAD

**Issue by ThorinChen** [alibaba/dubbo#964]
当需要dubb-monitor进行监控的时候，需要添加配置
<dubbo:monitor protocol="registry" /> 
适用于生产环境

开发人员在开发的时候，不需要该项配置，这个里面有没有什么参数可以不调用monitorService进行监控

或者mvn的profile编译时，不在配置中加入<dubbo:monitor protocol="registry" /> 

@ludvik 
@zhuzhaoyuan 
@wangchangbing

**Comment by chickenlj** [comment]
Please track this question here. [How to config dubbo:monitor](https://groups.google.com/forum/?hl=en#!topic/dubbo/oIQf4BihawA)
