### ISSUE TITLE
Can dubbo refer to the same provider node in a consistent, continuous requests

### ISSUE THREAD

**Issue by 1991wangliang** [alibaba/dubbo#965]
例如：有这样一次请求，有a模块和b模块。a模块先调用了一下b模块，再执行本地业务，然后再调用了一次b模块，之后结束业务。

b模块是做了负载的，就是存在多个b模块。dubbo框架如何在a模块下控制两次请求的b模块是同一个模块？

**Comment by 1991wangliang** [comment]
我配置了一个LoadBalance
```
public class MyLoadBalance implements LoadBalance{



    @Override
    public <T> Invoker<T> select(List<Invoker<T>> invokers, URL url, Invocation invocation) throws RpcException {
        System.out.println(url);
        System.out.println(invocation);
        System.out.println(invokers);
        return null;
    }
}
```
com.alibaba.dubbo.rpc.cluster.LoadBalance 
```
myLoadBalance = com.demo.balance.MyLoadBalance

```
xml

```

    <dubbo:provider loadbalance="myLoadBalance" />

```

调用模块的时候为什么不执行进来呢？

dubbo  2.5.3 版本

**Comment by 1991wangliang** [comment]
dubbo 2.5.7 版本也不走.

**Comment by chickenlj** [comment]
[Argument of BitSet type lost](https://groups.google.com/forum/?hl=en#!topic/dubbo/U2QAsl_KQWo)
This issue is moved here,  we recommend use google groups for discussing.

**Comment by 1991wangliang** [comment]
ok 我在 Google groups 下回复了，需要翻墙才行。。 我用LoadBalance是为了达到我上面说的效果，首先这样做的话可行的吧？

**Comment by Authorlove** [comment]
Check if RpcContext has the latest call’s ip and set it for next invocation

**Comment by chickenlj** [comment]
http://dubbo.io/books/dubbo-user-book/demos/stickiness.html
