### ISSUE TITLE
Argument of BitSet type lost

### ISSUE THREAD

**Issue by zsolver** [alibaba/dubbo#966]
consumer 传递包含BitSet类型参数，provider 获取BitSet内值为空，没有报任何错误。
dubbo版本2.5.3，java1.8

**Comment by chickenlj** [comment]
[Argument of BitSet type lost](https://groups.google.com/forum/?hl=en#!topic/dubbo/_44QE3lWs-A)
This issue is moved here,  we recommend use google groups for discussing.

**Comment by zsolver** [comment]
It was solved, thanks for your help
