### ISSUE TITLE
NamedThreadFactory typo: mDaemo

### ISSUE THREAD

**Issue by xingguang2013** [alibaba/dubbo#968]
[NamedThreadFactory](https://github.com/alibaba/dubbo/blob/master/dubbo-common/src/main/java/com/alibaba/dubbo/common/utils/NamedThreadFactory.java)属性mDaemo单词拼写错误，应该是mDaemo**n**

**Comment by chickenlj** [comment]
Fixed: 22385dc804d550ea9f415bc9f96c2d6d10139e92
