### ISSUE TITLE
When will the dubbo-springboot-starter be released?

### ISSUE THREAD

**Issue by zshi456** [alibaba/dubbo#973]
Is there a time schedule?

**Comment by ralf0131** [comment]
Hi, please check out this awesome project: https://github.com/dubbo/dubbo-spring-boot-project

**Comment by slatonwu** [comment]
依赖的dubbo还是2.5.3

**Comment by lovepoem** [comment]
>依赖的dubbo还是2.5.3
A refactoring issue is in progress by @
