### ISSUE TITLE
Without interface definition, only knows the interface name and method name, can i invoke dubbo dynaically?

### ISSUE THREAD

**Issue by civism** [alibaba/dubbo#975]
I am developing a distributed schedule system based on dubbo services. In order to invoke the remote dubbo service, i must have all the service definition on the schedule system. 
Is it possible to invoke a remote service without the service definition(.class file)?

**Comment by lovepoem** [comment]
https://github.com/elasticjob/elastic-job this can help you. you needn't rpc call to finish your requirement

**Comment by chickenlj** [comment]
[Generic Reference](http://dubbo.io/books/dubbo-user-book/demos/generic-reference.html) may help.
