### ISSUE TITLE
Any progress info for 2.5.8?

### ISSUE THREAD

**Issue by fanlei1988** [alibaba/dubbo#978]
I am looking forward  to the 2.5.8 version.

**Comment by chickenlj** [comment]
please track this issue [here](https://groups.google.com/forum/#!topic/dubbo/P-lQSaD-NS4)

may be you need a vpn to visit.

**Comment by chickenlj** [comment]
See #986

**Comment by fanlei1988** [comment]
@chickenlj thank you very much。
