### ISSUE TITLE
Has the 2.5.8 version released？

### ISSUE THREAD

**Issue by woldwang** [alibaba/dubbo#986]
Has the 2.5.8 version released？

**Comment by chickenlj** [comment]
It will be released soon, maybe within this week.

**Comment by Comven** [comment]
请问2.5.8的release版本是否会同时发布spring-boot版本的starter？

**Comment by woldwang** [comment]
Great! Thx！

**Comment by luffyke** [comment]
Would 2.5.8 update spring version and zookeeper version to the newest?

**Comment by woldwang** [comment]
How about RESTful?

**Comment by woldwang** [comment]
How about RESTful support?

**Comment by lovepoem** [comment]
It's released
