### ISSUE TITLE
zookeeper'Dubbo path has come out many strange nodes

### ISSUE THREAD

**Issue by Liubey** [alibaba/dubbo#988]
![image](https://user-images.githubusercontent.com/5568302/33536875-5d7a59d0-d87d-11e7-968b-c156d490b4aa.png)

black is start with com.* 
in addition，we use "GenericService mode" to invoke the real services

**Comment by Liubey** [comment]
many many nodes, cause we can‘t connect zk to list these paths in cli.

**Comment by DocEcho** [comment]
这个 2525 是 ／ 多次 encode 出来的

**Comment by chickenlj** [comment]
I have encountered this problem before, you must have wrote ZK from other systems. 
Please check your program. @DocEcho suggest one possibility.

**Comment by dayforward** [comment]
不止一次遇到这个问题了，请教一下各位大神，非常感谢！

**Comment by Jukewu** [comment]
同样遇到过这个问题，没找到原因

**Comment by Liubey** [comment]
为什么要close，还没解决问题呢 @chickenlj

**Comment by chickenlj** [comment]
Hi, Eason

This is very likely to be a env-related problems, do you have other systems writing data to ZK registry except for dubbo framework? I mean systems like dubbo-admin, which will write data to registry. Please remove the mosaic on the picture, so we can see this data was created by which part/feature.

Please send more details of this issue to dev@dubbo.apache.org for further discussion. We tend to discuss questions like this there.

**Comment by yjqg6666** [comment]
got the same problem.

**Comment by yjqg6666** [comment]
php > var_dump(urldecode("%24"));
string(1) "$"
php > var_dump(urlencode("%24"));
string(5) "%2524"
php > var_dump(urlencode("%2524"));
string(7) "%252524"
php > var_dump(urlencode("%252524"));
string(9) "%25252524"
php > var_dump(urlencode("%25252524"));
string(11) "%2525252524"

interface命名中含有特殊符号，然后多次转义的情况下会这样。　
转义是在什么情况下执行的？什么情况下会再次转义？　
我们有接口使用的是子类用到了$　出现了多个252524。
zk节点下面都有[consumers, routers, providers, configurators] 且下级内容均为空，很大可能性是由dubbo写入的。

**Comment by yjqg6666** [comment]
@Liubey  
php > var_dump(urldecode("%2C"));
string(1) ","

**Comment by yun2018** [comment]
> ![图片](https://user-images.githubusercontent.com/5568302/33536875-5d7a59d0-d87d-11e7-968b-c156d490b4aa.png)
> 
> 黑色以com.*开头， 另外，我们使用“GenericService模式”来调用真正的服务
老哥，这个后面咋解决的啊，现在也遇到了，求解中！！

**Comment by yun2018** [comment]
老哥，麻烦问下这个问题有方法解决么
