### ISSUE TITLE
Will dubbo provider a spring-boot-starter to simplify configuration?

### ISSUE THREAD

**Issue by o624366705** [alibaba/dubbo#991]
能否提供 dubbo-spring-boot-starter 启动配置模块?简化dubbo配置,同样xml配置能写在yaml里面自动装载就好多了

**Comment by javahongxi** [comment]
https://github.com/dubbo/dubbo-spring-boot-project

**Comment by smartbetter** [comment]
Can you update the version? this project dubbo version is 2.5.3.

**Comment by javahongxi** [comment]
Thanks, @smartbetter , now exclude dubbo in spring-boot-starter-dubbo

**Comment by javahongxi** [comment]
Good idea, @smartbetter

**Comment by sunhao-java** [comment]
PS:
这样配置的话，一个application只能有一个register？是不是说，同一个application中，所有服务只能注册到一个注册中心？这样的话，是不是有点不太好啊？
