### ISSUE TITLE
dubbo-demo set "java.net.preferIPv4Stack" not work

### ISSUE THREAD

**Issue by huangyunbin** [alibaba/dubbo#997]
System.setProperty("java.net.preferIPv4Stack", "true");  // not  work  (error is Can't assign requested address)
-Djava.net.preferIPv4Stack=true  // sucess

my os is mac.

ps:  in debug model,  System.setProperty("java.net.preferIPv4Stack", "true") is always sucess.  this makes me hard to understand

**Comment by qinliujie** [comment]
I have search openjdk and found that https://bugs.openjdk.java.net/browse/JDK-6964714 ,but this bug had been fixed.I think it is IDE bug.....because I pack it to a jar, and it work well.......

**Comment by qinliujie** [comment]
when I use IDEA to run this application,I found IDEA load a javaagent /Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar, I remove this javaagent in command line ,and it begin to work well
