### ISSUE TITLE
dubbo-demo Consumer error: 22222 port  already in use

### ISSUE THREAD

**Issue by huangyunbin** [alibaba/dubbo#998]
Provider and Consumer in the same machine,they are start com.alibaba.qos.server.Server.
com.alibaba.qos.common.Constants.DEFAULT_PORT = 22222.
so the 22222 port  conflict。

solution: Consumer main method add  System.setProperty("dubbo.qos.port", "33333");

**Comment by chickenlj** [comment]
Thx, we should use two different ports.

@qinliujie  How to specify a specific port?

**Comment by qinliujie** [comment]
see #1003
